// Whittle puzzles.
//
// Each puzzle has:
//   start - a six-letter word, in capitals
//   steps - three [clue, answer] pairs. Each answer is the word before it with one letter
//           removed and the other letters kept in the same order (PLANET, PLANT, PLAN, PAN).
//
// Every game picks four of these at random. All puzzles must be original.

// A chain marked retired: true is kept only so past daily sets still load. It is left out of
// random play and of any day scheduled from now on. No step may simply drop a plural S.
window.WHITTLE_PUZZLES = [
  { start: "PLANET", steps: [["Something that grows in soil", "PLANT"], ["A scheme", "PLAN"], ["You fry an egg in it", "PAN"]] },
  { start: "STRAIN", steps: [["It runs on rails", "TRAIN"], ["It falls from clouds", "RAIN"], ["Moved fast on foot", "RAN"]] },
  { start: "BRANDY", steps: [["A company's name and logo", "BRAND"], ["The husk of a grain", "BRAN"], ["To forbid", "BAN"]] },
  { start: "SPRINT", steps: [["To put ink on paper", "PRINT"], ["A measure of beer", "PINT"], ["It holds fabric in place", "PIN"]] },
  { retired: true, start: "CHEATS", steps: [["To break the rules", "CHEAT"], ["Warmth", "HEAT"], ["Worn on the head", "HAT"]] },
  { retired: true, start: "PAINTS", steps: [["To coat a wall with colour", "PAINT"], ["To breathe hard", "PANT"], ["A small insect", "ANT"]] },
  { start: "STABLE", steps: [["You eat dinner at it", "TABLE"], ["A story", "TALE"], ["A kind of beer", "ALE"]] },
  { start: "SCARED", steps: [["To frighten", "SCARE"], ["To look after", "CARE"], ["You drive it", "CAR"]] },
  { retired: true, start: "BOARDS", steps: [["A flat length of wood", "BOARD"], ["A wild pig", "BOAR"], ["It rows a boat", "OAR"]] },
  { retired: true, start: "PLEASE", steps: [["Appeals or requests", "PLEAS"], ["What a defendant enters in court", "PLEA"], ["A small green vegetable", "PEA"]] },
  { start: "FRIEND", steps: [["A demon or villain", "FIEND"], ["To locate", "FIND"], ["A fish steers with it", "FIN"]] },
  { retired: true, start: "CHARTS", steps: [["A map for sailors", "CHART"], ["A friendly talk", "CHAT"], ["A pet that purrs", "CAT"]] },
  { retired: true, start: "SWINGS", steps: [["It hangs in a playground", "SWING"], ["A bird flaps it", "WING"], ["To come first", "WIN"]] },
  { retired: true, start: "THINKS", steps: [["To use your mind", "THINK"], ["Not thick", "THIN"], ["A metal used for cans", "TIN"]] },
  { start: "STRIPE", steps: [["To peel away", "STRIP"], ["A journey", "TRIP"], ["A waiter hopes for one", "TIP"]] },
  { retired: true, start: "CRATES", steps: [["A wooden shipping box", "CRATE"], ["A speed or a price", "RATE"], ["A rodent", "RAT"]] },
  { retired: true, start: "GRAINS", steps: [["One seed of wheat", "GRAIN"], ["To get more of something", "GAIN"], ["A spirit mixed with tonic", "GIN"]] },
  { retired: true, start: "SPARKS", steps: [["A tiny flash from a fire", "SPARK"], ["A green space in town", "PARK"], ["Noah built one", "ARK"]] },
  { retired: true, start: "CLEANS", steps: [["Not dirty", "CLEAN"], ["A family group, in Scotland", "CLAN"], ["Beans come in one", "CAN"]] },
  { retired: true, start: "FLOATS", steps: [["To stay on the surface", "FLOAT"], ["Level, with no bumps", "FLAT"], ["Not thin", "FAT"]] },
  { retired: true, start: "SHEARS", steps: [["To clip a sheep's wool", "SHEAR"], ["To use your ears", "HEAR"], ["It is on the side of your head", "EAR"]] },
  { retired: true, start: "BRINGS", steps: [["To carry something here", "BRING"], ["Worn on a finger", "RING"], ["A drilling platform at sea", "RIG"]] },
  { retired: true, start: "SLEEPS", steps: [["What you do at night", "SLEEP"], ["To leak slowly through", "SEEP"], ["To use your eyes", "SEE"]] },
  { retired: true, start: "STEAMS", steps: [["It rises from a kettle", "STEAM"], ["Where two pieces of cloth are stitched", "SEAM"], ["Ships sail on it", "SEA"]] },
  { start: "BRIDGE", steps: [["She walks down the aisle", "BRIDE"], ["A trip on a bike or a horse", "RIDE"], ["To be free of something", "RID"]] },
  { retired: true, start: "TRAILS", steps: [["A path through the woods", "TRAIL"], ["A dog wags it", "TAIL"], ["To be unwell", "AIL"]] },
  { start: "SPLINT", steps: [["To divide in two", "SPLIT"], ["A narrow cut", "SLIT"], ["To take a seat", "SIT"]] },
  { retired: true, start: "PLATES", steps: [["You eat from it", "PLATE"], ["After the agreed time", "LATE"], ["Had a meal, in the past", "ATE"]] },
  { retired: true, start: "GRAPES", steps: [["Wine is made from it", "GRAPE"], ["To stare open-mouthed", "GAPE"], ["A big monkey-like animal", "APE"]] },
  { retired: true, start: "CLAMPS", steps: [["It holds wood while glue dries", "CLAMP"], ["To applaud", "CLAP"], ["A hat with a peak", "CAP"]] },
  { retired: true, start: "WHEELS", steps: [["It turns on an axle", "WHEEL"], ["The back of your foot", "HEEL"], ["A snake-like fish", "EEL"]] },
  { retired: true, start: "SPINES", steps: [["Your backbone", "SPINE"], ["An evergreen tree", "PINE"], ["Baked with a crust", "PIE"]] },
  { retired: true, start: "BEARDS", steps: [["Hair on the chin", "BEARD"], ["It threads onto a necklace", "BEAD"], ["You sleep in it", "BED"]] },
  { retired: true, start: "BLINKS", steps: [["Eyes do it in a flash", "BLINK"], ["One ring of a chain", "LINK"], ["Pens are filled with it", "INK"]] },
  { retired: true, start: "CRAFTS", steps: [["A skilled trade done by hand", "CRAFT"], ["A floating platform of logs", "RAFT"], ["Towards the back of a boat", "AFT"]] },
  { retired: true, start: "SHOUTS", steps: [["To yell", "SHOUT"], ["Fired from a gun", "SHOT"], ["Not cold", "HOT"]] },
  { retired: true, start: "CHARMS", steps: [["A lucky trinket", "CHARM"], ["Damage or injury", "HARM"], ["Meat from a pig", "HAM"]] },
  { retired: true, start: "TRAMPS", steps: [["A wanderer with no home", "TRAMP"], ["It catches animals", "TRAP"], ["Water comes out of it", "TAP"]] },
  { retired: true, start: "CLOTHS", steps: [["Fabric", "CLOTH"], ["A lump of thickened blood", "CLOT"], ["A baby's bed", "COT"]] },
  { retired: true, start: "SWEATS", steps: [["It beads on your skin when hot", "SWEAT"], ["You sit on it", "SEAT"], ["To have a meal", "EAT"]] },
  { start: "PRINCE", steps: [["What something costs", "PRICE"], ["A grain eaten with curry", "RICE"], ["Frozen water", "ICE"]] },
  { retired: true, start: "CHAIRS", steps: [["You sit on it", "CHAIR"], ["It grows on your head", "HAIR"], ["You breathe it", "AIR"]] },
  { retired: true, start: "BEASTS", steps: [["A wild animal", "BEAST"], ["To defeat", "BEAT"], ["It hangs upside down in caves", "BAT"]] },
  { retired: true, start: "TRENDS", steps: [["A fashion", "TREND"], ["To look after", "TEND"], ["Twice five", "TEN"]] },
  { retired: true, start: "SPARES", steps: [["An extra kept in reserve", "SPARE"], ["To practise boxing lightly", "SPAR"], ["A place to soak and relax", "SPA"]] },
  { start: "THREAD", steps: [["The grip on a tyre", "TREAD"], ["To take in words on a page", "READ"], ["The colour of a stop sign", "RED"]] },
  { retired: true, start: "SPOUTS", steps: [["A kettle pours from it", "SPOUT"], ["To push out your lips sulkily", "POUT"], ["Not in", "OUT"]] },
  { retired: true, start: "FLINTS", steps: [["A stone that makes sparks", "FLINT"], ["Fluff from the dryer", "LINT"], ["Set alight", "LIT"]] },
  { retired: true, start: "BLOATS", steps: [["To swell up", "BLOAT"], ["It floats", "BOAT"], ["A grain for porridge", "OAT"]] },
  { retired: true, start: "PEARLS", steps: [["A gem from an oyster", "PEARL"], ["The ringing of bells", "PEAL"], ["A friend", "PAL"]] },
  { retired: true, start: "BRACES", steps: [["A support that holds something steady", "BRACE"], ["A running contest", "RACE"], ["The top card in the pack", "ACE"]] },
  { retired: true, start: "SPRAYS", steps: [["A fine mist of liquid", "SPRAY"], ["To speak to a god", "PRAY"], ["To hand over money", "PAY"]] },
  { start: "STRING", steps: [["A bee does it", "STING"], ["To make music with your voice", "SING"], ["A wrongdoing", "SIN"]] },
  { retired: true, start: "SCOLDS", steps: [["To tell off", "SCOLD"], ["Not warm", "COLD"], ["Not new", "OLD"]] },
  { retired: true, start: "DRIVES", steps: [["To steer a car", "DRIVE"], ["To plunge headfirst into water", "DIVE"], ["To stop living", "DIE"]] },
  { retired: true, start: "GLOBES", steps: [["A model of the Earth", "GLOBE"], ["The soft bottom of your ear", "LOBE"], ["A high, gentle throw", "LOB"]] },
  { retired: true, start: "CREAMS", steps: [["The rich top of milk", "CREAM"], ["Five hundred sheets of paper", "REAM"], ["A male sheep", "RAM"]] },
  { retired: true, start: "CHILLS", steps: [["A cold feeling", "CHILL"], ["A small mountain", "HILL"], ["Unwell", "ILL"]] },
  { retired: true, start: "SPOILS", steps: [["To ruin", "SPOIL"], ["Earth in a garden", "SOIL"], ["It greases an engine", "OIL"]] },
  { retired: true, start: "STRAYS", steps: [["A lost pet", "STRAY"], ["To remain", "STAY"], ["To speak", "SAY"]] },
  { start: "PLUNGE", steps: [["A sudden forward thrust", "LUNGE"], ["You breathe with it", "LUNG"], ["To drag with effort", "LUG"]] },
  { retired: true, start: "BLENDS", steps: [["To mix together", "BLEND"], ["A curve in the road", "BEND"], ["The finish", "END"]] },
  { retired: true, start: "STEALS", steps: [["To take what is not yours", "STEAL"], ["A blue-green colour", "TEAL"], ["A hot drink", "TEA"]] },
  { retired: true, start: "SKIRTS", steps: [["Worn from the waist down", "SKIRT"], ["A short comic sketch", "SKIT"], ["A set of equipment", "KIT"]] },
  { retired: true, start: "SMARTS", steps: [["Clever", "SMART"], ["A market or store", "MART"], ["Paintings and sculpture", "ART"]] },
  { retired: true, start: "STARTS", steps: [["To begin", "START"], ["It twinkles at night", "STAR"], ["Black sticky stuff on roads", "TAR"]] },
  { retired: true, start: "PASTES", steps: [["A thick sticky mixture", "PASTE"], ["The time gone by", "PAST"], ["A gentle tap", "PAT"]] },
  { retired: true, start: "CHORDS", steps: [["Notes played together", "CHORD"], ["A length of string", "CORD"], ["A fish for frying", "COD"]] },
  { retired: true, start: "SLANTS", steps: [["A slope", "SLANT"], ["A thin strip of wood", "SLAT"], ["Took a seat", "SAT"]] },
  { retired: true, start: "GRUNTS", steps: [["A pig's sound", "GRUNT"], ["The smallest of a litter", "RUNT"], ["To move fast on foot", "RUN"]] },
  { retired: true, start: "GROWLS", steps: [["A dog's warning sound", "GROWL"], ["To get bigger", "GROW"], ["A line of seats", "ROW"]] },
  { retired: true, start: "CROWNS", steps: [["A king wears it", "CROWN"], ["A black bird that caws", "CROW"], ["It gives milk", "COW"]] },
  { retired: true, start: "STOOLS", steps: [["A seat with no back", "STOOL"], ["A hammer is one", "TOOL"], ["Also", "TOO"]] },
  { retired: true, start: "SLICES", steps: [["A piece of cake", "SLICE"], ["Tiny biting insects", "LICE"], ["An untruth", "LIE"]] },
  { retired: true, start: "CRUSTS", steps: [["The hard edge of a pizza", "CRUST"], ["Orange flakes on old iron", "RUST"], ["A groove worn into a track", "RUT"]] },
  { retired: true, start: "SPORTS", steps: [["Football is one", "SPORT"], ["A small round mark", "SPOT"], ["You cook soup in it", "POT"]] },
  { retired: true, start: "BRAIDS", steps: [["A plait of hair", "BRAID"], ["A sudden attack", "RAID"], ["Help", "AID"]] },
  { start: "TRIPLE", steps: [["Nonsense", "TRIPE"], ["Ready to eat", "RIPE"], ["To tear", "RIP"]] },
  { retired: true, start: "SCORES", steps: [["The points in a game", "SCORE"], ["The middle of an apple", "CORE"], ["Rock that contains metal", "ORE"]] },
  { retired: true, start: "BLOOMS", steps: [["A flower opening", "BLOOM"], ["A loud bang", "BOOM"], ["What a ghost says", "BOO"]] },
  // ---- Added 9 October 2026 ----
  { retired: true, start: "CHANTS", steps: [["Friendly talks", "CHATS"], ["They purr", "CATS"], ["Just one of them", "CAT"]] },
  { retired: true, start: "BROOMS", steps: [["Sudden rises in business", "BOOMS"], ["A loud bang", "BOOM"], ["What a ghost says", "BOO"]] },
  { retired: true, start: "SPEARS", steps: [["A pointed weapon", "SPEAR"], ["A friendly boxing practice", "SPAR"], ["A place for a massage", "SPA"]] },
  { retired: true, start: "PRINTS", steps: [["Put ink on paper", "PRINT"], ["A measure of beer or milk", "PINT"], ["A small sharp fastener", "PIN"]] },
  { retired: true, start: "GRINDS", steps: [["To crush into powder", "GRIND"], ["A pattern of squares", "GRID"], ["To get free of", "RID"]] },
  { retired: true, start: "THORNS", steps: [["A prickle on a rose", "THORN"], ["Ripped", "TORN"], ["A thousand kilograms", "TON"]] },
  { retired: true, start: "SWEEPS", steps: [["To brush the floor", "SWEEP"], ["To leak slowly", "SEEP"], ["To look with your eyes", "SEE"]] },
  { start: "SPLASH", steps: [["A long cut", "SLASH"], ["It grows on an eyelid", "LASH"], ["What is left after a fire", "ASH"]] },
  { retired: true, start: "CRAMPS", steps: [["A painful muscle spasm", "CRAMP"], ["To stuff in tightly", "CRAM"], ["A male sheep", "RAM"]] },
  { retired: true, start: "STOMPS", steps: [["To walk heavily", "STOMP"], ["Come to a halt", "STOP"], ["The highest point", "TOP"]] },
  { retired: true, start: "SWAMPS", steps: [["A wet, marshy area", "SWAMP"], ["To exchange", "SWAP"], ["The juice inside a tree", "SAP"]] },
  { retired: true, start: "CHAMPS", steps: [["The winner", "CHAMP"], ["A fellow, a bloke", "CHAP"], ["A hat with a peak", "CAP"]] },
  { retired: true, start: "SLINGS", steps: [["It supports a broken arm", "SLING"], ["To make music with your voice", "SING"], ["A wrongdoing", "SIN"]] },
  { retired: true, start: "CRANKS", steps: [["A handle you turn", "CRANK"], ["A position in an army", "RANK"], ["Moved fast on foot", "RAN"]] },
  { retired: true, start: "BLINDS", steps: [["They cover a window", "BLIND"], ["To tie up", "BIND"], ["Where rubbish goes", "BIN"]] },
  { retired: true, start: "GLANDS", steps: [["A body part that makes sweat or tears", "GLAND"], ["Dry ground", "LAND"], ["Plus", "AND"]] },
  { retired: true, start: "FLEETS", steps: [["A group of ships", "FLEET"], ["At the ends of your legs", "FEET"], ["A payment for a service", "FEE"]] },
  { retired: true, start: "SPENDS", steps: [["To pay out money", "SPEND"], ["To post a letter", "SEND"], ["The finish", "END"]] },
  { retired: true, start: "STANDS", steps: [["To be on your feet", "STAND"], ["On a beach", "SAND"], ["Unhappy", "SAD"]] },
  { retired: true, start: "STEAKS", steps: [["A slice of beef", "STEAK"], ["A hard wood used for furniture", "TEAK"], ["A hot drink", "TEA"]] },
  { retired: true, start: "CHORES", steps: [["A household task", "CHORE"], ["The centre of an apple", "CORE"], ["Rock with metal in it", "ORE"]] },
  { retired: true, start: "PLEATS", steps: [["A fold in a skirt", "PLEAT"], ["Soil fuel cut from a bog", "PEAT"], ["A cat or a dog", "PET"]] },
  { retired: true, start: "BLEATS", steps: [["The cry of a sheep", "BLEAT"], ["Rhythm", "BEAT"], ["A wager", "BET"]] },
  { retired: true, start: "GLOATS", steps: [["To brag about winning", "GLOAT"], ["It has horns and a beard", "GOAT"], ["Received", "GOT"]] },
  { retired: true, start: "STRAPS", steps: [["A band of leather", "STRAP"], ["It catches a mouse", "TRAP"], ["Turn it on for water", "TAP"]] },
  { retired: true, start: "HEARTS", steps: [["It pumps blood", "HEART"], ["Warmth", "HEAT"], ["What you do with food", "EAT"]] },
  { retired: true, start: "FEASTS", steps: [["A huge meal", "FEAST"], ["An impressive deed", "FEAT"], ["Not thin", "FAT"]] },
  { retired: true, start: "SPLITS", steps: [["To divide in two", "SPLIT"], ["What a llama might do to you", "SPIT"], ["Take a seat", "SIT"]] },
  { retired: true, start: "GRILLS", steps: [["To cook under a flame", "GRILL"], ["A fish breathes with it", "GILL"], ["Unwell", "ILL"]] },
  { retired: true, start: "GHOSTS", steps: [["It haunts a house", "GHOST"], ["The one who throws a party", "HOST"], ["Not cold", "HOT"]] },
  { retired: true, start: "BLEEDS", steps: [["Loses blood", "BLEED"], ["Lost blood", "BLED"], ["You sleep in it", "BED"]] },
  { retired: true, start: "BREEDS", steps: [["Kinds of dog", "BREED"], ["Brought up", "BRED"], ["The colour of a stop sign", "RED"]] },
  { retired: true, start: "THINGS", steps: [["An object", "THING"], ["Not fat", "THIN"], ["A metal can", "TIN"]] },
  { retired: true, start: "WRINGS", steps: [["To twist water out of a cloth", "WRING"], ["Worn on a finger", "RING"], ["To set up or fix a result", "RIG"]] },
  { retired: true, start: "GRASPS", steps: [["To grab hold", "GRASP"], ["A sharp breath", "GASP"], ["Petrol, in North America", "GAS"]] },
  { retired: true, start: "CLASPS", steps: [["A fastening on a necklace", "CLASP"], ["Applause", "CLAP"], ["The top of your thighs when sitting", "LAP"]] },
  { start: "GLANCE", steps: [["A knight's long spear", "LANCE"], ["Delicate fabric with holes", "LACE"], ["The best card", "ACE"]] },
  { retired: true, start: "POUNDS", steps: [["To hit hard again and again", "POUND"], ["A small lake", "POND"], ["Peas grow in it", "POD"]] },
  { retired: true, start: "FLIRTS", steps: [["To be playfully romantic", "FLIRT"], ["To move lightly and quickly", "FLIT"], ["In good shape", "FIT"]] },
  { retired: true, start: "GLINTS", steps: [["A flash of light", "GLINT"], ["Fluff from the dryer", "LINT"], ["Switched on", "LIT"]] },
  { retired: true, start: "HOARDS", steps: [["To store up in secret", "HOARD"], ["Not soft", "HARD"], ["Owned", "HAD"]] },
  { retired: true, start: "PRAWNS", steps: [["A shellfish like a shrimp", "PRAWN"], ["The weakest chess piece", "PAWN"], ["A cat's foot", "PAW"]] },
  { retired: true, start: "BROWNS", steps: [["To cook until golden", "BROWN"], ["Above the eye", "BROW"], ["A bend at the waist", "BOW"]] },
  { start: "SHOVEL", steps: [["To push roughly", "SHOVE"], ["Worn on a foot", "SHOE"], ["Not him", "SHE"]] },
  { start: "FAIRLY", steps: [["A tiny magical being", "FAIRY"], ["Just and honest", "FAIR"], ["Not near", "FAR"]] },
  { start: "FOURTH", steps: [["Onward, as in \"go ___\"", "FORTH"], ["A stronghold", "FORT"], ["In favour of", "FOR"]] },
  { start: "ORANGE", steps: [["A mountain chain, or a cooker", "RANGE"], ["Fury", "RAGE"], ["How old you are", "AGE"]] },
  { start: "HARDLY", steps: [["Tough, able to survive winter", "HARDY"], ["Not soft", "HARD"], ["Owned", "HAD"]] },
  { start: "REALLY", steps: [["A gathering of supporters", "RALLY"], ["A friend in a war", "ALLY"], ["Every one", "ALL"]] },
  { retired: true, start: "CORPSE", steps: [["A military unit", "CORPS"], ["Police officers, informally", "COPS"], ["Just one of them", "COP"]] },
  { start: "COURSE", steps: [["A spell of bad luck", "CURSE"], ["To make well", "CURE"], ["A hint, or a prompt", "CUE"]] },
  { start: "ABROAD", steps: [["Wide", "BROAD"], ["Cars drive on it", "ROAD"], ["A thin bar", "ROD"]] },
  { start: "SWITCH", steps: [["She rides a broomstick", "WITCH"], ["Together, not without", "WITH"], ["Cleverness", "WIT"]] },
  { start: "FAILED", steps: [["Put away in a folder", "FILED"], ["Ran away", "FLED"], ["Guided", "LED"]] },
  { start: "ASHORE", steps: [["Where the sea meets the land", "SHORE"], ["Worn on a foot", "SHOE"], ["Not him", "SHE"]] },
  { start: "BOUNCE", steps: [["A small unit of weight", "OUNCE"], ["A single time", "ONCE"], ["A single thing", "ONE"]] },
  { start: "MAINLY", steps: [["Brave and strong", "MANLY"], ["A lot of", "MANY"], ["A grown-up boy", "MAN"]] },
  { start: "CLEVER", steps: [["A bar for lifting", "LEVER"], ["At any time", "EVER"], ["The night before", "EVE"]] },
  { start: "STORED", steps: [["A shop", "STORE"], ["Ripped", "TORE"], ["One of ten on your feet", "TOE"]] },
  { start: "STAGED", steps: [["A platform for actors", "STAGE"], ["A wise person, or a herb", "SAGE"], ["How old you are", "AGE"]] },
  { start: "PARTLY", steps: [["A celebration", "PARTY"], ["A piece", "PART"], ["Average for the hole, in golf", "PAR"]] },
  { start: "HEATED", steps: [["Disliked strongly", "HATED"], ["To dislike strongly", "HATE"], ["Worn on the head", "HAT"]] },
  { start: "TAPPED", steps: [["Stuck down with sticky strips", "TAPED"], ["A sticky strip", "TAPE"], ["Turn it on for water", "TAP"]] },
  { start: "STONED", steps: [["A rock", "STONE"], ["A musical note, or a mood", "TONE"], ["A thousand kilograms", "TON"]] },
  { start: "SHARED", steps: [["To divide with others", "SHARE"], ["Like a rabbit, but bigger", "HARE"], ["To exist, as in \"we ___\"", "ARE"]] },
  { retired: true, start: "BRIDES", steps: [["A woman on her wedding day", "BRIDE"], ["A trip on a horse or bike", "RIDE"], ["To get free of", "RID"]] },
  { start: "CHOSEN", steps: [["Picked", "CHOSE"], ["You water the garden with it", "HOSE"], ["A garden tool for weeds", "HOE"]] },
  { retired: true, start: "SPIKES", steps: [["A sharp point", "SPIKE"], ["A long freshwater fish", "PIKE"], ["Baked with a crust", "PIE"]] },
  { retired: true, start: "POINTS", steps: [["The sharp end", "POINT"], ["A measure of beer or milk", "PINT"], ["A hole in the ground, or a fruit stone", "PIT"]] },
  { retired: true, start: "SPILLS", steps: [["To let liquid run out", "SPILL"], ["A tablet of medicine", "PILL"], ["Unwell", "ILL"]] },
  { retired: true, start: "GRACES", steps: [["Elegance, or a prayer before a meal", "GRACE"], ["A running contest", "RACE"], ["The best card", "ACE"]] },
  { retired: true, start: "BOOTHS", steps: [["A small enclosed stall", "BOOTH"], ["Footwear for rain", "BOOT"], ["What a ghost says", "BOO"]] },
  { retired: true, start: "PRICES", steps: [["What something costs", "PRICE"], ["Grains eaten with curry", "RICE"], ["Frozen water", "ICE"]] },
  { retired: true, start: "DRINKS", steps: [["To swallow a liquid", "DRINK"], ["Where you skate", "RINK"], ["It fills a pen", "INK"]] },
  { start: "GAMBLE", steps: [["The triangle of wall under a pointed roof", "GABLE"], ["Capable", "ABLE"], ["A kind of beer", "ALE"]] },
  // ---- Chains with no plural-S step, added 10 October 2026. Retired chains above stay for the days already played. ----
  { start: "NEARLY", steps: [["Before the usual time", "EARLY"], ["A nobleman", "EARL"], ["You hear with it", "EAR"]] },
  { start: "DRIVEN", steps: [["To steer a car", "DRIVE"], ["To plunge head first into water", "DIVE"], ["To stop living", "DIE"]] },
  { start: "BREAST", steps: [["A wild animal", "BEAST"], ["Where the sun rises", "EAST"], ["What you do with food", "EAT"]] },
  { start: "STREAM", steps: [["Hot water vapour", "STEAM"], ["A group of players", "TEAM"], ["A hot drink", "TEA"]] },
  { start: "PALACE", steps: [["A spot or location", "PLACE"], ["Speed", "PACE"], ["The best card", "ACE"]] },
  { start: "LEARNT", steps: [["To gain knowledge", "LEARN"], ["To be paid for work", "EARN"], ["You hear with it", "EAR"]] },
  { start: "BORING", steps: [["To carry along", "BRING"], ["Worn on a finger", "RING"], ["To set up or fix a result", "RIG"]] },
  { start: "FRIDGE", steps: [["The top of a mountain range", "RIDGE"], ["A trip on a horse or bike", "RIDE"], ["To get free of", "RID"]] },
  { start: "AGREED", steps: [["Wanting far more than your share", "GREED"], ["A tall grass by the water", "REED"], ["The colour of a stop sign", "RED"]] },
  { start: "SWEATY", steps: [["What you do in a hot gym", "SWEAT"], ["A place to sit", "SEAT"], ["What you do with food", "EAT"]] },
  { start: "CARVED", steps: [["Looked after", "CARED"], ["You might post one or play one", "CARD"], ["It has four wheels and an engine", "CAR"]] },
  { start: "SHRINE", steps: [["To give off light", "SHINE"], ["The front of your lower leg", "SHIN"], ["A wrongdoing", "SIN"]] },
  { start: "SEWING", steps: [["A seat that hangs from ropes", "SWING"], ["A bird flies with it", "WING"], ["False hair", "WIG"]] },
  { start: "DINNER", steps: [["A small roadside restaurant", "DINER"], ["To eat a meal", "DINE"], ["To stop living", "DIE"]] },
  { start: "CHILLY", steps: [["A slight cold", "CHILL"], ["Higher than the land around it", "HILL"], ["Unwell", "ILL"]] },
  { start: "SUITED", steps: [["A set of hotel rooms", "SUITE"], ["A place where something is built", "SITE"], ["Take a seat", "SIT"]] },
  { start: "STINKY", steps: [["To smell terrible", "STINK"], ["Where you wash the dishes", "SINK"], ["It fills a pen", "INK"]] },
  { start: "CREATE", steps: [["A wooden box for shipping", "CRATE"], ["Speed, or a price per unit", "RATE"], ["Consumed", "ATE"]] },
  { start: "TABLET", steps: [["You eat your dinner at it", "TABLE"], ["Capable", "ABLE"], ["A kind of beer", "ALE"]] },
  { start: "ABOARD", steps: [["A flat piece of wood", "BOARD"], ["A wild pig", "BOAR"], ["A rod, or a counter for drinks", "BAR"]] },
  { start: "STARVE", steps: [["To look hard and long", "STARE"], ["It twinkles at night", "STAR"], ["Black sticky stuff on roads", "TAR"]] },
  { start: "CRANKY", steps: [["A handle you turn", "CRANK"], ["A position in an army", "RANK"], ["Moved fast on foot", "RAN"]] },
  { start: "TIMBER", steps: [["A kitchen clock that counts down", "TIMER"], ["What a clock measures", "TIME"], ["To fasten with a knot", "TIE"]] },
  { start: "SLICED", steps: [["A piece of bread or cake", "SLICE"], ["Tiny biting insects in hair", "LICE"], ["Frozen water", "ICE"]] },
  { start: "SCARCE", steps: [["To frighten", "SCARE"], ["To look after", "CARE"], ["To exist, as in \"we ___\"", "ARE"]] },
  { start: "THRUST", steps: [["To rely on someone", "TRUST"], ["Red flakes on old iron", "RUST"], ["A groove worn by wheels", "RUT"]] },
  { start: "ASTRAY", steps: [["To wander off the path", "STRAY"], ["You carry drinks on it", "TRAY"], ["A beam of light", "RAY"]] },
  { start: "SPOILT", steps: [["To ruin", "SPOIL"], ["Earth for plants", "SOIL"], ["It makes an engine run smoothly", "OIL"]] },
  { start: "CASTLE", steps: [["A class in a strict social order", "CASTE"], ["The actors in a play", "CAST"], ["It purrs", "CAT"]] },
  { start: "AMUSED", steps: [["To make someone laugh", "AMUSE"], ["A source of inspiration", "MUSE"], ["To put to work", "USE"]] },
  { start: "THRASH", steps: [["Rubbish", "TRASH"], ["Red spots on the skin", "RASH"], ["What is left after a fire", "ASH"]] },
  { start: "SCORED", steps: [["The points in a game", "SCORE"], ["The centre of an apple", "CORE"], ["Rock with metal in it", "ORE"]] },
  { start: "FINGER", steps: [["Thinner, or of better quality", "FINER"], ["Very good", "FINE"], ["A fish swims with it", "FIN"]] },
  { start: "LONGER", steps: [["Someone who keeps to themselves", "LONER"], ["Single, with no others near", "LONE"], ["A single thing", "ONE"]] },
  { start: "STRAND", steps: [["To be on your feet", "STAND"], ["On a beach", "SAND"], ["Plus", "AND"]] },
  { start: "LATTER", steps: [["Afterwards", "LATER"], ["Not early", "LATE"], ["Consumed", "ATE"]] },
  { start: "SPARKY", steps: [["A tiny flash from a fire", "SPARK"], ["Where you leave the car", "PARK"], ["Noah's boat", "ARK"]] },
  { start: "CRAFTY", steps: [["A skill, or a vessel", "CRAFT"], ["Logs tied together to float", "RAFT"], ["Towards the back of a ship", "AFT"]] },
  { start: "HOPPED", steps: [["Wished", "HOPED"], ["A wish for something good", "HOPE"], ["To jump on one foot", "HOP"]] },
  { start: "POINTY", steps: [["The sharp end", "POINT"], ["A measure of beer or milk", "PINT"], ["A hole in the ground, or a fruit stone", "PIT"]] },
  { start: "AFLOAT", steps: [["To rest on top of water", "FLOAT"], ["Level, with no bumps", "FLAT"], ["Not thin", "FAT"]] },
  { start: "SPIKED", steps: [["A sharp point", "SPIKE"], ["A long freshwater fish", "PIKE"], ["Baked with a crust", "PIE"]] },
  { start: "SHREWD", steps: [["To cut into thin strips", "SHRED"], ["A garden hut", "SHED"], ["Not him", "SHE"]] },
  { start: "CUTTER", steps: [["More adorable", "CUTER"], ["Sweet and pretty", "CUTE"], ["A hint, or a prompt", "CUE"]] },
  { start: "TRENDY", steps: [["The general direction of change", "TREND"], ["To look after", "TEND"], ["The finish", "END"]] },
  { start: "CREAMY", steps: [["The top of the milk", "CREAM"], ["To stuff in tightly", "CRAM"], ["A male sheep", "RAM"]] },
  { start: "LINGER", steps: [["A large passenger ship", "LINER"], ["A row of people waiting", "LINE"], ["To tell an untruth", "LIE"]] },
  { start: "SHAMED", steps: [["A feeling of disgrace", "SHAME"], ["A fake", "SHAM"], ["Meat from a pig's leg", "HAM"]] },
  { start: "SINGLE", steps: [["To burn lightly at the edges", "SINGE"], ["To make music with your voice", "SING"], ["A wrongdoing", "SIN"]] },
  { start: "BITTER", steps: [["One who bites", "BITER"], ["To sink your teeth in", "BITE"], ["A small amount", "BIT"]] },
  { start: "COUPLE", steps: [["A sporty two-door car", "COUPE"], ["To manage in a hard situation", "COPE"], ["A police officer, informally", "COP"]] },
  // ---- 75 more chains, added 10 October 2026: no start ends in S, no step drops a plural S ----
  { start: "DRIVER", steps: [["To steer a car", "DRIVE"], ["To plunge head first into water", "DIVE"], ["A cube with spots, for board games", "DIE"]] },
  { start: "VALLEY", steps: [["A narrow lane behind houses", "ALLEY"], ["A friend in a war", "ALLY"], ["Every one", "ALL"]] },
  { start: "HATRED", steps: [["Disliked strongly", "HATED"], ["To dislike strongly", "HATE"], ["Had a meal", "ATE"]] },
  { start: "PLACED", steps: [["A spot or location", "PLACE"], ["Speed", "PACE"], ["The best card", "ACE"]] },
  { start: "RANGER", steps: [["A mountain chain, or a cooker", "RANGE"], ["Fury", "RAGE"], ["How old you are", "AGE"]] },
  { start: "FILLED", steps: [["Put away in a folder", "FILED"], ["Ran away", "FLED"], ["Guided", "LED"]] },
  { start: "LINKED", steps: [["Was fond of", "LIKED"], ["Told an untruth", "LIED"], ["Showed the way", "LED"]] },
  { start: "GREEDY", steps: [["Wanting far more than your share", "GREED"], ["A tall grass by the water", "REED"], ["The colour of a ripe tomato", "RED"]] },
  { start: "TRACED", steps: [["To copy a drawing through thin paper", "TRACE"], ["A running contest", "RACE"], ["A tennis serve nobody can return", "ACE"]] },
  { start: "DEARLY", steps: [["Before the usual time", "EARLY"], ["A British nobleman", "EARL"], ["You hear with it", "EAR"]] },
  { start: "SHOVED", steps: [["To push roughly", "SHOVE"], ["Worn on a foot", "SHOE"], ["Not him", "SHE"]] },
  { start: "TRANCE", steps: [["A tiny amount, or a faint mark", "TRACE"], ["A running contest", "RACE"], ["An expert", "ACE"]] },
  { start: "CARVER", steps: [["To cut wood into a shape", "CARVE"], ["To look after", "CARE"], ["To exist, as in \"we ___\"", "ARE"]] },
  { start: "CRATER", steps: [["A wooden box for shipping", "CRATE"], ["Speed, or a price per unit", "RATE"], ["Had a meal", "ATE"]] },
  { start: "SPEEDY", steps: [["How fast something goes", "SPEED"], ["A plant starts as one", "SEED"], ["To look with your eyes", "SEE"]] },
  { start: "LICKED", steps: [["Was fond of", "LIKED"], ["Lay down, or told a fib", "LIED"], ["Guided", "LED"]] },
  { start: "DRYING", steps: [["Very close to the end", "DYING"], ["A small dent in a car door", "DING"], ["To use a shovel", "DIG"]] },
  { start: "DIVERT", steps: [["Someone who swims under the sea in a mask", "DIVER"], ["To plunge head first into water", "DIVE"], ["To stop living", "DIE"]] },
  { start: "STINGY", steps: [["What a bee does", "STING"], ["To make music with your voice", "SING"], ["A wrongdoing", "SIN"]] },
  { start: "STRUNG", steps: [["Hurt by a wasp", "STUNG"], ["Performed, as a song", "SUNG"], ["It rises in the east", "SUN"]] },
  { start: "HEARTY", steps: [["It pumps blood", "HEART"], ["A male deer", "HART"], ["Paintings and sculpture", "ART"]] },
  { start: "BATHED", steps: [["To wash yourself in a tub", "BATHE"], ["A tub you wash in", "BATH"], ["It flies at night, or hits a baseball", "BAT"]] },
  { start: "PALATE", steps: [["You eat dinner off it", "PLATE"], ["Not on time", "LATE"], ["Had a meal", "ATE"]] },
  { start: "OWNING", steps: [["In debt", "OWING"], ["A bird flies with it", "WING"], ["To come first", "WIN"]] },
  { start: "MOUSSE", steps: [["A tiny squeaker", "MOUSE"], ["A source of inspiration", "MUSE"], ["To put to work", "USE"]] },
  { start: "LINEAR", steps: [["A large passenger ship", "LINER"], ["A row of people waiting", "LINE"], ["To tell an untruth", "LIE"]] },
  { start: "DARNED", steps: [["Challenged someone to try", "DARED"], ["A challenge to do something risky", "DARE"], ["To exist, as in \"they ___\"", "ARE"]] },
  { start: "LACKED", steps: [["Tied, as shoes", "LACED"], ["Delicate fabric with holes", "LACE"], ["The best card", "ACE"]] },
  { start: "CHASTE", steps: [["Hurry", "HASTE"], ["To dislike strongly", "HATE"], ["Had a meal", "ATE"]] },
  { start: "SPROUT", steps: [["Where the tea comes out of the pot", "SPOUT"], ["A small round mark", "SPOT"], ["You cook in it", "POT"]] },
  { start: "POUNCE", steps: [["A small unit of weight", "OUNCE"], ["A single time", "ONCE"], ["A single thing", "ONE"]] },
  { start: "TRASHY", steps: [["Rubbish", "TRASH"], ["Red spots on the skin", "RASH"], ["A tree, or what is left after a fire", "ASH"]] },
  { start: "PRICEY", steps: [["What something costs", "PRICE"], ["Grains eaten with curry", "RICE"], ["Frozen water", "ICE"]] },
  { start: "CAMPER", steps: [["A playful leap, or a daring robbery", "CAPER"], ["A cloak, or a headland", "CAPE"], ["A hat with a peak", "CAP"]] },
  { start: "BARGED", steps: [["A flat boat for carrying goods", "BARGE"], ["Uncovered", "BARE"], ["To exist, as in \"you ___\"", "ARE"]] },
  { start: "SPACED", steps: [["Where the stars and planets are", "SPACE"], ["Speed", "PACE"], ["The best card", "ACE"]] },
  { start: "HASTEN", steps: [["Hurry", "HASTE"], ["To dislike strongly", "HATE"], ["Had a meal", "ATE"]] },
  { start: "BOWLED", steps: [["Bent at the waist", "BOWED"], ["Was in debt", "OWED"], ["To be in debt", "OWE"]] },
  { start: "ASCENT", steps: [["A smell", "SCENT"], ["Posted", "SENT"], ["A group of things that go together", "SET"]] },
  { start: "CLONED", steps: [["An exact copy", "CLONE"], ["Single, with no others near", "LONE"], ["A single thing", "ONE"]] },
  { start: "RAIDED", steps: [["Helped", "AIDED"], ["An assistant", "AIDE"], ["Help", "AID"]] },
  { start: "SPORTY", steps: [["Football or tennis", "SPORT"], ["Where ships dock", "PORT"], ["You cook in it", "POT"]] },
  { start: "DOWNED", steps: [["Possessed", "OWNED"], ["Was in debt", "OWED"], ["To be in debt", "OWE"]] },
  { start: "TITLED", steps: [["The name of a book", "TITLE"], ["A flat square on a floor or roof", "TILE"], ["To fasten with a knot", "TIE"]] },
  { start: "BRAINY", steps: [["Wet, with showers", "RAINY"], ["It falls from clouds", "RAIN"], ["Moved fast on foot", "RAN"]] },
  { start: "HEATER", steps: [["Someone who dislikes everything", "HATER"], ["To dislike strongly", "HATE"], ["Had a meal", "ATE"]] },
  { start: "RAIDER", steps: [["Someone on a horse or a bike", "RIDER"], ["A trip on a horse or bike", "RIDE"], ["To get free of", "RID"]] },
  { start: "SHINED", steps: [["To give off light", "SHINE"], ["The front of your lower leg", "SHIN"], ["A wrongdoing", "SIN"]] },
  { start: "BREWED", steps: [["To raise animals, or a type of dog", "BREED"], ["A tall grass by the water", "REED"], ["The colour of a stop sign", "RED"]] },
  { start: "RAGGED", steps: [["Was furious", "RAGED"], ["Grown old", "AGED"], ["How old you are", "AGE"]] },
  { start: "SLUICE", steps: [["A piece of bread or cake", "SLICE"], ["Tiny biting insects in hair", "LICE"], ["Frozen water", "ICE"]] },
  { start: "STEWED", steps: [["Stitched", "SEWED"], ["Planted, or ranked in a tournament", "SEED"], ["To look with your eyes", "SEE"]] },
  { start: "PRESTO", steps: [["A green basil sauce", "PESTO"], ["A bug that eats your plants", "PEST"], ["A cat or a dog", "PET"]] },
  { start: "CLOTHE", steps: [["Fabric", "CLOTH"], ["A lump of thick blood", "CLOT"], ["A great deal", "LOT"]] },
  { start: "STOWED", steps: [["Pulled by a tow truck", "TOWED"], ["Was in debt", "OWED"], ["To be in debt", "OWE"]] },
  { start: "SPRITE", steps: [["Wanting to hurt someone", "SPITE"], ["A place where something is built", "SITE"], ["Take a seat", "SIT"]] },
  { start: "SLIVER", steps: [["An organ that cleans the blood", "LIVER"], ["To be alive", "LIVE"], ["To tell an untruth", "LIE"]] },
  { start: "BONDED", steps: [["With the bones taken out, as fish", "BONED"], ["Part of a skeleton", "BONE"], ["A single thing", "ONE"]] },
  { start: "THORNY", steps: [["A prickle on a rose", "THORN"], ["Ripped", "TORN"], ["A thousand kilograms", "TON"]] },
  { start: "PLACID", steps: [["A tartan pattern", "PLAID"], ["Put down, as an egg", "LAID"], ["Help", "AID"]] },
  { start: "TEENSY", steps: [["Very small", "TEENY"], ["Someone aged 13 to 19", "TEEN"], ["The number after nine", "TEN"]] },
  { start: "SCAMPI", steps: [["A mischievous child", "SCAMP"], ["Tents in a field", "CAMP"], ["A hat with a peak", "CAP"]] },
  { start: "LATHER", steps: [["Afterwards", "LATER"], ["Not on time", "LATE"], ["Had a meal", "ATE"]] },
  { start: "MINCED", steps: [["Finely chopped meat", "MINCE"], ["More than one mouse", "MICE"], ["Frozen water", "ICE"]] },
  { start: "BRIDLE", steps: [["A woman on her wedding day", "BRIDE"], ["A trip on a horse or bike", "RIDE"], ["To get free of", "RID"]] },
  { start: "GRILLE", steps: [["To cook under a flame", "GRILL"], ["A fish breathes with it", "GILL"], ["Unwell", "ILL"]] },
  { start: "LANCER", steps: [["A knight's long spear", "LANCE"], ["Delicate fabric with holes", "LACE"], ["The best card", "ACE"]] },
  { start: "BELLOW", steps: [["Underneath", "BELOW"], ["What the wind does", "BLOW"], ["Not high", "LOW"]] },
  { start: "DRAFTY", steps: [["A first version of a piece of writing", "DRAFT"], ["Logs tied together to float", "RAFT"], ["A rodent with a long tail", "RAT"]] },
  { start: "SLINKY", steps: [["To move away quietly and guiltily", "SLINK"], ["Where you wash the dishes", "SINK"], ["A wrongdoing", "SIN"]] },
  { start: "FLARED", steps: [["A bright signal light", "FLARE"], ["The price of a bus ticket", "FARE"], ["To exist, as in \"we ___\"", "ARE"]] },
  { start: "FLUNKY", steps: [["Groovy, with a strong beat", "FUNKY"], ["A style of music with a strong beat", "FUNK"], ["A good time", "FUN"]] },
  { start: "VOICED", steps: [["What you speak with", "VOICE"], ["A bad habit", "VICE"], ["Frozen water", "ICE"]] },
  { start: "GOODLY", steps: [["A sweet treat, or a well-behaved person", "GOODY"], ["Not bad", "GOOD"], ["A deity", "GOD"]] },
  { start: "TWINGE", steps: [["Strong string for tying parcels", "TWINE"], ["A drink made from grapes", "WINE"], ["To come first", "WIN"]] }
];
