// Whittle puzzles.
//
// Each puzzle has:
//   start - a six-letter word, in capitals
//   steps - three [clue, answer] pairs. Each answer is the word before it with one letter
//           removed and the other letters kept in the same order (PLANET, PLANT, PLAN, PAN).
//
// Every game picks four of these at random. All puzzles must be original.

window.WHITTLE_PUZZLES = [
  { start: "PLANET", steps: [["Something that grows in soil", "PLANT"], ["A scheme", "PLAN"], ["You fry an egg in it", "PAN"]] },
  { start: "STRAIN", steps: [["It runs on rails", "TRAIN"], ["It falls from clouds", "RAIN"], ["Moved fast on foot", "RAN"]] },
  { start: "BRANDY", steps: [["A company's name and logo", "BRAND"], ["The husk of a grain", "BRAN"], ["To forbid", "BAN"]] },
  { start: "SPRINT", steps: [["To put ink on paper", "PRINT"], ["A measure of beer", "PINT"], ["It holds fabric in place", "PIN"]] },
  { start: "CHEATS", steps: [["To break the rules", "CHEAT"], ["Warmth", "HEAT"], ["Worn on the head", "HAT"]] },
  { start: "PAINTS", steps: [["To coat a wall with colour", "PAINT"], ["To breathe hard", "PANT"], ["A small insect", "ANT"]] },
  { start: "STABLE", steps: [["You eat dinner at it", "TABLE"], ["A story", "TALE"], ["A kind of beer", "ALE"]] },
  { start: "SCARED", steps: [["To frighten", "SCARE"], ["To look after", "CARE"], ["You drive it", "CAR"]] },
  { start: "BOARDS", steps: [["A flat length of wood", "BOARD"], ["A wild pig", "BOAR"], ["It rows a boat", "OAR"]] },
  { start: "PLEASE", steps: [["Appeals or requests", "PLEAS"], ["What a defendant enters in court", "PLEA"], ["A small green vegetable", "PEA"]] },
  { start: "FRIEND", steps: [["A demon or villain", "FIEND"], ["To locate", "FIND"], ["A fish steers with it", "FIN"]] },
  { start: "CHARTS", steps: [["A map for sailors", "CHART"], ["A friendly talk", "CHAT"], ["A pet that purrs", "CAT"]] },
  { start: "SWINGS", steps: [["It hangs in a playground", "SWING"], ["A bird flaps it", "WING"], ["To come first", "WIN"]] },
  { start: "THINKS", steps: [["To use your mind", "THINK"], ["Not thick", "THIN"], ["A metal used for cans", "TIN"]] },
  { start: "STRIPE", steps: [["To peel away", "STRIP"], ["A journey", "TRIP"], ["A waiter hopes for one", "TIP"]] },
  { start: "CRATES", steps: [["A wooden shipping box", "CRATE"], ["A speed or a price", "RATE"], ["A rodent", "RAT"]] },
  { start: "GRAINS", steps: [["One seed of wheat", "GRAIN"], ["To get more of something", "GAIN"], ["A spirit mixed with tonic", "GIN"]] },
  { start: "SPARKS", steps: [["A tiny flash from a fire", "SPARK"], ["A green space in town", "PARK"], ["Noah built one", "ARK"]] },
  { start: "CLEANS", steps: [["Not dirty", "CLEAN"], ["A family group, in Scotland", "CLAN"], ["Beans come in one", "CAN"]] },
  { start: "FLOATS", steps: [["To stay on the surface", "FLOAT"], ["Level, with no bumps", "FLAT"], ["Not thin", "FAT"]] },
  { start: "SHEARS", steps: [["To clip a sheep's wool", "SHEAR"], ["To use your ears", "HEAR"], ["It is on the side of your head", "EAR"]] },
  { start: "BRINGS", steps: [["To carry something here", "BRING"], ["Worn on a finger", "RING"], ["A drilling platform at sea", "RIG"]] },
  { start: "SLEEPS", steps: [["What you do at night", "SLEEP"], ["To leak slowly through", "SEEP"], ["To use your eyes", "SEE"]] },
  { start: "STEAMS", steps: [["It rises from a kettle", "STEAM"], ["Where two pieces of cloth are stitched", "SEAM"], ["Ships sail on it", "SEA"]] },
  { start: "BRIDGE", steps: [["She walks down the aisle", "BRIDE"], ["A trip on a bike or a horse", "RIDE"], ["To be free of something", "RID"]] },
  { start: "TRAILS", steps: [["A path through the woods", "TRAIL"], ["A dog wags it", "TAIL"], ["To be unwell", "AIL"]] },
  { start: "SPLINT", steps: [["To divide in two", "SPLIT"], ["A narrow cut", "SLIT"], ["To take a seat", "SIT"]] },
  { start: "PLATES", steps: [["You eat from it", "PLATE"], ["After the agreed time", "LATE"], ["Had a meal, in the past", "ATE"]] },
  { start: "GRAPES", steps: [["Wine is made from it", "GRAPE"], ["To stare open-mouthed", "GAPE"], ["A big monkey-like animal", "APE"]] },
  { start: "CLAMPS", steps: [["It holds wood while glue dries", "CLAMP"], ["To applaud", "CLAP"], ["A hat with a peak", "CAP"]] },
  { start: "WHEELS", steps: [["It turns on an axle", "WHEEL"], ["The back of your foot", "HEEL"], ["A snake-like fish", "EEL"]] },
  { start: "SPINES", steps: [["Your backbone", "SPINE"], ["An evergreen tree", "PINE"], ["Baked with a crust", "PIE"]] },
  { start: "BEARDS", steps: [["Hair on the chin", "BEARD"], ["It threads onto a necklace", "BEAD"], ["You sleep in it", "BED"]] },
  { start: "BLINKS", steps: [["Eyes do it in a flash", "BLINK"], ["One ring of a chain", "LINK"], ["Pens are filled with it", "INK"]] },
  { start: "CRAFTS", steps: [["A skilled trade done by hand", "CRAFT"], ["A floating platform of logs", "RAFT"], ["Towards the back of a boat", "AFT"]] },
  { start: "SHOUTS", steps: [["To yell", "SHOUT"], ["Fired from a gun", "SHOT"], ["Not cold", "HOT"]] },
  { start: "CHARMS", steps: [["A lucky trinket", "CHARM"], ["Damage or injury", "HARM"], ["Meat from a pig", "HAM"]] },
  { start: "TRAMPS", steps: [["A wanderer with no home", "TRAMP"], ["It catches animals", "TRAP"], ["Water comes out of it", "TAP"]] },
  { start: "CLOTHS", steps: [["Fabric", "CLOTH"], ["A lump of thickened blood", "CLOT"], ["A baby's bed", "COT"]] },
  { start: "SWEATS", steps: [["It beads on your skin when hot", "SWEAT"], ["You sit on it", "SEAT"], ["To have a meal", "EAT"]] },
  { start: "PRINCE", steps: [["What something costs", "PRICE"], ["A grain eaten with curry", "RICE"], ["Frozen water", "ICE"]] },
  { start: "CHAIRS", steps: [["You sit on it", "CHAIR"], ["It grows on your head", "HAIR"], ["You breathe it", "AIR"]] },
  { start: "BEASTS", steps: [["A wild animal", "BEAST"], ["To defeat", "BEAT"], ["It hangs upside down in caves", "BAT"]] },
  { start: "TRENDS", steps: [["A fashion", "TREND"], ["To look after", "TEND"], ["Twice five", "TEN"]] },
  { start: "SPARES", steps: [["An extra kept in reserve", "SPARE"], ["To practise boxing lightly", "SPAR"], ["A place to soak and relax", "SPA"]] },
  { start: "THREAD", steps: [["The grip on a tyre", "TREAD"], ["To take in words on a page", "READ"], ["The colour of a stop sign", "RED"]] },
  { start: "SPOUTS", steps: [["A kettle pours from it", "SPOUT"], ["To push out your lips sulkily", "POUT"], ["Not in", "OUT"]] },
  { start: "FLINTS", steps: [["A stone that makes sparks", "FLINT"], ["Fluff from the dryer", "LINT"], ["Set alight", "LIT"]] },
  { start: "BLOATS", steps: [["To swell up", "BLOAT"], ["It floats", "BOAT"], ["A grain for porridge", "OAT"]] },
  { start: "PEARLS", steps: [["A gem from an oyster", "PEARL"], ["The ringing of bells", "PEAL"], ["A friend", "PAL"]] },
  { start: "BRACES", steps: [["A support that holds something steady", "BRACE"], ["A running contest", "RACE"], ["The top card in the pack", "ACE"]] },
  { start: "SPRAYS", steps: [["A fine mist of liquid", "SPRAY"], ["To speak to a god", "PRAY"], ["To hand over money", "PAY"]] },
  { start: "STRING", steps: [["A bee does it", "STING"], ["To make music with your voice", "SING"], ["A wrongdoing", "SIN"]] },
  { start: "SCOLDS", steps: [["To tell off", "SCOLD"], ["Not warm", "COLD"], ["Not new", "OLD"]] },
  { start: "DRIVES", steps: [["To steer a car", "DRIVE"], ["To plunge headfirst into water", "DIVE"], ["To stop living", "DIE"]] },
  { start: "GLOBES", steps: [["A model of the Earth", "GLOBE"], ["The soft bottom of your ear", "LOBE"], ["A high, gentle throw", "LOB"]] },
  { start: "CREAMS", steps: [["The rich top of milk", "CREAM"], ["Five hundred sheets of paper", "REAM"], ["A male sheep", "RAM"]] },
  { start: "CHILLS", steps: [["A cold feeling", "CHILL"], ["A small mountain", "HILL"], ["Unwell", "ILL"]] },
  { start: "SPOILS", steps: [["To ruin", "SPOIL"], ["Earth in a garden", "SOIL"], ["It greases an engine", "OIL"]] },
  { start: "STRAYS", steps: [["A lost pet", "STRAY"], ["To remain", "STAY"], ["To speak", "SAY"]] },
  { start: "PLUNGE", steps: [["A sudden forward thrust", "LUNGE"], ["You breathe with it", "LUNG"], ["To drag with effort", "LUG"]] },
  { start: "BLENDS", steps: [["To mix together", "BLEND"], ["A curve in the road", "BEND"], ["The finish", "END"]] },
  { start: "STEALS", steps: [["To take what is not yours", "STEAL"], ["A blue-green colour", "TEAL"], ["A hot drink", "TEA"]] },
  { start: "SKIRTS", steps: [["Worn from the waist down", "SKIRT"], ["A short comic sketch", "SKIT"], ["A set of equipment", "KIT"]] },
  { start: "SMARTS", steps: [["Clever", "SMART"], ["A market or store", "MART"], ["Paintings and sculpture", "ART"]] },
  { start: "STARTS", steps: [["To begin", "START"], ["It twinkles at night", "STAR"], ["Black sticky stuff on roads", "TAR"]] },
  { start: "PASTES", steps: [["A thick sticky mixture", "PASTE"], ["The time gone by", "PAST"], ["A gentle tap", "PAT"]] },
  { start: "CHORDS", steps: [["Notes played together", "CHORD"], ["A length of string", "CORD"], ["A fish for frying", "COD"]] },
  { start: "SLANTS", steps: [["A slope", "SLANT"], ["A thin strip of wood", "SLAT"], ["Took a seat", "SAT"]] },
  { start: "GRUNTS", steps: [["A pig's sound", "GRUNT"], ["The smallest of a litter", "RUNT"], ["To move fast on foot", "RUN"]] },
  { start: "GROWLS", steps: [["A dog's warning sound", "GROWL"], ["To get bigger", "GROW"], ["A line of seats", "ROW"]] },
  { start: "CROWNS", steps: [["A king wears it", "CROWN"], ["A black bird that caws", "CROW"], ["It gives milk", "COW"]] },
  { start: "STOOLS", steps: [["A seat with no back", "STOOL"], ["A hammer is one", "TOOL"], ["Also", "TOO"]] },
  { start: "SLICES", steps: [["A piece of cake", "SLICE"], ["Tiny biting insects", "LICE"], ["An untruth", "LIE"]] },
  { start: "CRUSTS", steps: [["The hard edge of a pizza", "CRUST"], ["Orange flakes on old iron", "RUST"], ["A groove worn into a track", "RUT"]] },
  { start: "SPORTS", steps: [["Football is one", "SPORT"], ["A small round mark", "SPOT"], ["You cook soup in it", "POT"]] },
  { start: "BRAIDS", steps: [["A plait of hair", "BRAID"], ["A sudden attack", "RAID"], ["Help", "AID"]] },
  { start: "TRIPLE", steps: [["Nonsense", "TRIPE"], ["Ready to eat", "RIPE"], ["To tear", "RIP"]] },
  { start: "SCORES", steps: [["The points in a game", "SCORE"], ["The middle of an apple", "CORE"], ["Rock that contains metal", "ORE"]] },
  { start: "BLOOMS", steps: [["A flower opening", "BLOOM"], ["A loud bang", "BOOM"], ["What a ghost says", "BOO"]] },
  // ---- Added 9 October 2026 ----
  { start: "SPRING", steps: [["A small twig", "SPRIG"], ["A self-righteous, fussy person", "PRIG"], ["It oinks", "PIG"]] },
  { start: "CHANTS", steps: [["Friendly talks", "CHATS"], ["They purr", "CATS"], ["Just one of them", "CAT"]] },
  { start: "WRITES", steps: [["Court orders", "WRITS"], ["Quickness of mind", "WITS"], ["Belonging to it", "ITS"]] },
  { start: "BROOMS", steps: [["Sudden rises in business", "BOOMS"], ["A loud bang", "BOOM"], ["What a ghost says", "BOO"]] },
  { start: "SPEARS", steps: [["A pointed weapon", "SPEAR"], ["A friendly boxing practice", "SPAR"], ["A place for a massage", "SPA"]] },
  { start: "PRINTS", steps: [["Put ink on paper", "PRINT"], ["A measure of beer or milk", "PINT"], ["A small sharp fastener", "PIN"]] },
  { start: "GRINDS", steps: [["To crush into powder", "GRIND"], ["A pattern of squares", "GRID"], ["To get free of", "RID"]] },
  { start: "THORNS", steps: [["A prickle on a rose", "THORN"], ["Ripped", "TORN"], ["A thousand kilograms", "TON"]] },
  { start: "SWEEPS", steps: [["To brush the floor", "SWEEP"], ["To leak slowly", "SEEP"], ["To look with your eyes", "SEE"]] },
  { start: "SLATES", steps: [["A grey roofing stone", "SLATE"], ["To satisfy fully", "SATE"], ["Took a seat", "SAT"]] },
  { start: "SPLASH", steps: [["A long cut", "SLASH"], ["It grows on an eyelid", "LASH"], ["What is left after a fire", "ASH"]] },
  { start: "PLIERS", steps: [["Works away at a trade", "PLIES"], ["Pastry with a filling, more than one", "PIES"], ["Just one of them", "PIE"]] },
  { start: "CRAMPS", steps: [["A painful muscle spasm", "CRAMP"], ["To stuff in tightly", "CRAM"], ["A male sheep", "RAM"]] },
  { start: "STOMPS", steps: [["To walk heavily", "STOMP"], ["Come to a halt", "STOP"], ["The highest point", "TOP"]] },
  { start: "SWAMPS", steps: [["A wet, marshy area", "SWAMP"], ["To exchange", "SWAP"], ["The juice inside a tree", "SAP"]] },
  { start: "CHAMPS", steps: [["The winner", "CHAMP"], ["A fellow, a bloke", "CHAP"], ["A hat with a peak", "CAP"]] },
  { start: "SLINGS", steps: [["It supports a broken arm", "SLING"], ["To make music with your voice", "SING"], ["A wrongdoing", "SIN"]] },
  { start: "CRANKS", steps: [["A handle you turn", "CRANK"], ["A position in an army", "RANK"], ["Moved fast on foot", "RAN"]] },
  { start: "BLINDS", steps: [["They cover a window", "BLIND"], ["To tie up", "BIND"], ["Where rubbish goes", "BIN"]] },
  { start: "GLANDS", steps: [["A body part that makes sweat or tears", "GLAND"], ["Dry ground", "LAND"], ["Plus", "AND"]] },
  { start: "FLEETS", steps: [["A group of ships", "FLEET"], ["At the ends of your legs", "FEET"], ["A payment for a service", "FEE"]] },
  { start: "SPENDS", steps: [["To pay out money", "SPEND"], ["To post a letter", "SEND"], ["The finish", "END"]] },
  { start: "STANDS", steps: [["To be on your feet", "STAND"], ["On a beach", "SAND"], ["Unhappy", "SAD"]] },
  { start: "STEAKS", steps: [["A slice of beef", "STEAK"], ["A hard wood used for furniture", "TEAK"], ["A hot drink", "TEA"]] },
  { start: "SHARKS", steps: [["It has fins and lots of teeth", "SHARK"], ["Listen!", "HARK"], ["Noah's boat", "ARK"]] },
  { start: "CHORES", steps: [["A household task", "CHORE"], ["The centre of an apple", "CORE"], ["Rock with metal in it", "ORE"]] },
  { start: "PLEATS", steps: [["A fold in a skirt", "PLEAT"], ["Soil fuel cut from a bog", "PEAT"], ["A cat or a dog", "PET"]] },
  { start: "BLEATS", steps: [["The cry of a sheep", "BLEAT"], ["Rhythm", "BEAT"], ["A wager", "BET"]] },
  { start: "GLOATS", steps: [["To brag about winning", "GLOAT"], ["It has horns and a beard", "GOAT"], ["Received", "GOT"]] },
  { start: "STRAPS", steps: [["A band of leather", "STRAP"], ["It catches a mouse", "TRAP"], ["Turn it on for water", "TAP"]] },
  { start: "HEARTS", steps: [["It pumps blood", "HEART"], ["Warmth", "HEAT"], ["What you do with food", "EAT"]] },
  { start: "FEASTS", steps: [["A huge meal", "FEAST"], ["An impressive deed", "FEAT"], ["Not thin", "FAT"]] },
  { start: "SPLITS", steps: [["To divide in two", "SPLIT"], ["What a llama might do to you", "SPIT"], ["Take a seat", "SIT"]] },
  { start: "GRILLS", steps: [["To cook under a flame", "GRILL"], ["A fish breathes with it", "GILL"], ["Unwell", "ILL"]] },
  { start: "TRICKS", steps: [["A magician's act", "TRICK"], ["A clock's sound", "TICK"], ["A twitch", "TIC"]] },
  { start: "GHOSTS", steps: [["It haunts a house", "GHOST"], ["The one who throws a party", "HOST"], ["Not cold", "HOT"]] },
  { start: "BOOSTS", steps: [["A lift, a push upward", "BOOST"], ["Footwear for rain", "BOOT"], ["A robot, for short", "BOT"]] },
  { start: "BLEEDS", steps: [["Loses blood", "BLEED"], ["Lost blood", "BLED"], ["You sleep in it", "BED"]] },
  { start: "BREEDS", steps: [["Kinds of dog", "BREED"], ["Brought up", "BRED"], ["The colour of a stop sign", "RED"]] },
  { start: "THINGS", steps: [["An object", "THING"], ["Not fat", "THIN"], ["A metal can", "TIN"]] },
  { start: "WRINGS", steps: [["To twist water out of a cloth", "WRING"], ["Worn on a finger", "RING"], ["To set up or fix a result", "RIG"]] },
  { start: "GRASPS", steps: [["To grab hold", "GRASP"], ["A sharp breath", "GASP"], ["Petrol, in North America", "GAS"]] },
  { start: "CLASPS", steps: [["A fastening on a necklace", "CLASP"], ["Applause", "CLAP"], ["The top of your thighs when sitting", "LAP"]] },
  { start: "GLANCE", steps: [["A knight's long spear", "LANCE"], ["Delicate fabric with holes", "LACE"], ["The best card", "ACE"]] },
  { start: "POUNDS", steps: [["To hit hard again and again", "POUND"], ["A small lake", "POND"], ["Peas grow in it", "POD"]] },
  { start: "BLUNTS", steps: [["Not sharp", "BLUNT"], ["A soft tap in baseball", "BUNT"], ["However", "BUT"]] },
  { start: "FLIRTS", steps: [["To be playfully romantic", "FLIRT"], ["To move lightly and quickly", "FLIT"], ["In good shape", "FIT"]] },
  { start: "GLINTS", steps: [["A flash of light", "GLINT"], ["Fluff from the dryer", "LINT"], ["Switched on", "LIT"]] },
  { start: "HOARDS", steps: [["To store up in secret", "HOARD"], ["Not soft", "HARD"], ["Owned", "HAD"]] },
  { start: "BRAWLS", steps: [["A rough fight", "BRAWL"], ["To cry loudly", "BAWL"], ["A pointed tool for making holes", "AWL"]] },
  { start: "PRAWNS", steps: [["A shellfish like a shrimp", "PRAWN"], ["The weakest chess piece", "PAWN"], ["A cat's foot", "PAW"]] },
  { start: "BROWNS", steps: [["To cook until golden", "BROWN"], ["Above the eye", "BROW"], ["A bend at the waist", "BOW"]] },
  { start: "SHOVEL", steps: [["To push roughly", "SHOVE"], ["Worn on a foot", "SHOE"], ["Not him", "SHE"]] },
  { start: "TRUMPS", steps: [["Beats with a higher card", "TRUMP"], ["The rear end of an animal", "RUMP"], ["A pirate's drink", "RUM"]] },
  { start: "FAIRLY", steps: [["A tiny magical being", "FAIRY"], ["Just and honest", "FAIR"], ["Not near", "FAR"]] },
  { start: "FOURTH", steps: [["Onward, as in \"go ___\"", "FORTH"], ["A stronghold", "FORT"], ["In favour of", "FOR"]] },
  { start: "ORANGE", steps: [["A mountain chain, or a cooker", "RANGE"], ["Fury", "RAGE"], ["How old you are", "AGE"]] },
  { start: "HARDLY", steps: [["Tough, able to survive winter", "HARDY"], ["Not soft", "HARD"], ["Owned", "HAD"]] },
  { start: "REALLY", steps: [["A gathering of supporters", "RALLY"], ["A friend in a war", "ALLY"], ["Every one", "ALL"]] },
  { start: "CORPSE", steps: [["A military unit", "CORPS"], ["Police officers, informally", "COPS"], ["Just one of them", "COP"]] },
  { start: "COURSE", steps: [["A spell of bad luck", "CURSE"], ["To make well", "CURE"], ["A hint, or a prompt", "CUE"]] },
  { start: "ABROAD", steps: [["Wide", "BROAD"], ["Cars drive on it", "ROAD"], ["A thin bar", "ROD"]] },
  { start: "SWITCH", steps: [["She rides a broomstick", "WITCH"], ["Together, not without", "WITH"], ["Cleverness", "WIT"]] },
  { start: "FAILED", steps: [["Put away in a folder", "FILED"], ["Ran away", "FLED"], ["Guided", "LED"]] },
  { start: "ASHORE", steps: [["Where the sea meets the land", "SHORE"], ["Worn on a foot", "SHOE"], ["Not him", "SHE"]] },
  { start: "BOUNCE", steps: [["A small unit of weight", "OUNCE"], ["A single time", "ONCE"], ["A single thing", "ONE"]] },
  { start: "MAINLY", steps: [["Brave and strong", "MANLY"], ["A lot of", "MANY"], ["A grown-up boy", "MAN"]] },
  { start: "CLEVER", steps: [["A bar for lifting", "LEVER"], ["At any time", "EVER"], ["The night before", "EVE"]] },
  { start: "STORED", steps: [["A shop", "STORE"], ["Ripped", "TORE"], ["One of ten on your feet", "TOE"]] },
  { start: "STAGED", steps: [["A platform for actors", "STAGE"], ["A wise person, or a herb", "SAGE"], ["How old you are", "AGE"]] },
  { start: "PARTLY", steps: [["A celebration", "PARTY"], ["A piece", "PART"], ["Average for the hole, in golf", "PAR"]] },
  { start: "HEATED", steps: [["Disliked strongly", "HATED"], ["To dislike strongly", "HATE"], ["Worn on the head", "HAT"]] },
  { start: "TAPPED", steps: [["Stuck down with sticky strips", "TAPED"], ["A sticky strip", "TAPE"], ["Turn it on for water", "TAP"]] },
  { start: "STONED", steps: [["A rock", "STONE"], ["A musical note, or a mood", "TONE"], ["A thousand kilograms", "TON"]] },
  { start: "SHARED", steps: [["To divide with others", "SHARE"], ["Like a rabbit, but bigger", "HARE"], ["To exist, as in \"we ___\"", "ARE"]] }
];
