// Plus One puzzles.
//
// Each puzzle has:
//   clues   - two clues
//   answers - two words, in the same order. The second is the first with one letter added
//             anywhere: at the start, in the middle or at the end.
//
// Every game picks five of these at random. All puzzles must be original.

window.PLUS_ONE_PUZZLES = [
  { clues: ["A hot drink", "A group of players"], answers: ["TEA", "TEAM"] },
  { clues: ["A pet that purrs", "You push it around the store"], answers: ["CAT", "CART"] },
  { clues: ["It twinkles at night", "To begin"], answers: ["STAR", "START"] },
  { clues: ["Thick mist", "It croaks"], answers: ["FOG", "FROG"] },
  { clues: ["It threads onto a necklace", "Baked in a loaf"], answers: ["BEAD", "BREAD"] },
  { clues: ["Winter outerwear", "Where land meets sea"], answers: ["COAT", "COAST"] },
  { clues: ["It lights a desk", "It holds wood while glue dries"], answers: ["LAMP", "CLAMP"] },
  { clues: ["You hear with it", "To make money by working"], answers: ["EAR", "EARN"] },
  { clues: ["A long tired breath", "The sense of seeing"], answers: ["SIGH", "SIGHT"] },
  { clues: ["It floats", "To brag"], answers: ["BOAT", "BOAST"] },
  { clues: ["The one throwing the party", "It haunts a house"], answers: ["HOST", "GHOST"] },
  { clues: ["A big furry animal", "Hair on the chin"], answers: ["BEAR", "BEARD"] },
  { clues: ["Quick", "A big celebratory meal"], answers: ["FAST", "FEAST"] },
  { clues: ["Worn with a suit", "The sea's daily rise and fall"], answers: ["TIE", "TIDE"] },
  { clues: ["A hat with a peak", "Tents in the woods"], answers: ["CAP", "CAMP"] },
  { clues: ["It flutters around a lamp", "Thirty days or so"], answers: ["MOTH", "MONTH"] },
  { clues: ["A gentle tap", "A trail to walk along"], answers: ["PAT", "PATH"] },
  { clues: ["A night bird that hoots", "You eat cereal from it"], answers: ["OWL", "BOWL"] },
  { clues: ["Baked with a crust", "Water flows through it"], answers: ["PIE", "PIPE"] },
  { clues: ["Attached to your shoulder", "Where crops are grown"], answers: ["ARM", "FARM"] },
  { clues: ["Breakfast, lunch or dinner", "Won at the Olympics"], answers: ["MEAL", "MEDAL"] },
  { clues: ["It hangs upside down in caves", "A long soak in the tub"], answers: ["BAT", "BATH"] },
  { clues: ["It falls from clouds", "It runs on rails"], answers: ["RAIN", "TRAIN"] },
  { clues: ["What a bruise causes", "It colours a wall"], answers: ["PAIN", "PAINT"] },
  { clues: ["Worn on the head", "Warmth"], answers: ["HAT", "HEAT"] },
  { clues: ["To come first", "Made from grapes"], answers: ["WIN", "WINE"] },
  { clues: ["Worn inside a shoe", "Goods kept in a shop"], answers: ["SOCK", "STOCK"] },
  { clues: ["You write with it", "Not closed"], answers: ["PEN", "OPEN"] },
  { clues: ["Paintings and sculpture", "A small arrow thrown at a board"], answers: ["ART", "DART"] },
  { clues: ["You drive it", "It comes in a deck"], answers: ["CAR", "CARD"] },
  { clues: ["Frozen water", "A grain eaten with curry"], answers: ["ICE", "RICE"] },
  { clues: ["To move fast on foot", "To spoil completely"], answers: ["RUN", "RUIN"] },
  { clues: ["Fighting between nations", "Pleasantly hot"], answers: ["WAR", "WARM"] },
  { clues: ["The ocean", "A whiskered animal that claps its flippers"], answers: ["SEA", "SEAL"] },
  { clues: ["A scheme", "It flies"], answers: ["PLAN", "PLANE"] },
  { clues: ["It greases an engine", "A loop of wire"], answers: ["OIL", "COIL"] },
  { clues: ["You smell with it", "Unwanted sound"], answers: ["NOSE", "NOISE"] },
  { clues: ["You tie one on a gift", "The ridge above your eye"], answers: ["BOW", "BROW"] },
  { clues: ["A female chicken", "After that"], answers: ["HEN", "THEN"] },
  { clues: ["A rodent", "A speed or a price"], answers: ["RAT", "RATE"] },
  { clues: ["A wide smile", "A single seed of wheat"], answers: ["GRIN", "GRAIN"] },
  { clues: ["You sit on it", "It beads on your skin when hot"], answers: ["SEAT", "SWEAT"] },
  { clues: ["A fish steers with it", "Very good, or a penalty payment"], answers: ["FIN", "FINE"] },
  { clues: ["It rings", "Your stomach"], answers: ["BELL", "BELLY"] },
  { clues: ["To turn round fast", "Your backbone"], answers: ["SPIN", "SPINE"] },
  { clues: ["Paper money", "A loud fight"], answers: ["CASH", "CLASH"] },
  { clues: ["A male child", "In a short while"], answers: ["SON", "SOON"] },
  { clues: ["A metal used for cans", "Very small"], answers: ["TIN", "TINY"] },
  { clues: ["A farm animal with horns and a beard", "To show off about winning"], answers: ["GOAT", "GLOAT"] },
  { clues: ["A black bird that caws", "A king wears it"], answers: ["CROW", "CROWN"] },
  { clues: ["You wipe your feet on it", "Sums and numbers at school"], answers: ["MAT", "MATH"] },
  { clues: ["A small green vegetable", "The top of a mountain"], answers: ["PEA", "PEAK"] },
  { clues: ["A rule made by government", "Grass in front of a house"], answers: ["LAW", "LAWN"] },
  { clues: ["Twice five", "Aged thirteen to nineteen"], answers: ["TEN", "TEEN"] }
];
