// Daily puzzle schedule for 2026. Made by: node tools/make-daily.js 2026 --refresh (days 1 to 283 kept from the earlier schedule)
// One line per day. Day 1 is January 1. Each puzzle is named by its key (see shared/keys.js).
// Do not edit by hand: past days should stay as they were.
window.DAILY_SCHEDULE = window.DAILY_SCHEDULE || {};
window.DAILY_SCHEDULE[2026] = [
  ["TENT","SALT","MIND","RUST"],  // 1 · Jan 1
  ["RACE","FIRE","FISH","MEAT"],  // 2 · Jan 2
  ["HOPE","GIRL","SWIM","SOUP"],  // 3 · Jan 3
  ["MOST","PEAR","LAMP","BARK"],  // 4 · Jan 4
  ["SING","STAR","BELL","DARE"],  // 5 · Jan 5
  ["TREE","JOKE","LION","PEEL"],  // 6 · Jan 6
  ["GRIP","SNOW","JUMP","CLAP"],  // 7 · Jan 7
  ["WORM","MASK","PINK","LAKE"],  // 8 · Jan 8
  ["TOAD","PLAY","NAIL","BALD"],  // 9 · Jan 9
  ["WEEK","RAIN","TALL","HEAD"],  // 10 · Jan 10
  ["MILK","SOCK","LEAF","DIRT"],  // 11 · Jan 11
  ["PUSH","MOLE","CORN","HILL"],  // 12 · Jan 12
  ["COAT","COLD","PORK","SHIP"],  // 13 · Jan 13
  ["WIND","FUEL","GLUE","MOON"],  // 14 · Jan 14
  ["DEEP","WARM","HERO","WISH"],  // 15 · Jan 15
  ["BOWL","GAME","FLAT","LUCK"],  // 16 · Jan 16
  ["VASE","GOLD","MOTH","WAVE"],  // 17 · Jan 17
  ["SAND","CAKE","BOOK","TOWN"],  // 18 · Jan 18
  ["DUCK","LIFT","SEAT","KING"],  // 19 · Jan 19
  ["OPEN","WOLF","LOVE","NECK"],  // 20 · Jan 20
  ["FARM","JUMP","SHIP","MOST"],  // 21 · Jan 21
  ["GOLD","HEAD","GRIP","LION"],  // 22 · Jan 22
  ["CAKE","WEEK","MOLE","FARM"],  // 23 · Jan 23
  ["WARM","BOOK","DEEP","SNOW"],  // 24 · Jan 24
  ["WORM","GLUE","PINK","CLAP"],  // 25 · Jan 25
  ["FUEL","JOKE","DARE","WISH"],  // 26 · Jan 26
  ["PLAY","LIFT","TOWN","PUSH"],  // 27 · Jan 27
  ["OPEN","NAIL","LUCK","SEAT"],  // 28 · Jan 28
  ["WOLF","SOCK","DUCK","MIND"],  // 29 · Jan 29
  ["PORK","LEAF","PEAR","RACE"],  // 30 · Jan 30
  ["HILL","SWIM","STAR","KING"],  // 31 · Jan 31
  ["COAT","MOTH","TALL","DIRT"],  // 32 · Feb 1
  ["LAKE","FLAT","SALT","FIRE"],  // 33 · Feb 2
  ["SAND","LOVE","PEEL","MASK"],  // 34 · Feb 3
  ["WIND","HERO","NECK","GIRL"],  // 35 · Feb 4
  ["LAMP","RAIN","GAME","RUST"],  // 36 · Feb 5
  ["FISH","SOUP","MILK","MOON"],  // 37 · Feb 6
  ["WAVE","HOPE","BALD","BOWL"],  // 38 · Feb 7
  ["TENT","COLD","TOAD","BELL"],  // 39 · Feb 8
  ["MEAT","VASE","TREE","CORN"],  // 40 · Feb 9
  ["SING","BARK","FLAT","PEAR"],  // 41 · Feb 10
  ["BALD","WORM","RUST","GLUE"],  // 42 · Feb 11
  ["LAMP","WEEK","GOLD","SOUP"],  // 43 · Feb 12
  ["DIRT","HOPE","WARM","HILL"],  // 44 · Feb 13
  ["KING","SAND","SNOW","PUSH"],  // 45 · Feb 14
  ["MEAT","CORN","FARM","PLAY"],  // 46 · Feb 15
  ["JUMP","GRIP","SHIP","GIRL"],  // 47 · Feb 16
  ["LAKE","PINK","HEAD","FUEL"],  // 48 · Feb 17
  ["BELL","TOAD","MOON","WOLF"],  // 49 · Feb 18
  ["DUCK","LOVE","MIND","GAME"],  // 50 · Feb 19
  ["BARK","COAT","TENT","MILK"],  // 51 · Feb 20
  ["NECK","SALT","OPEN","PEEL"],  // 52 · Feb 21
  ["MOTH","FISH","STAR","CAKE"],  // 53 · Feb 22
  ["VASE","JOKE","DEEP","BOWL"],  // 54 · Feb 23
  ["WAVE","COLD","DARE","LIFT"],  // 55 · Feb 24
  ["TALL","LION","SING","SOCK"],  // 56 · Feb 25
  ["RAIN","WISH","LEAF","CLAP"],  // 57 · Feb 26
  ["NAIL","WIND","PORK","LUCK"],  // 58 · Feb 27
  ["BOOK","TOWN","HERO","TREE"],  // 59 · Feb 28
  ["MOLE","SWIM","SEAT","MASK"],  // 60 · Mar 1
  ["FIRE","MOST","RACE","SWIM"],  // 61 · Mar 2
  ["SNOW","BARK","DEEP","HERO"],  // 62 · Mar 3
  ["FARM","GIRL","LAMP","OPEN"],  // 63 · Mar 4
  ["MASK","SALT","HILL","COAT"],  // 64 · Mar 5
  ["CLAP","MOON","PLAY","MEAT"],  // 65 · Mar 6
  ["NAIL","LEAF","SING","SAND"],  // 66 · Mar 7
  ["DARE","DIRT","PEEL","GLUE"],  // 67 · Mar 8
  ["TALL","LION","LOVE","PEAR"],  // 68 · Mar 9
  ["SHIP","TOWN","GAME","KING"],  // 69 · Mar 10
  ["CAKE","BELL","WISH","GRIP"],  // 70 · Mar 11
  ["BALD","LAKE","GOLD","STAR"],  // 71 · Mar 12
  ["NECK","RUST","LIFT","LUCK"],  // 72 · Mar 13
  ["FIRE","MIND","HEAD","DUCK"],  // 73 · Mar 14
  ["MOLE","COLD","SOUP","TOAD"],  // 74 · Mar 15
  ["TREE","RAIN","BOWL","PINK"],  // 75 · Mar 16
  ["WOLF","RACE","PORK","VASE"],  // 76 · Mar 17
  ["SOCK","HOPE","WORM","WAVE"],  // 77 · Mar 18
  ["MOTH","WIND","CORN","FLAT"],  // 78 · Mar 19
  ["FUEL","WEEK","TENT","JOKE"],  // 79 · Mar 20
  ["SEAT","MOST","PUSH","WARM"],  // 80 · Mar 21
  ["FISH","BOOK","JUMP","MILK"],  // 81 · Mar 22
  ["NAIL","DIRT","WAVE","GIRL"],  // 82 · Mar 23
  ["SALT","BALD","VASE","KING"],  // 83 · Mar 24
  ["STAR","HILL","BOOK","TALL"],  // 84 · Mar 25
  ["LEAF","RACE","LAKE","BOWL"],  // 85 · Mar 26
  ["SHIP","FIRE","COAT","TREE"],  // 86 · Mar 27
  ["WEEK","GRIP","JUMP","DARE"],  // 87 · Mar 28
  ["TOWN","FARM","JOKE","TENT"],  // 88 · Mar 29
  ["LAMP","SWIM","WIND","SING"],  // 89 · Mar 30
  ["SEAT","PLAY","TOAD","LOVE"],  // 90 · Mar 31
  ["COLD","SOUP","MOON","DUCK"],  // 91 · Apr 1
  ["CLAP","FLAT","MOTH","HERO"],  // 92 · Apr 2
  ["FUEL","WOLF","DEEP","BARK"],  // 93 · Apr 3
  ["RUST","GLUE","HEAD","CAKE"],  // 94 · Apr 4
  ["CORN","MOLE","LIFT","PINK"],  // 95 · Apr 5
  ["MILK","MIND","SNOW","MOST"],  // 96 · Apr 6
  ["MASK","WARM","PUSH","FISH"],  // 97 · Apr 7
  ["PEEL","RAIN","BELL","LUCK"],  // 98 · Apr 8
  ["WORM","SOCK","OPEN","NECK"],  // 99 · Apr 9
  ["PEAR","LION","MEAT","SAND"],  // 100 · Apr 10
  ["HOPE","WISH","GOLD","GAME"],  // 101 · Apr 11
  ["PORK","COLD","RAIN","SHIP"],  // 102 · Apr 12
  ["CLAP","LION","BOWL","MIND"],  // 103 · Apr 13
  ["JUMP","DUCK","HILL","GRIP"],  // 104 · Apr 14
  ["WARM","LEAF","KING","FUEL"],  // 105 · Apr 15
  ["SAND","LOVE","MOST","HERO"],  // 106 · Apr 16
  ["MEAT","SOCK","GIRL","CORN"],  // 107 · Apr 17
  ["LAKE","LAMP","BOOK","NECK"],  // 108 · Apr 18
  ["SWIM","BALD","VASE","PLAY"],  // 109 · Apr 19
  ["TALL","JOKE","PUSH","TENT"],  // 110 · Apr 20
  ["COAT","HEAD","SOUP","WOLF"],  // 111 · Apr 21
  ["LUCK","TOAD","BELL","MASK"],  // 112 · Apr 22
  ["TREE","MOTH","PORK","WORM"],  // 113 · Apr 23
  ["DIRT","LIFT","FARM","WEEK"],  // 114 · Apr 24
  ["DEEP","PEAR","RUST","SEAT"],  // 115 · Apr 25
  ["OPEN","TOWN","HOPE","SNOW"],  // 116 · Apr 26
  ["NAIL","DARE","PINK","MOON"],  // 117 · Apr 27
  ["FISH","CAKE","WISH","FIRE"],  // 118 · Apr 28
  ["GAME","GLUE","RACE","MILK"],  // 119 · Apr 29
  ["STAR","WIND","SALT","PEEL"],  // 120 · Apr 30
  ["MOLE","WAVE","GOLD","BARK"],  // 121 · May 1
  ["SING","FLAT","SAND","WIND"],  // 122 · May 2
  ["PEAR","HEAD","BOOK","DUCK"],  // 123 · May 3
  ["MEAT","COLD","MOTH","LEAF"],  // 124 · May 4
  ["PUSH","WARM","PORK","LION"],  // 125 · May 5
  ["LAMP","CLAP","RUST","LOVE"],  // 126 · May 6
  ["MOLE","FARM","TREE","SNOW"],  // 127 · May 7
  ["SWIM","CORN","WISH","GIRL"],  // 128 · May 8
  ["BELL","SHIP","JUMP","SOCK"],  // 129 · May 9
  ["TENT","WAVE","RAIN","MILK"],  // 130 · May 10
  ["DEEP","NAIL","BOWL","GAME"],  // 131 · May 11
  ["WORM","LIFT","TALL","MOST"],  // 132 · May 12
  ["FISH","VASE","DIRT","JOKE"],  // 133 · May 13
  ["PLAY","HILL","MIND","DARE"],  // 134 · May 14
  ["RACE","COAT","GOLD","SALT"],  // 135 · May 15
  ["BARK","STAR","GLUE","KING"],  // 136 · May 16
  ["FUEL","HERO","MASK","MOON"],  // 137 · May 17
  ["SOUP","PEEL","NECK","WOLF"],  // 138 · May 18
  ["LAKE","SEAT","BALD","TOAD"],  // 139 · May 19
  ["FIRE","PINK","SING","WEEK"],  // 140 · May 20
  ["HOPE","FLAT","GRIP","TOWN"],  // 141 · May 21
  ["OPEN","LUCK","CAKE","SALT"],  // 142 · May 22
  ["LAMP","NAIL","GAME","HOPE"],  // 143 · May 23
  ["FISH","GRIP","MOTH","STAR"],  // 144 · May 24
  ["LOVE","BARK","SOCK","LIFT"],  // 145 · May 25
  ["FARM","WARM","TREE","DARE"],  // 146 · May 26
  ["JUMP","RACE","SWIM","JOKE"],  // 147 · May 27
  ["CLAP","HERO","NECK","PEEL"],  // 148 · May 28
  ["BOOK","PEAR","SOUP","OPEN"],  // 149 · May 29
  ["LEAF","WEEK","MEAT","KING"],  // 150 · May 30
  ["HILL","SHIP","FLAT","LAKE"],  // 151 · May 31
  ["PLAY","PINK","WAVE","RAIN"],  // 152 · Jun 1
  ["GLUE","MOST","LION","TOWN"],  // 153 · Jun 2
  ["PUSH","MASK","BELL","MIND"],  // 154 · Jun 3
  ["FUEL","SAND","MOON","DIRT"],  // 155 · Jun 4
  ["FIRE","CORN","GIRL","SNOW"],  // 156 · Jun 5
  ["BOWL","COAT","WISH","TALL"],  // 157 · Jun 6
  ["MOLE","PORK","DEEP","WOLF"],  // 158 · Jun 7
  ["COLD","VASE","SING","RUST"],  // 159 · Jun 8
  ["SEAT","CAKE","TOAD","HEAD"],  // 160 · Jun 9
  ["DUCK","MILK","WORM","LUCK"],  // 161 · Jun 10
  ["BALD","WIND","TENT","GOLD"],  // 162 · Jun 11
  ["CLAP","TOWN","SAND","SNOW"],  // 163 · Jun 12
  ["LAMP","GLUE","HILL","MASK"],  // 164 · Jun 13
  ["MOON","MILK","DEEP","GRIP"],  // 165 · Jun 14
  ["LION","MOLE","WIND","FUEL"],  // 166 · Jun 15
  ["HEAD","RAIN","TENT","TREE"],  // 167 · Jun 16
  ["PEAR","SING","TOAD","LEAF"],  // 168 · Jun 17
  ["LAKE","CORN","GOLD","SOUP"],  // 169 · Jun 18
  ["BELL","WARM","WORM","VASE"],  // 170 · Jun 19
  ["NECK","GAME","FLAT","LUCK"],  // 171 · Jun 20
  ["WEEK","FIRE","OPEN","RACE"],  // 172 · Jun 21
  ["DUCK","GIRL","STAR","PEEL"],  // 173 · Jun 22
  ["MOTH","MIND","PUSH","FISH"],  // 174 · Jun 23
  ["WISH","SEAT","JUMP","KING"],  // 175 · Jun 24
  ["SOCK","LIFT","BARK","DARE"],  // 176 · Jun 25
  ["MEAT","SHIP","SWIM","HOPE"],  // 177 · Jun 26
  ["BOWL","COLD","LOVE","BALD"],  // 178 · Jun 27
  ["COAT","JOKE","PORK","CAKE"],  // 179 · Jun 28
  ["SALT","TALL","HERO","PLAY"],  // 180 · Jun 29
  ["NAIL","RUST","DIRT","WOLF"],  // 181 · Jun 30
  ["MOST","PINK","BOOK","FARM"],  // 182 · Jul 1
  ["WAVE","WIND","DUCK","LEAF"],  // 183 · Jul 2
  ["MOTH","COAT","WOLF","GOLD"],  // 184 · Jul 3
  ["DEEP","DIRT","LUCK","RUST"],  // 185 · Jul 4
  ["GIRL","SOCK","PEAR","PLAY"],  // 186 · Jul 5
  ["WARM","BARK","OPEN","SWIM"],  // 187 · Jul 6
  ["FUEL","BALD","WISH","GAME"],  // 188 · Jul 7
  ["SAND","CAKE","LOVE","LAKE"],  // 189 · Jul 8
  ["VASE","SNOW","WAVE","HILL"],  // 190 · Jul 9
  ["SHIP","WEEK","KING","COLD"],  // 191 · Jul 10
  ["BOWL","NECK","GLUE","BOOK"],  // 192 · Jul 11
  ["LION","MIND","TREE","CLAP"],  // 193 · Jul 12
  ["WORM","SING","TOAD","MEAT"],  // 194 · Jul 13
  ["MOST","TENT","SOUP","JUMP"],  // 195 · Jul 14
  ["HEAD","STAR","PEEL","RACE"],  // 196 · Jul 15
  ["SALT","SEAT","LIFT","RAIN"],  // 197 · Jul 16
  ["PORK","CORN","TALL","LAMP"],  // 198 · Jul 17
  ["GRIP","MASK","MOLE","PUSH"],  // 199 · Jul 18
  ["MOON","FIRE","PINK","HOPE"],  // 200 · Jul 19
  ["FARM","BELL","NAIL","HERO"],  // 201 · Jul 20
  ["FISH","FLAT","JOKE","TOWN"],  // 202 · Jul 21
  ["DARE","MILK","LION","MOLE"],  // 203 · Jul 22
  ["KING","BOWL","JOKE","PINK"],  // 204 · Jul 23
  ["COAT","TREE","CORN","MASK"],  // 205 · Jul 24
  ["LUCK","DEEP","DIRT","HILL"],  // 206 · Jul 25
  ["MOTH","LOVE","BALD","HERO"],  // 207 · Jul 26
  ["PUSH","MOON","RUST","HOPE"],  // 208 · Jul 27
  ["LAMP","FUEL","DUCK","BARK"],  // 209 · Jul 28
  ["CLAP","WEEK","LEAF","SAND"],  // 210 · Jul 29
  ["PEEL","SALT","FIRE","TALL"],  // 211 · Jul 30
  ["TENT","GLUE","LIFT","TOAD"],  // 212 · Jul 31
  ["BOOK","WAVE","HEAD","PORK"],  // 213 · Aug 1
  ["TOWN","MIND","RAIN","GOLD"],  // 214 · Aug 2
  ["DARE","WISH","SHIP","PEAR"],  // 215 · Aug 3
  ["GRIP","BELL","RACE","SNOW"],  // 216 · Aug 4
  ["WARM","NAIL","NECK","SOCK"],  // 217 · Aug 5
  ["FARM","CAKE","SOUP","LAKE"],  // 218 · Aug 6
  ["SEAT","SING","VASE","MOST"],  // 219 · Aug 7
  ["WORM","PLAY","MILK","JUMP"],  // 220 · Aug 8
  ["STAR","FISH","OPEN","MEAT"],  // 221 · Aug 9
  ["SWIM","WOLF","WIND","GAME"],  // 222 · Aug 10
  ["GIRL","COLD","FLAT","WAVE"],  // 223 · Aug 11
  ["MOON","FISH","TREE","COAT"],  // 224 · Aug 12
  ["TALL","BALD","LUCK","SOUP"],  // 225 · Aug 13
  ["BARK","SAND","MOLE","DARE"],  // 226 · Aug 14
  ["DIRT","TOWN","SHIP","COLD"],  // 227 · Aug 15
  ["WOLF","LEAF","CORN","FUEL"],  // 228 · Aug 16
  ["BOOK","STAR","KING","MEAT"],  // 229 · Aug 17
  ["JOKE","WIND","LIFT","MIND"],  // 230 · Aug 18
  ["SOCK","WEEK","TOAD","PORK"],  // 231 · Aug 19
  ["JUMP","LAKE","LAMP","GIRL"],  // 232 · Aug 20
  ["RUST","GOLD","OPEN","RACE"],  // 233 · Aug 21
  ["GRIP","HERO","GLUE","MILK"],  // 234 · Aug 22
  ["HEAD","SALT","SWIM","PEAR"],  // 235 · Aug 23
  ["VASE","FARM","PLAY","NECK"],  // 236 · Aug 24
  ["TENT","MOST","MOTH","PINK"],  // 237 · Aug 25
  ["LOVE","HILL","BELL","GAME"],  // 238 · Aug 26
  ["SNOW","BOWL","WORM","SING"],  // 239 · Aug 27
  ["DUCK","PEEL","NAIL","FLAT"],  // 240 · Aug 28
  ["WISH","SEAT","WARM","DEEP"],  // 241 · Aug 29
  ["LION","RAIN","PUSH","HOPE"],  // 242 · Aug 30
  ["FIRE","MASK","CLAP","CAKE"],  // 243 · Aug 31
  ["DARE","TOWN","DIRT","RACE"],  // 244 · Sep 1
  ["HERO","PEEL","HOPE","MOLE"],  // 245 · Sep 2
  ["WISH","MASK","MEAT","LAKE"],  // 246 · Sep 3
  ["LIFT","WIND","WAVE","GOLD"],  // 247 · Sep 4
  ["HILL","GRIP","GAME","TALL"],  // 248 · Sep 5
  ["GLUE","SEAT","VASE","COAT"],  // 249 · Sep 6
  ["FISH","LOVE","JOKE","WARM"],  // 250 · Sep 7
  ["WORM","PORK","MIND","SNOW"],  // 251 · Sep 8
  ["DEEP","MOON","FIRE","RUST"],  // 252 · Sep 9
  ["TENT","LUCK","COLD","TOAD"],  // 253 · Sep 10
  ["MOST","PEAR","GIRL","SALT"],  // 254 · Sep 11
  ["WOLF","BOOK","SWIM","CORN"],  // 255 · Sep 12
  ["SAND","PLAY","LAMP","FARM"],  // 256 · Sep 13
  ["MOTH","STAR","JUMP","HEAD"],  // 257 · Sep 14
  ["KING","RAIN","BELL","FLAT"],  // 258 · Sep 15
  ["PINK","MILK","LEAF","WEEK"],  // 259 · Sep 16
  ["OPEN","CLAP","LION","DUCK"],  // 260 · Sep 17
  ["NAIL","BARK","CAKE","SING"],  // 261 · Sep 18
  ["BALD","NECK","SOUP","SHIP"],  // 262 · Sep 19
  ["TREE","BOWL","SOCK","PUSH"],  // 263 · Sep 20
  ["FUEL","SALT","SOUP","CLAP"],  // 264 · Sep 21
  ["CAKE","MIND","RUST","RAIN"],  // 265 · Sep 22
  ["NAIL","CORN","LION","BOWL"],  // 266 · Sep 23
  ["LUCK","DUCK","HOPE","SEAT"],  // 267 · Sep 24
  ["GOLD","WAVE","GIRL","WOLF"],  // 268 · Sep 25
  ["WIND","COAT","MEAT","MOON"],  // 269 · Sep 26
  ["GLUE","SWIM","WISH","STAR"],  // 270 · Sep 27
  ["TENT","GRIP","TOAD","SOCK"],  // 271 · Sep 28
  ["SAND","NECK","TALL","FIRE"],  // 272 · Sep 29
  ["LAMP","LIFT","DEEP","TREE"],  // 273 · Sep 30
  ["HILL","MOST","PLAY","VASE"],  // 274 · Oct 1
  ["LAKE","BARK","PUSH","HERO"],  // 275 · Oct 2
  ["PEEL","JUMP","SHIP","DIRT"],  // 276 · Oct 3
  ["TOWN","MOTH","RACE","WEEK"],  // 277 · Oct 4
  ["PORK","MASK","MOLE","FLAT"],  // 278 · Oct 5
  ["COLD","LEAF","GAME","JOKE"],  // 279 · Oct 6
  ["LOVE","SNOW","OPEN","PINK"],  // 280 · Oct 7
  ["HEAD","KING","WARM","BOOK"],  // 281 · Oct 8
  ["PEAR","SING","MILK","WORM"],  // 282 · Oct 9
  ["BARK","BOWL","HARP","GLUE"],  // 283 · Oct 10
  ["WEED","HERO","CAKE","SNAP"],  // 284 · Oct 11
  ["HOUR","NECK","PORK","LIFT"],  // 285 · Oct 12
  ["BOOK","GIRL","SEAT","ROCK"],  // 286 · Oct 13
  ["NEST","DARE","PALM","FROG"],  // 287 · Oct 14
  ["HARP","SKIN","MASK","FUEL"],  // 288 · Oct 15
  ["SING","WOLF","DARK","LAMP"],  // 289 · Oct 16
  ["KING","TENT","WIND","JAIL"],  // 290 · Oct 17
  ["BOWL","SHED","DUCK","WOOL"],  // 291 · Oct 18
  ["TOAD","PUSH","CARD","TUNE"],  // 292 · Oct 19
  ["BEAD","BALD","KING","BOLD"],  // 293 · Oct 20
  ["LAMB","MOTH","TOAD","RACE"],  // 294 · Oct 21
  ["LUCK","DARE","LEAF","MILE"],  // 295 · Oct 22
  ["ROPE","HEAD","HOUR","MINT"],  // 296 · Oct 23
  ["JAIL","TENT","CLAP","PLAY"],  // 297 · Oct 24
  ["HORN","OPEN","SALT","FLAT"],  // 298 · Oct 25
  ["SAND","DARK","HERO","WOOL"],  // 299 · Oct 26
  ["LION","NEST","BOOK","WALL"],  // 300 · Oct 27
  ["TUNE","RUST","MOLE","SEAL"],  // 301 · Oct 28
  ["LOAF","WOLF","FUND","WEED"],  // 302 · Oct 29
  ["NAIL","CAVE","BELL","BIRD"],  // 303 · Oct 30
  ["SEAT","SHOE","LIFT","HEEL"],  // 304 · Oct 31
  ["JUMP","BULB","SHED","GLUE"],  // 305 · Nov 1
  ["MEAT","LOVE","BOWL","RAFT"],  // 306 · Nov 2
  ["WORM","TIDE","WIND","CRAB"],  // 307 · Nov 3
  ["WASP","MOST","SEED","PORK"],  // 308 · Nov 4
  ["NOSE","SKIN","PUSH","TOOL"],  // 309 · Nov 5
  ["VASE","BATH","GOWN","SOUP"],  // 310 · Nov 6
  ["VEIL","FOOT","RAIN","FIRE"],  // 311 · Nov 7
  ["LOCK","KITE","MILK","DUCK"],  // 312 · Nov 8
  ["PALM","SNOW","SOCK","MAIL"],  // 313 · Nov 9
  ["COAL","HOPE","CLUB","BOAT"],  // 314 · Nov 10
  ["CORK","TOWN","DOOR","WARM"],  // 315 · Nov 11
  ["TALL","CANE","GIRL","MIND"],  // 316 · Nov 12
  ["REED","MOON","MASK","LAMP"],  // 317 · Nov 13
  ["HARP","LATE","ROCK","BARK"],  // 318 · Nov 14
  ["CORN","DICE","OVEN","PINK"],  // 319 · Nov 15
  ["BEAR","PEAR","PAIL","COLD"],  // 320 · Nov 16
  ["WISH","GOLD","DEEP","GAME"],  // 321 · Nov 17
  ["SWIM","FROG","BULL","SING"],  // 322 · Nov 18
  ["JOKE","FISH","COAT","DESK"],  // 323 · Nov 19
  ["NECK","SHOP","HILL","PINE"],  // 324 · Nov 20
  ["LAKE","PLUM","FUEL","CAKE"],  // 325 · Nov 21
  ["CARD","STAR","FLEA","TREE"],  // 326 · Nov 22
  ["DIRT","WEEK","SNAP","PUMP"],  // 327 · Nov 23
  ["PEEL","SHIP","WAVE","FARM"],  // 328 · Nov 24
  ["GRIP","BEAN","HEEL","LUCK"],  // 329 · Nov 25
  ["PLUM","BOOK","LOAF","WASP"],  // 330 · Nov 26
  ["MOTH","SNAP","CARD","MEAT"],  // 331 · Nov 27
  ["PAIL","BULL","FOOT","SEED"],  // 332 · Nov 28
  ["SEAT","HEAD","GIRL","NAIL"],  // 333 · Nov 29
  ["LAMB","BATH","CAVE","OPEN"],  // 334 · Nov 30
  ["JOKE","PUMP","PEAR","CORK"],  // 335 · Dec 1
  ["CAKE","MILE","SHED","HILL"],  // 336 · Dec 2
  ["BEAN","JUMP","STAR","LATE"],  // 337 · Dec 3
  ["GLUE","NECK","LION","TUNE"],  // 338 · Dec 4
  ["WARM","RAFT","DUCK","GAME"],  // 339 · Dec 5
  ["TOOL","WAVE","CORN","MIND"],  // 340 · Dec 6
  ["BARK","BOAT","WEED","BOLD"],  // 341 · Dec 7
  ["TOWN","FARM","SING","RUST"],  // 342 · Dec 8
  ["GOWN","COLD","JAIL","FUEL"],  // 343 · Dec 9
  ["WISH","COAL","PEEL","KING"],  // 344 · Dec 10
  ["SHIP","DARE","REED","GOLD"],  // 345 · Dec 11
  ["BEAD","CANE","HOPE","WOLF"],  // 346 · Dec 12
  ["LOCK","LEAF","SNOW","HERO"],  // 347 · Dec 13
  ["SOCK","PINK","WORM","DOOR"],  // 348 · Dec 14
  ["CRAB","PLAY","PORK","DIRT"],  // 349 · Dec 15
  ["FIRE","PALM","FLEA","TOAD"],  // 350 · Dec 16
  ["LOVE","MAIL","PUSH","NEST"],  // 351 · Dec 17
  ["FISH","OVEN","SKIN","SALT"],  // 352 · Dec 18
  ["FUND","HORN","PINE","LAMP"],  // 353 · Dec 19
  ["SOUP","BALD","WEEK","VEIL"],  // 354 · Dec 20
  ["HOUR","DARK","FLAT","BULB"],  // 355 · Dec 21
  ["SAND","HARP","FROG","CLUB"],  // 356 · Dec 22
  ["DICE","ROCK","WIND","TALL"],  // 357 · Dec 23
  ["SHOE","LAKE","WOOL","BEAR"],  // 358 · Dec 24
  ["KITE","TIDE","LIFT","MILK"],  // 359 · Dec 25
  ["MINT","TENT","NOSE","BIRD"],  // 360 · Dec 26
  ["RACE","GRIP","CLAP","BOWL"],  // 361 · Dec 27
  ["SHOP","WALL","MOON","DEEP"],  // 362 · Dec 28
  ["DESK","COAT","BELL","ROPE"],  // 363 · Dec 29
  ["TREE","MASK","MOST","RAIN"],  // 364 · Dec 30
  ["SWIM","MOLE","VASE","SEAL"]  // 365 · Dec 31
];
