// Daily puzzle schedule for 2026. Made by: node tools/make-daily.js 2026 --refresh (days 1 to 283 kept from the earlier schedule)
// One line per day. Day 1 is January 1. Each puzzle is named by its key (see shared/keys.js).
// Do not edit by hand: past days should stay as they were.
window.DAILY_SCHEDULE = window.DAILY_SCHEDULE || {};
window.DAILY_SCHEDULE[2026] = [
  ["HOUR","BREAK","CELL","WAIT","MISSED"],  // 1 · Jan 1
  ["BLUE","PEEK","BOUGH","FEAT","ALLOWED"],  // 2 · Jan 2
  ["HEAL","WOOD","TOAD","KNEAD","NONE"],  // 3 · Jan 3
  ["FLEA","SAIL","HAIR","WEEK","CENT"],  // 4 · Jan 4
  ["SOAR","ROSE","WEIGH","FAIR","TOE"],  // 5 · Jan 5
  ["ROAD","DEER","WAIST","SOLE","SUITE"],  // 6 · Jan 6
  ["IDLE","WEAR","PALE","CREAK","GUEST"],  // 7 · Jan 7
  ["MANE","MAZE","ONE","WHALE","HOLE"],  // 8 · Jan 8
  ["VAIN","MEAT","PAUSE","BEAN","SCENE"],  // 9 · Jan 9
  ["PLAIN","MAIL","FLEW","HIGHER","LOAN"],  // 10 · Jan 10
  ["FLOUR","RAIN","THRONE","LESSON","WAIVE"],  // 11 · Jan 11
  ["STEAK","HEARD","MUSCLE","RIGHT","HORSE"],  // 12 · Jan 12
  ["EIGHT","CHEWS","BARE","BEACH","SIGHT"],  // 13 · Jan 13
  ["LEAK","DIE","PAIR","PEACE","STEAL"],  // 14 · Jan 14
  ["YOLK","TAIL","KNIGHT","KNEW","SEE"],  // 15 · Jan 15
  ["TIDE","RING","BUY","BOARD","PRAY"],  // 16 · Jan 16
  ["SON","GROAN","KNOT","SEAM","STAIR"],  // 17 · Jan 17
  ["GRATE","MUSCLE","KNEAD","HEAL","DIE"],  // 18 · Jan 18
  ["HORSE","PEACE","ROAD","SEE","LOAN"],  // 19 · Jan 19
  ["PLAIN","HOLE","PAIR","SEAM","WAIT"],  // 20 · Jan 20
  ["KNIGHT","BLUE","HAIR","YOLK","FAIR"],  // 21 · Jan 21
  ["FLOUR","RIGHT","PEEK","HIGHER","WHALE"],  // 22 · Jan 22
  ["WOOD","BREAK","CELL","WEIGH","TOAD"],  // 23 · Jan 23
  ["ONE","SOLE","STEAL","MANE","FLEW"],  // 24 · Jan 24
  ["SUITE","RAIN","IDLE","MEAT","ROSE"],  // 25 · Jan 25
  ["PAUSE","CREAK","SIGHT","BOARD","FEAT"],  // 26 · Jan 26
  ["WEEK","THRONE","GRATE","BEAN","EIGHT"],  // 27 · Jan 27
  ["DEER","BOUGH","SON","HOUR","KNOT"],  // 28 · Jan 28
  ["CENT","MAZE","HEARD","BUY","CHEWS"],  // 29 · Jan 29
  ["KNEW","NONE","FLEA","SCENE","WAIVE"],  // 30 · Jan 30
  ["VAIN","STAIR","TOE","SAIL","PALE"],  // 31 · Jan 31
  ["GUEST","WEAR","BEACH","SOAR","MISSED"],  // 32 · Feb 1
  ["TAIL","MAIL","LESSON","WAIST","LEAK"],  // 33 · Feb 2
  ["PRAY","BARE","ALLOWED","RING","TIDE"],  // 34 · Feb 3
  ["GROAN","STEAK","WAIST","DIE","CREAK"],  // 35 · Feb 4
  ["IDLE","SUITE","RING","STEAK","GROAN"],  // 36 · Feb 5
  ["MUSCLE","FEAT","SIGHT","SAIL","RAIN"],  // 37 · Feb 6
  ["PLAIN","MAZE","STEAL","GUEST","KNEW"],  // 38 · Feb 7
  ["NONE","HEARD","HOLE","SON","GRATE"],  // 39 · Feb 8
  ["CHEWS","WAIT","KNOT","PAUSE","FLEA"],  // 40 · Feb 9
  ["FAIR","SOLE","TOE","MANE","WEIGH"],  // 41 · Feb 10
  ["CELL","PALE","BOARD","BUY","PAIR"],  // 42 · Feb 11
  ["FLEW","ROAD","RIGHT","BEAN","TIDE"],  // 43 · Feb 12
  ["KNEAD","KNIGHT","CENT","MAIL","BLUE"],  // 44 · Feb 13
  ["LEAK","EIGHT","STAIR","HOUR","SEE"],  // 45 · Feb 14
  ["THRONE","BOUGH","WHALE","SEAM","TOAD"],  // 46 · Feb 15
  ["WOOD","SCENE","LOAN","SOAR","PRAY"],  // 47 · Feb 16
  ["LESSON","VAIN","BEACH","WEAR","MISSED"],  // 48 · Feb 17
  ["FLOUR","WEEK","DEER","BARE","YOLK"],  // 49 · Feb 18
  ["ALLOWED","PEACE","ONE","TAIL","HAIR"],  // 50 · Feb 19
  ["MEAT","PEEK","HORSE","WAIVE","BREAK"],  // 51 · Feb 20
  ["HIGHER","HEAL","ROSE","SCENE","TAIL"],  // 52 · Feb 21
  ["KNEW","KNIGHT","BEACH","SEE","CENT"],  // 53 · Feb 22
  ["THRONE","SEAM","PRAY","DEER","GUEST"],  // 54 · Feb 23
  ["MUSCLE","EIGHT","STEAL","BOARD","BEAN"],  // 55 · Feb 24
  ["HIGHER","BARE","TOE","HORSE","PAIR"],  // 56 · Feb 25
  ["PLAIN","ROSE","PAUSE","MAIL","BOUGH"],  // 57 · Feb 26
  ["ONE","TOAD","CELL","MISSED","WAIVE"],  // 58 · Feb 27
  ["RAIN","MANE","DIE","SON","IDLE"],  // 59 · Feb 28
  ["GROAN","HOUR","WHALE","HOLE","WEEK"],  // 60 · Mar 1
  ["MEAT","ROAD","SIGHT","NONE","WOOD"],  // 61 · Mar 2
  ["WAIT","PEACE","VAIN","SOLE","KNEAD"],  // 62 · Mar 3
  ["LEAK","BUY","STEAK","PEEK","PALE"],  // 63 · Mar 4
  ["MAZE","WEIGH","YOLK","CHEWS","FAIR"],  // 64 · Mar 5
  ["FLEW","WEAR","FEAT","HEARD","LOAN"],  // 65 · Mar 6
  ["CREAK","GRATE","RING","SOAR","FLOUR"],  // 66 · Mar 7
  ["STAIR","ALLOWED","HEAL","KNOT","RIGHT"],  // 67 · Mar 8
  ["TIDE","SAIL","FLEA","LESSON","HAIR"],  // 68 · Mar 9
  ["BREAK","SUITE","BLUE","WAIST","HORSE"],  // 69 · Mar 10
  ["KNEW","DIE","LEAK","BUY","BREAK"],  // 70 · Mar 11
  ["HOLE","SIGHT","WEAR","HIGHER","PEEK"],  // 71 · Mar 12
  ["RAIN","KNIGHT","LOAN","THRONE","WOOD"],  // 72 · Mar 13
  ["BEACH","KNOT","GRATE","DEER","CREAK"],  // 73 · Mar 14
  ["WEIGH","GUEST","TOE","PAUSE","HEARD"],  // 74 · Mar 15
  ["RIGHT","RING","FLEA","PLAIN","PALE"],  // 75 · Mar 16
  ["SEAM","YOLK","SAIL","FEAT","CENT"],  // 76 · Mar 17
  ["STAIR","ONE","SOAR","SUITE","KNEAD"],  // 77 · Mar 18
  ["MAIL","WAIVE","ALLOWED","HEAL","IDLE"],  // 78 · Mar 19
  ["MAZE","WEEK","CHEWS","WAIST","HAIR"],  // 79 · Mar 20
  ["ROAD","BARE","TOAD","PRAY","TAIL"],  // 80 · Mar 21
  ["BEAN","MANE","ROSE","BLUE","FAIR"],  // 81 · Mar 22
  ["STEAK","NONE","MISSED","EIGHT","FLOUR"],  // 82 · Mar 23
  ["WHALE","FLEW","SCENE","BOUGH","BOARD"],  // 83 · Mar 24
  ["SEE","PEACE","SON","LESSON","SOLE"],  // 84 · Mar 25
  ["CELL","STEAL","TIDE","WAIT","HOUR"],  // 85 · Mar 26
  ["VAIN","PAIR","GROAN","MUSCLE","MEAT"],  // 86 · Mar 27
  ["ROSE","SOLE","TAIL","PEEK","VAIN"],  // 87 · Mar 28
  ["ALLOWED","WEAR","SAIL","SIGHT","BUY"],  // 88 · Mar 29
  ["BEACH","EIGHT","WEIGH","MAIL","WAIVE"],  // 89 · Mar 30
  ["STAIR","THRONE","STEAL","PAUSE","RING"],  // 90 · Mar 31
  ["SCENE","BLUE","MUSCLE","CREAK","SEE"],  // 91 · Apr 1
  ["HEAL","FLEW","FEAT","RAIN","FAIR"],  // 92 · Apr 2
  ["MEAT","GRATE","BREAK","ROAD","HEARD"],  // 93 · Apr 3
  ["PLAIN","HOLE","WEEK","DEER","SUITE"],  // 94 · Apr 4
  ["MISSED","BEAN","DIE","SEAM","YOLK"],  // 95 · Apr 5
  ["SON","PAIR","HAIR","CHEWS","KNEAD"],  // 96 · Apr 6
  ["BOARD","KNIGHT","WOOD","WAIT","BARE"],  // 97 · Apr 7
  ["GROAN","TIDE","KNOT","KNEW","ONE"],  // 98 · Apr 8
  ["CENT","FLEA","LOAN","WHALE","MAZE"],  // 99 · Apr 9
  ["STEAK","LESSON","FLOUR","WAIST","TOE"],  // 100 · Apr 10
  ["SOAR","PEACE","HOUR","PALE","NONE"],  // 101 · Apr 11
  ["GUEST","RIGHT","TOAD","IDLE","PRAY"],  // 102 · Apr 12
  ["HORSE","HIGHER","LEAK","CELL","BOUGH"],  // 103 · Apr 13
  ["MANE","YOLK","SIGHT","CHEWS","CELL"],  // 104 · Apr 14
  ["FLOUR","DEER","WOOD","RAIN","PAIR"],  // 105 · Apr 15
  ["TAIL","PAUSE","FLEA","WEEK","HORSE"],  // 106 · Apr 16
  ["GRATE","RING","MAZE","PEACE","BREAK"],  // 107 · Apr 17
  ["BLUE","DIE","HAIR","KNEAD","FEAT"],  // 108 · Apr 18
  ["ROAD","BUY","LOAN","KNOT","HEARD"],  // 109 · Apr 19
  ["STAIR","SOLE","FLEW","MANE","TOAD"],  // 110 · Apr 20
  ["STEAK","GROAN","MUSCLE","HIGHER","HOLE"],  // 111 · Apr 21
  ["MAIL","VAIN","WAIST","IDLE","NONE"],  // 112 · Apr 22
  ["SON","PALE","RIGHT","HEAL","GUEST"],  // 113 · Apr 23
  ["SCENE","ONE","LESSON","ROSE","SUITE"],  // 114 · Apr 24
  ["ALLOWED","PLAIN","SAIL","SEE","MEAT"],  // 115 · Apr 25
  ["BEACH","SOAR","WAIT","MISSED","BEAN"],  // 116 · Apr 26
  ["BARE","KNIGHT","FAIR","SEAM","PEEK"],  // 117 · Apr 27
  ["CREAK","TIDE","BOUGH","WHALE","THRONE"],  // 118 · Apr 28
  ["CENT","PRAY","KNEW","HOUR","WEAR"],  // 119 · Apr 29
  ["TOE","WAIVE","WEIGH","LEAK","EIGHT"],  // 120 · Apr 30
  ["BOARD","STEAL","BARE","SAIL","FEAT"],  // 121 · May 1
  ["WEEK","KNEW","KNIGHT","SOAR","CELL"],  // 122 · May 2
  ["BOARD","BLUE","WAIST","GRATE","DEER"],  // 123 · May 3
  ["ROSE","KNEAD","FLOUR","SUITE","TAIL"],  // 124 · May 4
  ["MEAT","STEAL","SCENE","HORSE","CREAK"],  // 125 · May 5
  ["HEAL","KNOT","BEAN","PRAY","WAIT"],  // 126 · May 6
  ["PALE","RIGHT","SON","FLEA","BEACH"],  // 127 · May 7
  ["YOLK","SEE","SEAM","EIGHT","SIGHT"],  // 128 · May 8
  ["SOLE","PAUSE","BREAK","STAIR","TIDE"],  // 129 · May 9
  ["NONE","LOAN","ROAD","WEIGH","MUSCLE"],  // 130 · May 10
  ["HAIR","PLAIN","IDLE","STEAK","PEACE"],  // 131 · May 11
  ["TOAD","MAIL","LEAK","THRONE","FLEW"],  // 132 · May 12
  ["GROAN","WOOD","HEARD","HOLE","WAIVE"],  // 133 · May 13
  ["ALLOWED","FAIR","CENT","TOE","LESSON"],  // 134 · May 14
  ["WHALE","CHEWS","PAIR","HIGHER","RAIN"],  // 135 · May 15
  ["MISSED","PEEK","BUY","ONE","WEAR"],  // 136 · May 16
  ["RING","MAZE","DIE","MANE","GUEST"],  // 137 · May 17
  ["VAIN","BOUGH","HOUR","KNIGHT","TIDE"],  // 138 · May 18
  ["KNEW","FLEW","DEER","HEAL","ALLOWED"],  // 139 · May 19
  ["BUY","HIGHER","PAIR","FLOUR","PRAY"],  // 140 · May 20
  ["WEEK","PEACE","HOLE","FAIR","MAZE"],  // 141 · May 21
  ["GRATE","PEEK","SEAM","CELL","WEIGH"],  // 142 · May 22
  ["ROSE","SOLE","BARE","STAIR","BEACH"],  // 143 · May 23
  ["ROAD","WAIST","TOAD","STEAK","FLEA"],  // 144 · May 24
  ["YOLK","SOAR","RING","MUSCLE","LOAN"],  // 145 · May 25
  ["HOUR","PAUSE","VAIN","MISSED","HEARD"],  // 146 · May 26
  ["HAIR","KNEAD","MANE","SCENE","RIGHT"],  // 147 · May 27
  ["SUITE","PALE","ONE","WAIVE","PLAIN"],  // 148 · May 28
  ["DIE","BLUE","KNOT","BOARD","RAIN"],  // 149 · May 29
  ["GUEST","BEAN","WHALE","THRONE","MEAT"],  // 150 · May 30
  ["BREAK","TOE","WAIT","SAIL","LEAK"],  // 151 · May 31
  ["FEAT","GROAN","IDLE","HORSE","TAIL"],  // 152 · Jun 1
  ["SON","NONE","STEAL","SEE","WOOD"],  // 153 · Jun 2
  ["EIGHT","MAIL","CHEWS","BOUGH","LESSON"],  // 154 · Jun 3
  ["CREAK","WEAR","SIGHT","CENT","PEEK"],  // 155 · Jun 4
  ["PAUSE","FLEW","EIGHT","BREAK","DEER"],  // 156 · Jun 5
  ["CHEWS","WEIGH","MAZE","TIDE","BUY"],  // 157 · Jun 6
  ["PRAY","HORSE","NONE","PAIR","SAIL"],  // 158 · Jun 7
  ["WEAR","DIE","STAIR","STEAL","PLAIN"],  // 159 · Jun 8
  ["PEACE","FLOUR","BEAN","SIGHT","BOARD"],  // 160 · Jun 9
  ["TOAD","HAIR","TOE","KNEAD","RIGHT"],  // 161 · Jun 10
  ["RING","GRATE","CREAK","HEARD","VAIN"],  // 162 · Jun 11
  ["SOAR","BARE","MUSCLE","BOUGH","HEAL"],  // 163 · Jun 12
  ["HOLE","BLUE","IDLE","THRONE","ROAD"],  // 164 · Jun 13
  ["SON","WAIT","ONE","GUEST","SUITE"],  // 165 · Jun 14
  ["KNOT","WAIST","YOLK","SEE","ALLOWED"],  // 166 · Jun 15
  ["KNEW","CENT","LOAN","SCENE","FEAT"],  // 167 · Jun 16
  ["MAIL","SOLE","STEAK","WEEK","HOUR"],  // 168 · Jun 17
  ["PALE","FAIR","GROAN","WAIVE","FLEA"],  // 169 · Jun 18
  ["MEAT","TAIL","RAIN","HIGHER","WOOD"],  // 170 · Jun 19
  ["CELL","LESSON","SEAM","BEACH","MANE"],  // 171 · Jun 20
  ["KNIGHT","ROSE","WHALE","LEAK","MISSED"],  // 172 · Jun 21
  ["WOOD","HAIR","CELL","PAIR","FEAT"],  // 173 · Jun 22
  ["SUITE","BEAN","HORSE","KNOT","MISSED"],  // 174 · Jun 23
  ["SON","DEER","WEIGH","RAIN","CENT"],  // 175 · Jun 24
  ["WAIST","STAIR","SAIL","BUY","KNIGHT"],  // 176 · Jun 25
  ["MANE","RING","NONE","STEAL","ROAD"],  // 177 · Jun 26
  ["HOLE","KNEW","SCENE","WEEK","HIGHER"],  // 178 · Jun 27
  ["GUEST","WEAR","MEAT","RIGHT","YOLK"],  // 179 · Jun 28
  ["MAIL","CHEWS","PRAY","SEE","ROSE"],  // 180 · Jun 29
  ["DIE","HEARD","PEACE","FLEA","BLUE"],  // 181 · Jun 30
  ["PLAIN","SEAM","FLOUR","TAIL","EIGHT"],  // 182 · Jul 1
  ["SIGHT","BEACH","LOAN","WAIVE","HEAL"],  // 183 · Jul 2
  ["PEEK","LEAK","MUSCLE","BREAK","STEAK"],  // 184 · Jul 3
  ["LESSON","FLEW","SOLE","ALLOWED","ONE"],  // 185 · Jul 4
  ["FAIR","GRATE","PALE","BOARD","WHALE"],  // 186 · Jul 5
  ["KNEAD","HOUR","TIDE","IDLE","WAIT"],  // 187 · Jul 6
  ["VAIN","PAUSE","GROAN","TOE","BARE"],  // 188 · Jul 7
  ["THRONE","CREAK","MAZE","BOUGH","SOAR"],  // 189 · Jul 8
  ["TOAD","WAIVE","SCENE","HEAL","PRAY"],  // 190 · Jul 9
  ["PAUSE","DIE","WEEK","SON","GUEST"],  // 191 · Jul 10
  ["WHALE","TAIL","BOARD","ROSE","BOUGH"],  // 192 · Jul 11
  ["THRONE","RIGHT","HOLE","PAIR","CENT"],  // 193 · Jul 12
  ["MEAT","STEAK","MANE","HIGHER","WEIGH"],  // 194 · Jul 13
  ["YOLK","BREAK","MISSED","DEER","KNEW"],  // 195 · Jul 14
  ["RING","SAIL","FLEA","WOOD","KNIGHT"],  // 196 · Jul 15
  ["SOLE","ONE","SUITE","FLEW","SIGHT"],  // 197 · Jul 16
  ["HOUR","IDLE","SEE","STAIR","PEACE"],  // 198 · Jul 17
  ["PLAIN","PEEK","FAIR","ROAD","WAIT"],  // 199 · Jul 18
  ["LESSON","VAIN","LOAN","KNEAD","FLOUR"],  // 200 · Jul 19
  ["WAIST","ALLOWED","CELL","SEAM","HORSE"],  // 201 · Jul 20
  ["EIGHT","HAIR","WEAR","CHEWS","CREAK"],  // 202 · Jul 21
  ["TIDE","HEARD","TOE","TOAD","STEAL"],  // 203 · Jul 22
  ["PALE","BEACH","BUY","MAZE","GRATE"],  // 204 · Jul 23
  ["FEAT","MAIL","SOAR","RAIN","KNOT"],  // 205 · Jul 24
  ["NONE","BEAN","BARE","MUSCLE","BLUE"],  // 206 · Jul 25
  ["LEAK","GROAN","BEACH","TOAD","FAIR"],  // 207 · Jul 26
  ["PAIR","ONE","CREAK","ROSE","WAIVE"],  // 208 · Jul 27
  ["MAIL","BOARD","SON","WEAR","NONE"],  // 209 · Jul 28
  ["SEE","WHALE","TOE","GUEST","MAZE"],  // 210 · Jul 29
  ["SUITE","HEAL","WAIT","IDLE","PAUSE"],  // 211 · Jul 30
  ["WEEK","BLUE","PEEK","EIGHT","VAIN"],  // 212 · Jul 31
  ["BARE","FLOUR","SIGHT","DEER","CHEWS"],  // 213 · Aug 1
  ["BREAK","HIGHER","HOLE","KNEAD","CELL"],  // 214 · Aug 2
  ["SAIL","FEAT","ROAD","PALE","LEAK"],  // 215 · Aug 3
  ["MEAT","RING","HORSE","SOLE","PEACE"],  // 216 · Aug 4
  ["STEAK","BUY","RAIN","CENT","GROAN"],  // 217 · Aug 5
  ["THRONE","KNIGHT","WAIST","SCENE","TIDE"],  // 218 · Aug 6
  ["STAIR","SEAM","YOLK","KNOT","LESSON"],  // 219 · Aug 7
  ["BOUGH","WOOD","MANE","SOAR","BEAN"],  // 220 · Aug 8
  ["HAIR","HEARD","RIGHT","GRATE","HOUR"],  // 221 · Aug 9
  ["WEIGH","LOAN","STEAL","DIE","PLAIN"],  // 222 · Aug 10
  ["MISSED","ALLOWED","KNEW","PRAY","TAIL"],  // 223 · Aug 11
  ["FLEW","MUSCLE","FLEA","STEAK","EIGHT"],  // 224 · Aug 12
  ["PAIR","BLUE","CENT","MUSCLE","PAUSE"],  // 225 · Aug 13
  ["PEEK","FLEA","FEAT","ROAD","DIE"],  // 226 · Aug 14
  ["BARE","HORSE","STEAL","SAIL","LOAN"],  // 227 · Aug 15
  ["SUITE","THRONE","WAIT","FAIR","WAIST"],  // 228 · Aug 16
  ["CREAK","PALE","CELL","KNIGHT","KNEW"],  // 229 · Aug 17
  ["SEE","FLEW","BOUGH","WHALE","HOLE"],  // 230 · Aug 18
  ["HAIR","BEAN","SEAM","PEACE","KNEAD"],  // 231 · Aug 19
  ["TOAD","MAIL","TAIL","WAIVE","HOUR"],  // 232 · Aug 20
  ["HIGHER","PRAY","SOLE","RIGHT","SON"],  // 233 · Aug 21
  ["ONE","GROAN","VAIN","MANE","WOOD"],  // 234 · Aug 22
  ["WEIGH","SIGHT","BREAK","MEAT","GUEST"],  // 235 · Aug 23
  ["SCENE","SOAR","BUY","PLAIN","BOARD"],  // 236 · Aug 24
  ["DEER","NONE","IDLE","CHEWS","GRATE"],  // 237 · Aug 25
  ["KNOT","RING","MAZE","WEEK","HEAL"],  // 238 · Aug 26
  ["BEACH","LESSON","LEAK","FLOUR","ROSE"],  // 239 · Aug 27
  ["TIDE","WEAR","RAIN","TOE","STAIR"],  // 240 · Aug 28
  ["ALLOWED","HEARD","MISSED","YOLK","SEE"],  // 241 · Aug 29
  ["WEEK","IDLE","PLAIN","BEACH","SOAR"],  // 242 · Aug 30
  ["ALLOWED","ONE","GROAN","WAIT","SUITE"],  // 243 · Aug 31
  ["BEAN","VAIN","DEER","BOARD","HEAL"],  // 244 · Sep 1
  ["STAIR","STEAL","MANE","BARE","MAZE"],  // 245 · Sep 2
  ["SEAM","BOUGH","THRONE","GRATE","TOE"],  // 246 · Sep 3
  ["PAIR","WAIST","HIGHER","CREAK","CELL"],  // 247 · Sep 4
  ["SON","RING","STEAK","RIGHT","PEEK"],  // 248 · Sep 5
  ["HOUR","LOAN","KNOT","SAIL","BUY"],  // 249 · Sep 6
  ["MAIL","TOAD","PEACE","CHEWS","GUEST"],  // 250 · Sep 7
  ["ROSE","LEAK","PAUSE","MUSCLE","HEARD"],  // 251 · Sep 8
  ["WHALE","SIGHT","KNEAD","ROAD","FLEW"],  // 252 · Sep 9
  ["WEIGH","WEAR","PRAY","YOLK","DIE"],  // 253 · Sep 10
  ["MEAT","WOOD","TAIL","TIDE","KNEW"],  // 254 · Sep 11
  ["RAIN","KNIGHT","WAIVE","FLOUR","FAIR"],  // 255 · Sep 12
  ["CENT","MISSED","HORSE","HAIR","NONE"],  // 256 · Sep 13
  ["SCENE","FEAT","BLUE","PALE","FLEA"],  // 257 · Sep 14
  ["BREAK","LESSON","SOLE","HOLE","EIGHT"],  // 258 · Sep 15
  ["BOUGH","FLOUR","PRAY","HEAL","WHALE"],  // 259 · Sep 16
  ["BREAK","GROAN","WOOD","FAIR","GRATE"],  // 260 · Sep 17
  ["FEAT","MEAT","PEACE","CHEWS","MUSCLE"],  // 261 · Sep 18
  ["YOLK","FLEW","SAIL","ALLOWED","RAIN"],  // 262 · Sep 19
  ["GUEST","ONE","PAIR","STEAL","KNEW"],  // 263 · Sep 20
  ["SOLE","HAIR","LESSON","TAIL","WEIGH"],  // 264 · Sep 21
  ["SCENE","CREAK","HIGHER","HOLE","PLAIN"],  // 265 · Sep 22
  ["LEAK","THRONE","TOAD","WEEK","TIDE"],  // 266 · Sep 23
  ["NONE","MAZE","DEER","BOARD","WEAR"],  // 267 · Sep 24
  ["WAIT","IDLE","EIGHT","HEARD","STEAK"],  // 268 · Sep 25
  ["PEEK","TOE","HOUR","LOAN","SON"],  // 269 · Sep 26
  ["CELL","SIGHT","BUY","SUITE","FLEA"],  // 270 · Sep 27
  ["SOAR","PAUSE","ROSE","STAIR","BEAN"],  // 271 · Sep 28
  ["DIE","PALE","KNOT","ROAD","SEE"],  // 272 · Sep 29
  ["BLUE","VAIN","RING","WAIST","MAIL"],  // 273 · Sep 30
  ["SEAM","HORSE","CENT","MISSED","KNIGHT"],  // 274 · Oct 1
  ["RIGHT","BARE","BEACH","WAIVE","MANE"],  // 275 · Oct 2
  ["KNEAD","PRAY","STEAK","FLOUR","RING"],  // 276 · Oct 3
  ["SEE","PAUSE","CELL","MAIL","ROAD"],  // 277 · Oct 4
  ["BARE","IDLE","SUITE","BOARD","BLUE"],  // 278 · Oct 5
  ["GROAN","WAIT","LEAK","CREAK","TAIL"],  // 279 · Oct 6
  ["FLEW","TIDE","HEARD","BEACH","STAIR"],  // 280 · Oct 7
  ["GUEST","YOLK","THRONE","FLEA","MANE"],  // 281 · Oct 8
  ["WEIGH","MISSED","SOAR","WEEK","WAIST"],  // 282 · Oct 9
  ["MUSCLE","MEAT","LINKS","SEE","STATIONARY"],  // 283 · Oct 10
  ["CEREAL","BEACH","ALTAR","ROAD","GENES"],  // 284 · Oct 11
  ["BLUE","THYME","TAUGHT","DEER","PEAL"],  // 285 · Oct 12
  ["BRIDAL","DIE","MOAN","EARN","VAIN"],  // 286 · Oct 13
  ["RYE","BUY","LEASED","WOOD","FLOE"],  // 287 · Oct 14
  ["HEAL","FORTH","PEDAL","SOARED","STATIONARY"],  // 288 · Oct 15
  ["WEAR","PATIENCE","BAND","QUARTS","FLEW"],  // 289 · Oct 16
  ["LOCKS","TEAM","PORE","MAID","NONE"],  // 290 · Oct 17
  ["HEARD","DAYS","MEDAL","KNOT","RAISE"],  // 291 · Oct 18
  ["PLAIN","SOLE","PAUSE","NAY","ROLE"],  // 292 · Oct 19
  ["CREWS","KNEW","BEAT","DISCREET","WEIGH"],  // 293 · Oct 20
  ["HEIR","OVERDO","RAIN","COUNCIL","SUMMARY"],  // 294 · Oct 21
  ["FRIAR","TRACKED","FLAIR","REAL","FIR"],  // 295 · Oct 22
  ["GILT","BERTH","MOOSE","SERF","PEER"],  // 296 · Oct 23
  ["WHALE","GRATE","BREAK","CACHE","MALL"],  // 297 · Oct 24
  ["WEEK","SCENE","SUITE","STAIR","CEILING"],  // 298 · Oct 25
  ["SIGHT","HORSE","TOLD","MAZE","GAIT"],  // 299 · Oct 26
  ["LOAN","SLAY","MEAT","CENT","TERN"],  // 300 · Oct 27
  ["POLE","BOAR","HYMN","ALLOWED","VIAL"],  // 301 · Oct 28
  ["PALE","MAIL","STEAK","PAIR","YOLK"],  // 302 · Oct 29
  ["BALL","WHIRLED","FAINT","WEATHER","MANE"],  // 303 · Oct 30
  ["FOUL","BOARD","KNIGHT","EWE","KNEAD"],  // 304 · Oct 31
  ["HOARD","PASSED","MINER","PRAY","HEW"],  // 305 · Nov 1
  ["CLAUSE","PEEK","SEE","COARSE","DUAL"],  // 306 · Nov 2
  ["CORE","MUSCLE","BEAN","PRESENCE","HOLE"],  // 307 · Nov 3
  ["CHUTE","SLEIGHT","TAIL","SEW","BERRY"],  // 308 · Nov 4
  ["TOAD","BOUGH","IDLE","DOE","KNOWS"],  // 309 · Nov 5
  ["MISSED","CREAK","TOE","CHEWS","OAR"],  // 310 · Nov 6
  ["WADE","GORILLA","LIAR","SON","KERNEL"],  // 311 · Nov 7
  ["BOULDER","HALL","FLEA","MIGHT","SEAS"],  // 312 · Nov 8
  ["TACKS","CANVAS","CELL","SUNDAE","GUEST"],  // 313 · Nov 9
  ["BAZAAR","PAIN","AISLE","PROFIT","BREAD"],  // 314 · Nov 10
  ["STEAL","HOUR","LOOT","GROAN","WAIT"],  // 315 · Nov 11
  ["SOAR","THRONE","DEW","HANGAR","HAIR"],  // 316 · Nov 12
  ["ROSE","RING","PLUM","LINKS","HEIR"],  // 317 · Nov 13
  ["BLUE","DEW","THRONE","BALL","MUSCLE"],  // 318 · Nov 14
  ["TEAM","OVERDO","NAVAL","PROFIT","DUAL"],  // 319 · Nov 15
  ["KNIGHT","SEAS","KNOWS","CREWS","HANGAR"],  // 320 · Nov 16
  ["IDLE","BOULDER","FLEW","ROSE","STEAK"],  // 321 · Nov 17
  ["ROAD","NONE","ALLOWED","WEIGH","DOE"],  // 322 · Nov 18
  ["HOLE","CHORD","GILT","WEEK","CEREAL"],  // 323 · Nov 19
  ["KNEAD","REAL","PAUSE","TOLD","WOOD"],  // 324 · Nov 20
  ["BAIL","FRIAR","FLAIR","MANE","HYMN"],  // 325 · Nov 21
  ["FAINT","ALTAR","PALE","SOARED","MAIL"],  // 326 · Nov 22
  ["HEW","SEE","WEATHER","CELL","BREAD"],  // 327 · Nov 23
  ["PEDAL","BERRY","COUNCIL","HEARD","WHALE"],  // 328 · Nov 24
  ["RAP","EIGHT","SCENE","LINKS","FLOUR"],  // 329 · Nov 25
  ["RAIN","HORSE","PRINCIPAL","HOARD","THYME"],  // 330 · Nov 26
  ["TERN","PEACE","MEAT","RYE","HAIR"],  // 331 · Nov 27
  ["KNOT","SLAY","PALATE","MEDAL","TAIL"],  // 332 · Nov 28
  ["PEER","SEAM","TIDE","PAIN","PASSED"],  // 333 · Nov 29
  ["QUARTS","AISLE","CANVAS","CENT","MAZE"],  // 334 · Nov 30
  ["OAR","WADE","BREAK","PEEK","WAIST"],  // 335 · Dec 1
  ["YOLK","RIGHT","MINER","HIGHER","ONE"],  // 336 · Dec 2
  ["BOAR","STEPPE","RING","CARAT","SUMMARY"],  // 337 · Dec 3
  ["CHEWS","SAIL","GRISLY","BUY","CYMBAL"],  // 338 · Dec 4
  ["STATIONARY","FORTH","FIR","BEAN","WAIT"],  // 339 · Dec 5
  ["VAIN","SHEAR","BEACH","CACHE","BOARD"],  // 340 · Dec 6
  ["BEAT","STRAIGHT","SUNDAE","GENES","SON"],  // 341 · Dec 7
  ["VIAL","PEAL","POLE","TOAD","TAUGHT"],  // 342 · Dec 8
  ["MANNER","GORILLA","FOUL","NAY","MISSED"],  // 343 · Dec 9
  ["LOCKS","PATIENCE","BAND","ROLE","FLEA"],  // 344 · Dec 10
  ["BARE","CEILING","TRACKED","GRATE","LIAR"],  // 345 · Dec 11
  ["HOUR","MIGHT","STEAL","PAIR","GUEST"],  // 346 · Dec 12
  ["HEAL","PRESENCE","WEAR","DISCREET","FEAT"],  // 347 · Dec 13
  ["BAZAAR","LOAN","EWE","DEER","FLOE"],  // 348 · Dec 14
  ["CHUTE","COARSE","WHIRLED","SUITE","CREAK"],  // 349 · Dec 15
  ["SOLE","MOOSE","MALL","SLEIGHT","CLAUSE"],  // 350 · Dec 16
  ["BOUGH","SIGHT","TACKS","KERNEL","PLUM"],  // 351 · Dec 17
  ["WAIVE","EARN","GROAN","KNEW","STAIR"],  // 352 · Dec 18
  ["SOAR","CORE","BRIDAL","LEASED","RAISE"],  // 353 · Dec 19
  ["GAIT","LEAK","PRAY","HALL","TOE"],  // 354 · Dec 20
  ["LOOT","BERTH","PLAIN","LESSON","FAIR"],  // 355 · Dec 21
  ["PORE","MAID","SEW","DIE","MOAN"],  // 356 · Dec 22
  ["SERF","DAYS","HOARD","ALLOWED","OVERDO"],  // 357 · Dec 23
  ["BAZAAR","HIGHER","DAYS","LIAR","MIGHT"],  // 358 · Dec 24
  ["BOULDER","MAZE","PAIN","NAVAL","CELL"],  // 359 · Dec 25
  ["STATIONARY","NAY","QUARTS","HEIR","PALATE"],  // 360 · Dec 26
  ["KNEAD","EARN","KNOT","BAND","BARE"],  // 361 · Dec 27
  ["SEAM","ROSE","MAIL","TAIL","MUSCLE"],  // 362 · Dec 28
  ["MANNER","MALL","WOOD","HEAL","WEATHER"],  // 363 · Dec 29
  ["CREAK","COARSE","SOAR","HALL","MISSED"],  // 364 · Dec 30
  ["PRAY","IDLE","FRIAR","CHEWS","TEAM"]  // 365 · Dec 31
];
