// Soundalike puzzles.
//
// Each puzzle has:
//   clues   - two clues
//   answers - two words, in the same order, that sound the same but are spelled differently.
//
// Every game picks five of these at random. All puzzles must be original.

window.SOUNDALIKE_PUZZLES = [
  { clues: ["Two of something", "A juicy fruit"], answers: ["PAIR", "PEAR"] },
  { clues: ["Ground wheat for baking", "A bloom"], answers: ["FLOUR", "FLOWER"] },
  { clues: ["He wears armour", "When the stars are out"], answers: ["KNIGHT", "NIGHT"] },
  { clues: ["It catches the wind", "Prices marked down"], answers: ["SAIL", "SALE"] },
  { clues: ["Letters and parcels", "Not female"], answers: ["MAIL", "MALE"] },
  { clues: ["Where a belt sits", "Rubbish"], answers: ["WAIST", "WASTE"] },
  { clues: ["To take what is not yours", "A strong metal"], answers: ["STEAL", "STEEL"] },
  { clues: ["Seven days", "Not strong"], answers: ["WEEK", "WEAK"] },
  { clues: ["An opening", "Entire"], answers: ["HOLE", "WHOLE"] },
  { clues: ["Correct", "To put words on paper"], answers: ["RIGHT", "WRITE"] },
  { clues: ["To use your eyes", "The ocean"], answers: ["SEE", "SEA"] },
  { clues: ["A male child", "It rises in the morning"], answers: ["SON", "SUN"] },
  { clues: ["It grows on your head", "A long-eared animal like a big rabbit"], answers: ["HAIR", "HARE"] },
  { clues: ["Calm, with no war", "A part of something"], answers: ["PEACE", "PIECE"] },
  { clues: ["The colour of the sky", "What the wind did"], answers: ["BLUE", "BLEW"] },
  { clues: ["Cars drive on it", "Sat on a horse, in the past"], answers: ["ROAD", "RODE"] },
  { clues: ["A woodland animal with antlers", "How a letter starts"], answers: ["DEER", "DEAR"] },
  { clues: ["Travelled by plane, in the past", "A winter illness"], answers: ["FLEW", "FLU"] },
  { clues: ["To stay until something happens", "What scales measure"], answers: ["WAIT", "WEIGHT"] },
  { clues: ["Uncovered", "A big furry animal"], answers: ["BARE", "BEAR"] },
  { clues: ["Beef or pork", "To come together"], answers: ["MEAT", "MEET"] },
  { clues: ["A dog wags it", "A story"], answers: ["TAIL", "TALE"] },
  { clues: ["It falls from clouds", "A king's time on the throne"], answers: ["RAIN", "REIGN"] },
  { clues: ["To snap in two", "It slows a car"], answers: ["BREAK", "BRAKE"] },
  { clues: ["Simple", "It flies"], answers: ["PLAIN", "PLANE"] },
  { clues: ["To get better after an injury", "The back of your foot"], answers: ["HEAL", "HEEL"] },
  { clues: ["A single thing", "Came first in a race"], answers: ["ONE", "WON"] },
  { clues: ["Twice four", "Had a meal, in the past"], answers: ["EIGHT", "ATE"] },
  { clues: ["A tangle in a rope", "A word that says no"], answers: ["KNOT", "NOT"] },
  { clues: ["Sixty minutes", "Belonging to us"], answers: ["HOUR", "OUR"] },
  { clues: ["Sand by the sea", "A tree with smooth grey bark"], answers: ["BEACH", "BEECH"] },
  { clues: ["Trees are made of it", "Was willing to"], answers: ["WOOD", "WOULD"] },
  { clues: ["The bottom of a shoe", "A person's spirit"], answers: ["SOLE", "SOUL"] },
  { clues: ["A king's seat", "Tossed through the air"], answers: ["THRONE", "THROWN"] },
  { clues: ["To shred cheese", "Very good"], answers: ["GRATE", "GREAT"] },
  { clues: ["A flat length of wood", "Having nothing to do"], answers: ["BOARD", "BORED"] },
  { clues: ["A prisoner's room", "To exchange for money"], answers: ["CELL", "SELL"] },
  { clues: ["Just and honest", "The price of a bus ticket"], answers: ["FAIR", "FARE"] },
  { clues: ["Was aware of", "Not old"], answers: ["KNEW", "NEW"] },
  { clues: ["A puzzle of hedges", "Corn"], answers: ["MAZE", "MAIZE"] },
  { clues: ["A thorny flower", "Lines of seats"], answers: ["ROSE", "ROWS"] },
  { clues: ["A foot has five", "To pull a car with a rope"], answers: ["TOE", "TOW"] },
  { clues: ["To stop living", "To colour cloth"], answers: ["DIE", "DYE"] },
  { clues: ["You can ride it", "Rough-voiced from a cold"], answers: ["HORSE", "HOARSE"] },
  { clues: ["The biggest sea animal", "A long sad cry"], answers: ["WHALE", "WAIL"] },
  { clues: ["To purchase", "Said when leaving"], answers: ["BUY", "BYE"] },
  { clues: ["Where two pieces of cloth are stitched", "To appear to be"], answers: ["SEAM", "SEEM"] },
  { clues: ["A lion's long hair", "The most important"], answers: ["MANE", "MAIN"] },
  { clues: ["Baked, on toast", "Past form of to be"], answers: ["BEAN", "BEEN"] },
  { clues: ["Permitted", "Out loud, not silently"], answers: ["ALLOWED", "ALOUD"] },
  { clues: ["A short break", "A cat's feet"], answers: ["PAUSE", "PAWS"] },
  { clues: ["A set of hotel rooms", "Sugary"], answers: ["SUITE", "SWEET"] },
  { clues: ["One step of a staircase", "To look hard and long"], answers: ["STAIR", "STARE"] },
  { clues: ["To have on, as clothes", "In what place"], answers: ["WEAR", "WHERE"] },
  { clues: ["A daring deed", "You stand on them"], answers: ["FEAT", "FEET"] },
  { clues: ["Took in with the ears", "A group of cattle"], answers: ["HEARD", "HERD"] },
  { clues: ["Borrowed money", "Single, with no others"], answers: ["LOAN", "LONE"] },
  { clues: ["Light in colour", "A bucket"], answers: ["PALE", "PAIL"] },
  { clues: ["Part of a play", "Looked at, in the past"], answers: ["SCENE", "SEEN"] },
  { clues: ["A cut of beef", "A wooden post"], answers: ["STEAK", "STAKE"] },
  { clues: ["The sea's daily rise and fall", "Fastened with a knot"], answers: ["TIDE", "TIED"] },
  { clues: ["To find how heavy something is", "A route"], answers: ["WEIGH", "WAY"] },
  { clues: ["Grinds with the teeth", "To pick"], answers: ["CHEWS", "CHOOSE"] },
  { clues: ["A tiny jumping pest", "To run away"], answers: ["FLEA", "FLEE"] },
  { clues: ["A sound of pain", "Fully developed"], answers: ["GROAN", "GROWN"] },
  { clues: ["Further up", "To give someone a job"], answers: ["HIGHER", "HIRE"] },
  { clues: ["Doing nothing", "A worshipped star"], answers: ["IDLE", "IDOL"] },
  { clues: ["A drip through a hole", "A long green onion"], answers: ["LEAK", "LEEK"] },
  { clues: ["Failed to hit", "Thin fog"], answers: ["MISSED", "MIST"] },
  { clues: ["It moves your bones", "A shellfish with a blue-black shell"], answers: ["MUSCLE", "MUSSEL"] },
  { clues: ["Not any", "A woman in a convent"], answers: ["NONE", "NUN"] },
  { clues: ["A quick look", "The top of a mountain"], answers: ["PEEK", "PEAK"] },
  { clues: ["To speak to a god", "An animal that is hunted"], answers: ["PRAY", "PREY"] },
  { clues: ["Worn on a finger", "To twist water out of a cloth"], answers: ["RING", "WRING"] },
  { clues: ["The sense of seeing", "A place where something is built"], answers: ["SIGHT", "SITE"] },
  { clues: ["To fly high", "Painful"], answers: ["SOAR", "SORE"] },
  { clues: ["A warty amphibian", "Pulled along by a rope"], answers: ["TOAD", "TOWED"] },
  { clues: ["Full of self-admiration", "It carries blood to the heart"], answers: ["VAIN", "VEIN"] },
  { clues: ["To give up a right", "What the sea does"], answers: ["WAIVE", "WAVE"] },
  { clues: ["The yellow of an egg", "A wooden bar across two oxen"], answers: ["YOLK", "YOKE"] },
  { clues: ["A big tree branch", "To bend at the waist"], answers: ["BOUGH", "BOW"] },
  { clues: ["One hundredth of a dollar", "A smell"], answers: ["CENT", "SCENT"] },
  { clues: ["The squeak of an old door", "A small stream"], answers: ["CREAK", "CREEK"] },
  { clues: ["A visitor", "Made a lucky estimate"], answers: ["GUEST", "GUESSED"] },
  { clues: ["To work dough with your hands", "To require"], answers: ["KNEAD", "NEED"] },
  { clues: ["A class at school", "To make smaller"], answers: ["LESSON", "LESSEN"] }
];
