// Mash-Ups puzzles.
//
// Each puzzle has:
//   clues  - two clues, one for each word
//   parts  - the two words, in capitals. The end of the first must match the start of
//            the second (DRUM and UMBRELLA share "UM").
//   answer - the two words blended into one where they overlap (DRUMBRELLA)
//
// Every game picks five of these at random. All puzzles must be original.

window.MASH_UPS_PUZZLES = [
  { clues: ["You hit it with sticks", "It keeps the rain off"], parts: ["DRUM", "UMBRELLA"], answer: "DRUMBRELLA" },
  { clues: ["A big cousin of the violin, played seated", "Seafood with claws"], parts: ["CELLO", "LOBSTER"], answer: "CELLOBSTER" },
  { clues: ["It has 88 keys", "A long work of fiction"], parts: ["PIANO", "NOVEL"], answer: "PIANOVEL" },
  { clues: ["A red salad fruit", "A warty amphibian"], parts: ["TOMATO", "TOAD"], answer: "TOMATOAD" },
  { clues: ["A yellow fruit you peel", "She minds the children"], parts: ["BANANA", "NANNY"], answer: "BANANANNY" },
  { clues: ["A black and white bear", "A small white flower"], parts: ["PANDA", "DAISY"], answer: "PANDAISY" },
  { clues: ["It hops and has a pouch", "It crows at dawn"], parts: ["KANGAROO", "ROOSTER"], answer: "KANGAROOSTER" },
  { clues: ["A six-string instrument", "A Scottish checked cloth"], parts: ["GUITAR", "TARTAN"], answer: "GUITARTAN" },
  { clues: ["An orange root vegetable", "A big black-and-tan guard dog"], parts: ["CARROT", "ROTTWEILER"], answer: "CARROTTWEILER" },
  { clues: ["A big orange squash", "To light a fire"], parts: ["PUMPKIN", "KINDLE"], answer: "PUMPKINDLE" },
  { clues: ["A machine that does tasks for you", "Milk comes in one"], parts: ["ROBOT", "BOTTLE"], answer: "ROBOTTLE" },
  { clues: ["A pink fish that swims upstream", "It swings through the trees"], parts: ["SALMON", "MONKEY"], answer: "SALMONKEY" },
  { clues: ["A nut in a hard, wrinkled shell", "A spice grated onto eggnog"], parts: ["WALNUT", "NUTMEG"], answer: "WALNUTMEG" },
  { clues: ["A spring flower from Holland", "Red colour for your mouth"], parts: ["TULIP", "LIPSTICK"], answer: "TULIPSTICK" },
  { clues: ["A spiky desert plant", "An elephant's long tooth"], parts: ["CACTUS", "TUSK"], answer: "CACTUSK" },
  { clues: ["A brass instrument", "Part of a flower"], parts: ["TRUMPET", "PETAL"], answer: "TRUMPETAL" },
  { clues: ["A bird with a pouch under its beak", "Wax with a wick"], parts: ["PELICAN", "CANDLE"], answer: "PELICANDLE" },
  { clues: ["A talking bird", "To turn around"], parts: ["PARROT", "ROTATE"], answer: "PARROTATE" },
  { clues: ["A desert animal with humps", "A big juicy fruit"], parts: ["CAMEL", "MELON"], answer: "CAMELON" },
  { clues: ["A striped big cat", "A small pet rodent"], parts: ["TIGER", "GERBIL"], answer: "TIGERBIL" },
  { clues: ["A sour yellow fruit", "A scary creature"], parts: ["LEMON", "MONSTER"], answer: "LEMONSTER" },
  { clues: ["A griddled breakfast cake with squares", "A sheep's woolly coat"], parts: ["WAFFLE", "FLEECE"], answer: "WAFFLEECE" },
  { clues: ["A couch", "A tiny magical being with wings"], parts: ["SOFA", "FAIRY"], answer: "SOFAIRY" },
  { clues: ["A peppery red root", "It cleans the plates"], parts: ["RADISH", "DISHWASHER"], answer: "RADISHWASHER" },
  { clues: ["A tropical orange fruit", "A mischievous ugly creature"], parts: ["MANGO", "GOBLIN"], answer: "MANGOBLIN" },
  { clues: ["It drives in nails", "Half woman, half fish"], parts: ["HAMMER", "MERMAID"], answer: "HAMMERMAID" },
  { clues: ["Played with a bow", "A flat pasta ribbon"], parts: ["VIOLIN", "LINGUINE"], answer: "VIOLINGUINE" },
  { clues: ["A cucumber kept in brine", "A big-eyed primate from Madagascar"], parts: ["PICKLE", "LEMUR"], answer: "PICKLEMUR" },
  { clues: ["It fastens a shirt", "You taste with it"], parts: ["BUTTON", "TONGUE"], answer: "BUTTONGUE" },
  { clues: ["It covers the floor", "A trumpet-shaped garden flower"], parts: ["CARPET", "PETUNIA"], answer: "CARPETUNIA" },
  { clues: ["A horned animal with thick skin", "A long pasta strand"], parts: ["RHINO", "NOODLE"], answer: "RHINOODLE" },
  { clues: ["A big ape", "A woolly South American animal"], parts: ["GORILLA", "LLAMA"], answer: "GORILLAMA" },
  { clues: ["It lays eggs", "A dog's little house"], parts: ["CHICKEN", "KENNEL"], answer: "CHICKENNEL" },
  { clues: ["A bushy-tailed nut collector", "A tangy sauce for hot dogs"], parts: ["SQUIRREL", "RELISH"], answer: "SQUIRRELISH" },
  { clues: ["A wrapped head covering", "A twangy stringed instrument"], parts: ["TURBAN", "BANJO"], answer: "TURBANJO" },
  { clues: ["A round leafy vegetable", "A spy"], parts: ["CABBAGE", "AGENT"], answer: "CABBAGENT" },
  { clues: ["A small cake baked in a paper cup", "A small songbird"], parts: ["MUFFIN", "FINCH"], answer: "MUFFINCH" },
  { clues: ["A dam-building rodent", "A covered porch"], parts: ["BEAVER", "VERANDA"], answer: "BEAVERANDA" },
  { clues: ["A striped horse", "A shout of praise"], parts: ["ZEBRA", "BRAVO"], answer: "ZEBRAVO" },
  { clues: ["A hard hat for a cyclist", "It ticks a steady beat for musicians"], parts: ["HELMET", "METRONOME"], answer: "HELMETRONOME" },
  { clues: ["A long-eared farm animal", "You type on it"], parts: ["DONKEY", "KEYBOARD"], answer: "DONKEYBOARD" },
  { clues: ["A root vegetable for chips", "It browns bread"], parts: ["POTATO", "TOASTER"], answer: "POTATOASTER" },
  { clues: ["An open summer shoe", "A spotted dog"], parts: ["SANDAL", "DALMATIAN"], answer: "SANDALMATIAN" },
  { clues: ["A spice that makes you sneeze", "A sweet-smelling scent"], parts: ["PEPPER", "PERFUME"], answer: "PEPPERFUME" },
  { clues: ["A hairy tropical nut", "A tool for opening nuts, or a ballet"], parts: ["COCONUT", "NUTCRACKER"], answer: "COCONUTCRACKER" },
  { clues: ["You dry off with it", "A friendly greeting"], parts: ["TOWEL", "WELCOME"], answer: "TOWELCOME" },
  { clues: ["It takes photographs", "It rubs out pencil marks"], parts: ["CAMERA", "ERASER"], answer: "CAMERASER" },
  { clues: ["A whining, biting insect", "A chewy brown sweet"], parts: ["MOSQUITO", "TOFFEE"], answer: "MOSQUITOFFEE" },
  { clues: ["A tusked Arctic sea animal", "Covered in orange flakes of corrosion"], parts: ["WALRUS", "RUSTY"], answer: "WALRUSTY" },
  { clues: ["A large stinging wasp", "A plant that stings"], parts: ["HORNET", "NETTLE"], answer: "HORNETTLE" },
  { clues: ["A snapping river reptile", "A tricky choice"], parts: ["CROCODILE", "DILEMMA"], answer: "CROCODILEMMA" },
  { clues: ["A big shaggy prairie animal", "A spiky plant with soothing gel"], parts: ["BUFFALO", "ALOE"], answer: "BUFFALOE" },
  { clues: ["A leafy green that made a sailor strong", "A dull pain"], parts: ["SPINACH", "ACHE"], answer: "SPINACHE" },
  { clues: ["It floats and pops", "Canada's one-dollar coin"], parts: ["BALLOON", "LOONIE"], answer: "BALLOONIE" },
  { clues: ["A fish that comes in cans", "It wipes your mouth at dinner"], parts: ["TUNA", "NAPKIN"], answer: "TUNAPKIN" },
  { clues: ["A space rock with a glowing tail", "Iron or gold"], parts: ["COMET", "METAL"], answer: "COMETAL" },
  { clues: ["You stay there on holiday", "It brings the stars closer"], parts: ["HOTEL", "TELESCOPE"], answer: "HOTELESCOPE" },
  { clues: ["A playful river animal", "A raised outdoor patio"], parts: ["OTTER", "TERRACE"], answer: "OTTERRACE" },
  { clues: ["The tallest animal", "Fondness"], parts: ["GIRAFFE", "AFFECTION"], answer: "GIRAFFECTION" },
  { clues: ["Soft chewy toffee", "A tune"], parts: ["CARAMEL", "MELODY"], answer: "CARAMELODY" },
  { clues: ["A seabird with a colourful beak", "To end"], parts: ["PUFFIN", "FINISH"], answer: "PUFFINISH" }
];
