// Daily puzzle schedule for 2026. Made by: node tools/make-daily.js 2026 --refresh (days 1 to 282 kept from the earlier schedule)
// One line per day. Day 1 is January 1. Each puzzle is named by its key (see shared/keys.js).
// Do not edit by hand: past days should stay as they were.
window.DAILY_SCHEDULE = window.DAILY_SCHEDULE || {};
window.DAILY_SCHEDULE[2026] = [
  ["PAPER","FALL","SHOP","POT","GAME"],  // 1 · Jan 1
  ["TOP","FREE","DOG","FISH","NIGHT"],  // 2 · Jan 2
  ["ROOM","SHOE","STONE","CHAIR","BALL"],  // 3 · Jan 3
  ["RAIN","SHIP","BOOT","MAIL","SOFT"],  // 4 · Jan 4
  ["GLASS","NAIL","LINE","EYE","MILK"],  // 5 · Jan 5
  ["FLY","FIRE","STAR","LIGHT","HAND"],  // 6 · Jan 6
  ["CAT","TEA","GRASS","HAT","FOOT"],  // 7 · Jan 7
  ["WHITE","SAND","SEA","HEART","DRESS"],  // 8 · Jan 8
  ["HEAD","KEY","WORM","WIND","FRUIT"],  // 9 · Jan 9
  ["COLD","BREAK","SIDE","SMOKE","CAKE"],  // 10 · Jan 10
  ["BOOK","SNOW","BACK","WOOD","HOUSE"],  // 11 · Jan 11
  ["MAN","BUS","TRAP","BOX","WATER"],  // 12 · Jan 12
  ["DOOR","SCHOOL","TRACK","BOW","WALL"],  // 13 · Jan 13
  ["SHORT","GOLD","BLOOD","BLACK","SALT"],  // 14 · Jan 14
  ["RING","TIME","HORSE","DAY","BED"],  // 15 · Jan 15
  ["BELL","CHIP","PASS","PLAY","ICE"],  // 16 · Jan 16
  ["ROCK","FLOWER","BOARD","PAN","SPACE"],  // 17 · Jan 17
  ["MOON","LAND","TOOTH","BANK","EGG"],  // 18 · Jan 18
  ["CROSS","CUP","SUN","WORK","SHELL"],  // 19 · Jan 19
  ["OIL","STICK","HAIR","BAG","CAR"],  // 20 · Jan 20
  ["BIRD","TABLE","LIGHT","STAR","FREE"],  // 21 · Jan 21
  ["NAIL","RAIN","MOON","HAIR","TIME"],  // 22 · Jan 22
  ["PLAY","HEART","HORSE","LINE","BALL"],  // 23 · Jan 23
  ["CUP","SOFT","BACK","CAR","CHAIR"],  // 24 · Jan 24
  ["HAND","CHIP","TOP","FRUIT","WORK"],  // 25 · Jan 25
  ["PASS","TRACK","ROOM","SMOKE","PAN"],  // 26 · Jan 26
  ["BUS","SHIP","GRASS","WALL","BLOOD"],  // 27 · Jan 27
  ["RING","BOW","HOUSE","BELL","PAPER"],  // 28 · Jan 28
  ["DOOR","GAME","MAN","BOOK","STICK"],  // 29 · Jan 29
  ["GLASS","SAND","SPACE","BLACK","ICE"],  // 30 · Jan 30
  ["SCHOOL","EYE","ROCK","DRESS","WATER"],  // 31 · Jan 31
  ["BAG","POT","TRAP","TABLE","HAT"],  // 32 · Feb 1
  ["CROSS","FLY","OIL","MILK","BED"],  // 33 · Feb 2
  ["NIGHT","SUN","BREAK","SEA","LAND"],  // 34 · Feb 3
  ["CAKE","BOOT","DOG","EGG","TOOTH"],  // 35 · Feb 4
  ["KEY","WIND","BANK","FISH","MAIL"],  // 36 · Feb 5
  ["FOOT","CAT","FIRE","GOLD","BIRD"],  // 37 · Feb 6
  ["SALT","HEAD","COLD","WOOD","STONE"],  // 38 · Feb 7
  ["DAY","FALL","BOX","TEA","WORM"],  // 39 · Feb 8
  ["SNOW","SHOP","WHITE","BOARD","SHELL"],  // 40 · Feb 9
  ["SHOE","SHORT","SIDE","FLOWER","BOX"],  // 41 · Feb 10
  ["CHAIR","WORK","SAND","FIRE","FLY"],  // 42 · Feb 11
  ["BED","BAG","WIND","WORM","POT"],  // 43 · Feb 12
  ["DOOR","HAT","SMOKE","BOOT","MOON"],  // 44 · Feb 13
  ["STONE","TEA","DRESS","GRASS","PAPER"],  // 45 · Feb 14
  ["CAKE","LAND","SPACE","SHOE","HOUSE"],  // 46 · Feb 15
  ["NAIL","TOP","SIDE","EYE","FOOT"],  // 47 · Feb 16
  ["SHIP","BALL","SEA","TIME","BIRD"],  // 48 · Feb 17
  ["SHELL","CUP","PASS","DOG","MILK"],  // 49 · Feb 18
  ["PAN","STAR","FALL","SUN","LINE"],  // 50 · Feb 19
  ["ROOM","MAIL","TOOTH","HAND","FREE"],  // 51 · Feb 20
  ["BUS","EGG","BLACK","GLASS","TABLE"],  // 52 · Feb 21
  ["STICK","BOARD","NIGHT","MAN","WALL"],  // 53 · Feb 22
  ["BLOOD","LIGHT","BANK","ROCK","WHITE"],  // 54 · Feb 23
  ["DAY","GAME","HAIR","TRACK","BOOK"],  // 55 · Feb 24
  ["RAIN","HEAD","FISH","OIL","BREAK"],  // 56 · Feb 25
  ["SNOW","BELL","WATER","SOFT","CAT"],  // 57 · Feb 26
  ["FRUIT","WOOD","SHORT","SALT","HEART"],  // 58 · Feb 27
  ["FLOWER","KEY","BOW","HORSE","ICE"],  // 59 · Feb 28
  ["TRAP","BACK","CROSS","SCHOOL","CHIP"],  // 60 · Mar 1
  ["RING","SHOP","GOLD","PLAY","CAR"],  // 61 · Mar 2
  ["COLD","LAND","CROSS","MOON","NIGHT"],  // 62 · Mar 3
  ["CHIP","BOOK","FOOT","FREE","SIDE"],  // 63 · Mar 4
  ["GOLD","DAY","SOFT","SMOKE","BOX"],  // 64 · Mar 5
  ["GRASS","TEA","TIME","EYE","BREAK"],  // 65 · Mar 6
  ["SHIP","HOUSE","TABLE","WIND","CUP"],  // 66 · Mar 7
  ["SAND","BIRD","SEA","BELL","HAND"],  // 67 · Mar 8
  ["RING","SPACE","BOOT","BOARD","PAN"],  // 68 · Mar 9
  ["SHOP","BOW","CHAIR","PAPER","BAG"],  // 69 · Mar 10
  ["GAME","BED","SHORT","FLOWER","BALL"],  // 70 · Mar 11
  ["RAIN","POT","LIGHT","WATER","ICE"],  // 71 · Mar 12
  ["DOOR","FRUIT","SHELL","MAN","SALT"],  // 72 · Mar 13
  ["FISH","NAIL","HEAD","SNOW","FLY"],  // 73 · Mar 14
  ["DOG","SCHOOL","SUN","BUS","HORSE"],  // 74 · Mar 15
  ["HAT","SHOE","WORM","HEART","MILK"],  // 75 · Mar 16
  ["FALL","STAR","WOOD","STONE","PLAY"],  // 76 · Mar 17
  ["PASS","BACK","WORK","KEY","GLASS"],  // 77 · Mar 18
  ["TOOTH","CAT","TRACK","MAIL","EGG"],  // 78 · Mar 19
  ["CAR","WHITE","HAIR","STICK","LINE"],  // 79 · Mar 20
  ["BLACK","TOP","COLD","WALL","ROCK"],  // 80 · Mar 21
  ["ROOM","DRESS","OIL","TRAP","FIRE"],  // 81 · Mar 22
  ["CAKE","BLOOD","BANK","SPACE","BOARD"],  // 82 · Mar 23
  ["DRESS","MOON","HAT","FIRE","BOW"],  // 83 · Mar 24
  ["SHELL","STONE","FISH","COLD","STICK"],  // 84 · Mar 25
  ["TOP","SCHOOL","ICE","BAG","WHITE"],  // 85 · Mar 26
  ["SHIP","CUP","BLACK","ROCK","PASS"],  // 86 · Mar 27
  ["KEY","ROOM","BALL","NAIL","TIME"],  // 87 · Mar 28
  ["PLAY","BOOK","FLOWER","LINE","MAN"],  // 88 · Mar 29
  ["TRAP","MAIL","WORM","WALL","PAN"],  // 89 · Mar 30
  ["MILK","FRUIT","BACK","GRASS","TEA"],  // 90 · Mar 31
  ["EYE","TABLE","SHOP","GOLD","BANK"],  // 91 · Apr 1
  ["SEA","WOOD","RAIN","SALT","HEAD"],  // 92 · Apr 2
  ["WATER","TOOTH","DAY","BIRD","BOX"],  // 93 · Apr 3
  ["DOG","CHAIR","BELL","CROSS","SAND"],  // 94 · Apr 4
  ["EGG","FOOT","GAME","FALL","HEART"],  // 95 · Apr 5
  ["SUN","STAR","HAIR","TRACK","SMOKE"],  // 96 · Apr 6
  ["CAKE","NIGHT","HOUSE","CHIP","FREE"],  // 97 · Apr 7
  ["DOOR","RING","GLASS","WORK","HAND"],  // 98 · Apr 8
  ["BLOOD","SOFT","WIND","BUS","BOOT"],  // 99 · Apr 9
  ["SNOW","CAT","SHORT","CAR","POT"],  // 100 · Apr 10
  ["FLY","LAND","OIL","SHOE","PAPER"],  // 101 · Apr 11
  ["BREAK","LIGHT","BED","SIDE","HORSE"],  // 102 · Apr 12
  ["BOX","SIDE","FALL","MILK","LAND"],  // 103 · Apr 13
  ["LINE","FLY","EYE","ROOM","BALL"],  // 104 · Apr 14
  ["CHIP","ROCK","TRAP","FLOWER","LIGHT"],  // 105 · Apr 15
  ["WALL","FIRE","HEAD","TIME","SUN"],  // 106 · Apr 16
  ["BIRD","BACK","BOARD","KEY","CUP"],  // 107 · Apr 17
  ["BREAK","TRACK","PAN","STICK","SOFT"],  // 108 · Apr 18
  ["SHELL","BAG","WORK","WOOD","BLACK"],  // 109 · Apr 19
  ["SAND","GRASS","CHAIR","STONE","NAIL"],  // 110 · Apr 20
  ["DOOR","PASS","MAIL","GAME","ICE"],  // 111 · Apr 21
  ["GLASS","FISH","CROSS","BOOT","BUS"],  // 112 · Apr 22
  ["PLAY","MOON","HAIR","FREE","MAN"],  // 113 · Apr 23
  ["EGG","SNOW","POT","TOP","BED"],  // 114 · Apr 24
  ["WIND","NIGHT","SEA","COLD","SHOP"],  // 115 · Apr 25
  ["DOG","DAY","FOOT","TOOTH","BELL"],  // 116 · Apr 26
  ["SHOE","SMOKE","PAPER","HAT","BOOK"],  // 117 · Apr 27
  ["SCHOOL","HORSE","STAR","RING","FRUIT"],  // 118 · Apr 28
  ["BLOOD","TABLE","HOUSE","SPACE","BOW"],  // 119 · Apr 29
  ["WATER","OIL","WHITE","SHORT","TEA"],  // 120 · Apr 30
  ["CAT","CAKE","CAR","HAND","SALT"],  // 121 · May 1
  ["SHIP","RAIN","HEART","BANK","WORM"],  // 122 · May 2
  ["DRESS","GOLD","RAIN","HAIR","SHOP"],  // 123 · May 3
  ["EYE","SHELL","HEAD","FLY","TOP"],  // 124 · May 4
  ["BACK","BOOT","RING","FRUIT","CUP"],  // 125 · May 5
  ["BED","DOOR","GOLD","GLASS","COLD"],  // 126 · May 6
  ["HORSE","ROCK","WHITE","CHAIR","CAKE"],  // 127 · May 7
  ["TOOTH","WATER","STICK","STONE","ICE"],  // 128 · May 8
  ["WALL","BREAK","SHOE","HEART","TABLE"],  // 129 · May 9
  ["BLACK","SEA","BELL","SOFT","PAPER"],  // 130 · May 10
  ["TRACK","WIND","OIL","DAY","PLAY"],  // 131 · May 11
  ["BOX","SIDE","SNOW","TIME","FOOT"],  // 132 · May 12
  ["TRAP","WORM","MOON","BOW","BAG"],  // 133 · May 13
  ["BOARD","CHIP","BANK","SHORT","CAR"],  // 134 · May 14
  ["EGG","CROSS","MILK","LINE","HAT"],  // 135 · May 15
  ["NAIL","GAME","SALT","FLOWER","DRESS"],  // 136 · May 16
  ["CAT","SCHOOL","LIGHT","FISH","HOUSE"],  // 137 · May 17
  ["BUS","ROOM","POT","TEA","DOG"],  // 138 · May 18
  ["BIRD","MAIL","BALL","HAND","BOOK"],  // 139 · May 19
  ["WOOD","STAR","FALL","MAN","PAN"],  // 140 · May 20
  ["FIRE","SAND","KEY","SMOKE","NIGHT"],  // 141 · May 21
  ["SPACE","PASS","WORK","SHIP","SUN"],  // 142 · May 22
  ["GRASS","LAND","FREE","BLOOD","BACK"],  // 143 · May 23
  ["PAPER","SNOW","GAME","BOOT","SHORT"],  // 144 · May 24
  ["DRESS","TIME","SHELL","CHAIR","RAIN"],  // 145 · May 25
  ["FLY","HAT","FALL","CROSS","BALL"],  // 146 · May 26
  ["COLD","BUS","PLAY","EYE","LIGHT"],  // 147 · May 27
  ["NIGHT","WORK","FRUIT","NAIL","BOW"],  // 148 · May 28
  ["CAT","STONE","GOLD","LAND","SIDE"],  // 149 · May 29
  ["MILK","FLOWER","HOUSE","FIRE","DAY"],  // 150 · May 30
  ["HEART","BAG","BREAK","BOARD","PASS"],  // 151 · May 31
  ["OIL","RING","MAIL","FISH","ROOM"],  // 152 · Jun 1
  ["TEA","WALL","TOP","CAR","SAND"],  // 153 · Jun 2
  ["EGG","SOFT","CAKE","STAR","WATER"],  // 154 · Jun 3
  ["WORM","GRASS","SUN","KEY","BOOK"],  // 155 · Jun 4
  ["GLASS","STICK","TRACK","SHIP","WHITE"],  // 156 · Jun 5
  ["TRAP","HEAD","SALT","FOOT","DOOR"],  // 157 · Jun 6
  ["BANK","TABLE","SMOKE","SEA","SHOE"],  // 158 · Jun 7
  ["BELL","WOOD","BED","WIND","BLOOD"],  // 159 · Jun 8
  ["MAN","MOON","ICE","CHIP","SCHOOL"],  // 160 · Jun 9
  ["CUP","DOG","TOOTH","POT","BOX"],  // 161 · Jun 10
  ["ROCK","PAN","HORSE","LINE","BLACK"],  // 162 · Jun 11
  ["SHOP","FREE","BIRD","HAND","HAIR"],  // 163 · Jun 12
  ["SPACE","WORM","SHIP","OIL","BUS"],  // 164 · Jun 13
  ["TABLE","MAN","CAR","FALL","SUN"],  // 165 · Jun 14
  ["RAIN","CHIP","NIGHT","LAND","EGG"],  // 166 · Jun 15
  ["SEA","PAN","POT","FLOWER","BANK"],  // 167 · Jun 16
  ["CROSS","BALL","BACK","WOOD","BOX"],  // 168 · Jun 17
  ["CUP","DOG","HAND","DRESS","SOFT"],  // 169 · Jun 18
  ["GAME","FREE","MAIL","WATER","RING"],  // 170 · Jun 19
  ["CHAIR","HAIR","NAIL","FLY","BIRD"],  // 171 · Jun 20
  ["TEA","GRASS","PASS","SALT","ROCK"],  // 172 · Jun 21
  ["BED","SMOKE","LINE","PAPER","SAND"],  // 173 · Jun 22
  ["GLASS","GOLD","SNOW","FISH","ICE"],  // 174 · Jun 23
  ["TOOTH","HAT","HOUSE","STONE","STICK"],  // 175 · Jun 24
  ["LIGHT","SPACE","WORK","WIND","SIDE"],  // 176 · Jun 25
  ["BLOOD","FOOT","TRACK","TOP","BOW"],  // 177 · Jun 26
  ["FIRE","FRUIT","BOOT","HEAD","TIME"],  // 178 · Jun 27
  ["DOOR","MILK","BREAK","BELL","CAKE"],  // 179 · Jun 28
  ["CAT","SHELL","PLAY","HEART","BOOK"],  // 180 · Jun 29
  ["TRAP","DAY","WALL","WHITE","MOON"],  // 181 · Jun 30
  ["BAG","COLD","SHOP","EYE","SHORT"],  // 182 · Jul 1
  ["BLACK","STAR","HORSE","ROOM","KEY"],  // 183 · Jul 2
  ["BOARD","SCHOOL","SHOE","GAME","STONE"],  // 184 · Jul 3
  ["BOX","FOOT","FISH","BOOK","HEART"],  // 185 · Jul 4
  ["HEAD","RAIN","SOFT","SHOP","WIND"],  // 186 · Jul 5
  ["BREAK","FIRE","RING","CAT","TOOTH"],  // 187 · Jul 6
  ["GRASS","PAPER","TIME","SCHOOL","DRESS"],  // 188 · Jul 7
  ["SNOW","BUS","WATER","COLD","HORSE"],  // 189 · Jul 8
  ["HAIR","GLASS","TRAP","WORK","DOG"],  // 190 · Jul 9
  ["STICK","LINE","TEA","CROSS","ROCK"],  // 191 · Jul 10
  ["LAND","DAY","TABLE","CAKE","SUN"],  // 192 · Jul 11
  ["BIRD","WHITE","WORM","PASS","BOW"],  // 193 · Jul 12
  ["SMOKE","BLACK","EYE","HOUSE","DOOR"],  // 194 · Jul 13
  ["NIGHT","SHOE","HAT","FLOWER","MAIL"],  // 195 · Jul 14
  ["MILK","POT","MAN","WOOD","FALL"],  // 196 · Jul 15
  ["CHIP","LIGHT","SPACE","MOON","STAR"],  // 197 · Jul 16
  ["BALL","NAIL","BOARD","SALT","ICE"],  // 198 · Jul 17
  ["SHORT","SIDE","BOOT","SAND","PLAY"],  // 199 · Jul 18
  ["FRUIT","CUP","SEA","KEY","CAR"],  // 200 · Jul 19
  ["WALL","BAG","SHIP","BLOOD","BACK"],  // 201 · Jul 20
  ["BELL","BED","TOP","GOLD","FREE"],  // 202 · Jul 21
  ["BANK","OIL","FLY","SHELL","ROOM"],  // 203 · Jul 22
  ["HAND","PAN","EGG","CHAIR","TRACK"],  // 204 · Jul 23
  ["HEAD","ICE","TABLE","FLY","TRACK"],  // 205 · Jul 24
  ["HOUSE","PASS","EGG","TOOTH","DRESS"],  // 206 · Jul 25
  ["SEA","BACK","SNOW","FRUIT","WORK"],  // 207 · Jul 26
  ["EYE","SCHOOL","WALL","BLOOD","KEY"],  // 208 · Jul 27
  ["FOOT","BOOK","NAIL","MAN","CAKE"],  // 209 · Jul 28
  ["SHOP","POT","BANK","SHELL","STAR"],  // 210 · Jul 29
  ["BAG","TEA","PLAY","TOP","SAND"],  // 211 · Jul 30
  ["GRASS","COLD","MAIL","GOLD","STONE"],  // 212 · Jul 31
  ["SPACE","CUP","GLASS","FISH","WORM"],  // 213 · Aug 1
  ["FIRE","HAT","ROOM","FLOWER","OIL"],  // 214 · Aug 2
  ["SUN","NIGHT","BELL","MOON","DOG"],  // 215 · Aug 3
  ["BLACK","RAIN","WATER","LIGHT","CROSS"],  // 216 · Aug 4
  ["HAIR","SHORT","HEART","GAME","BUS"],  // 217 · Aug 5
  ["BIRD","BOX","LAND","SHOE","CAR"],  // 218 · Aug 6
  ["DOOR","SMOKE","BALL","RING","ROCK"],  // 219 · Aug 7
  ["FREE","HORSE","BOOT","CHAIR","SALT"],  // 220 · Aug 8
  ["SHIP","BREAK","STICK","SIDE","PAPER"],  // 221 · Aug 9
  ["WIND","TRAP","CAT","FALL","BOARD"],  // 222 · Aug 10
  ["BOW","LINE","BED","SOFT","WOOD"],  // 223 · Aug 11
  ["CHIP","TIME","DAY","MILK","HAND"],  // 224 · Aug 12
  ["PAN","WHITE","FALL","CAR","DOG"],  // 225 · Aug 13
  ["DRESS","TRACK","BOOK","SAND","STAR"],  // 226 · Aug 14
  ["LINE","CHAIR","WORK","SPACE","HEART"],  // 227 · Aug 15
  ["MAN","DOOR","BOOT","WIND","SIDE"],  // 228 · Aug 16
  ["BELL","SOFT","DAY","FOOT","SHOE"],  // 229 · Aug 17
  ["BOARD","BED","CHIP","TOP","EYE"],  // 230 · Aug 18
  ["BUS","SHOP","TRAP","SALT","STONE"],  // 231 · Aug 19
  ["PAN","TIME","COLD","BIRD","FIRE"],  // 232 · Aug 20
  ["FRUIT","PASS","SMOKE","BOX","RING"],  // 233 · Aug 21
  ["BREAK","ROOM","BANK","WALL","FISH"],  // 234 · Aug 22
  ["STICK","TABLE","FREE","WORM","HOUSE"],  // 235 · Aug 23
  ["SCHOOL","BLACK","FLY","SUN","EGG"],  // 236 · Aug 24
  ["POT","CAT","GRASS","LAND","NAIL"],  // 237 · Aug 25
  ["HEAD","WATER","SHIP","SNOW","WOOD"],  // 238 · Aug 26
  ["BLOOD","KEY","ROCK","CUP","GAME"],  // 239 · Aug 27
  ["HAT","BAG","WHITE","RAIN","BOW"],  // 240 · Aug 28
  ["SHELL","GOLD","OIL","PAPER","MILK"],  // 241 · Aug 29
  ["MAIL","PLAY","TOOTH","LIGHT","FLOWER"],  // 242 · Aug 30
  ["SHORT","CROSS","NIGHT","BACK","HAIR"],  // 243 · Aug 31
  ["SEA","GLASS","MOON","HAND","TEA"],  // 244 · Sep 1
  ["CAKE","ICE","HORSE","BALL","TOP"],  // 245 · Sep 2
  ["MAN","HOUSE","FOOT","COLD","EYE"],  // 246 · Sep 3
  ["SHIP","FLOWER","WHITE","HEART","SPACE"],  // 247 · Sep 4
  ["WOOD","LINE","ROOM","WIND","KEY"],  // 248 · Sep 5
  ["EGG","BUS","HAT","WATER","TABLE"],  // 249 · Sep 6
  ["CHAIR","FLY","BOOK","TRACK","PLAY"],  // 250 · Sep 7
  ["SUN","SCHOOL","POT","BOOT","WORK"],  // 251 · Sep 8
  ["FALL","SAND","BED","SHOE","PAN"],  // 252 · Sep 9
  ["OIL","ROCK","FREE","SOFT","TOOTH"],  // 253 · Sep 10
  ["CHIP","SIDE","CUP","CAKE","ICE"],  // 254 · Sep 11
  ["HAIR","TRAP","GAME","BIRD","BOARD"],  // 255 · Sep 12
  ["BLOOD","GRASS","GOLD","BELL","PAPER"],  // 256 · Sep 13
  ["HAND","RING","BACK","DAY","HORSE"],  // 257 · Sep 14
  ["BAG","FRUIT","LAND","CAR","CAT"],  // 258 · Sep 15
  ["BOW","DRESS","SHOP","NAIL","SNOW"],  // 259 · Sep 16
  ["NIGHT","STAR","FIRE","TIME","DOG"],  // 260 · Sep 17
  ["TEA","BOX","MAIL","BREAK","BANK"],  // 261 · Sep 18
  ["BALL","MOON","HEAD","LIGHT","STICK"],  // 262 · Sep 19
  ["SHELL","STONE","DOOR","BLACK","CROSS"],  // 263 · Sep 20
  ["WORM","MILK","SMOKE","FISH","WALL"],  // 264 · Sep 21
  ["SHORT","RAIN","GLASS","SEA","SALT"],  // 265 · Sep 22
  ["PASS","DRESS","PAN","TEA","MAIL"],  // 266 · Sep 23
  ["BANK","NIGHT","HEART","DOG","BOOK"],  // 267 · Sep 24
  ["SUN","STAR","BIRD","SHOE","WORM"],  // 268 · Sep 25
  ["BED","BACK","HAIR","LINE","BLOOD"],  // 269 · Sep 26
  ["CAT","SCHOOL","TABLE","EYE","NAIL"],  // 270 · Sep 27
  ["FIRE","WALL","HOUSE","BUS","KEY"],  // 271 · Sep 28
  ["FRUIT","MOON","DAY","PAPER","PASS"],  // 272 · Sep 29
  ["FISH","SEA","CROSS","BLACK","STICK"],  // 273 · Sep 30
  ["CHIP","EGG","FLY","SHELL","ROOM"],  // 274 · Oct 1
  ["HORSE","LAND","TOOTH","WORK","FREE"],  // 275 · Oct 2
  ["RING","SALT","SAND","RAIN","HAT"],  // 276 · Oct 3
  ["TOP","FALL","SHOP","DOOR","CUP"],  // 277 · Oct 4
  ["HEAD","FLOWER","STONE","GAME","BELL"],  // 278 · Oct 5
  ["MAN","BOARD","COLD","CAR","ROCK"],  // 279 · Oct 6
  ["BREAK","CAKE","SNOW","SOFT","WIND"],  // 280 · Oct 7
  ["BOX","TIME","TRAP","HAND","ICE"],  // 281 · Oct 8
  ["BAG","SHORT","GLASS","OIL","GRASS"],  // 282 · Oct 9
  ["TRIP","WAX","SMOKE","GATE","BEAN"],  // 283 · Oct 10
  ["SNOW","CARPET","STORM","SOFT","WALL"],  // 284 · Oct 11
  ["SHORT","SWEET","TOP","NUT","TOWER"],  // 285 · Oct 12
  ["WATCH","MASTER","HOUSE","CHAIN","WOLF"],  // 286 · Oct 13
  ["GOLD","KNIFE","SPRING","RING","CAR"],  // 287 · Oct 14
  ["TOWN","KEY","DOOR","PIECE","DOG"],  // 288 · Oct 15
  ["TRAIN","LAND","HOLE","ROCK","PAD"],  // 289 · Oct 16
  ["WHITE","BAG","PRINT","RUN","SET"],  // 290 · Oct 17
  ["FREE","SPOON","STONE","WORK","CASE"],  // 291 · Oct 18
  ["LINE","SEA","BERRY","WORD","CHIP"],  // 292 · Oct 19
  ["SEED","DUST","PLAY","GUARD","WORM"],  // 293 · Oct 20
  ["ROAD","TOOTH","BLOOD","SHIP","CAKE"],  // 294 · Oct 21
  ["STICK","JAM","BACK","BELT","HOT"],  // 295 · Oct 22
  ["SIDE","BUG","CARD","DRESS","TRAP"],  // 296 · Oct 23
  ["PICK","TABLE","FRUIT","CORN","ICE"],  // 297 · Oct 24
  ["RAIN","SCHOOL","BRIDGE","APPLE","STAMP"],  // 298 · Oct 25
  ["FALL","SKIN","MAIL","BRUSH","TEA"],  // 299 · Oct 26
  ["PILLOW","WATER","DROP","JACK","GRAPE"],  // 300 · Oct 27
  ["NAIL","CRAFT","BOX","BREAD","FORK"],  // 301 · Oct 28
  ["POT","FLOWER","PAPER","MATE","SHOP"],  // 302 · Oct 29
  ["TIP","CUP","BOARD","BRICK","HOUND"],  // 303 · Oct 30
  ["MARK","DAY","FLAKE","PAN","SHED"],  // 304 · Oct 31
  ["YARD","LOCK","STAR","SHOE","FIRE"],  // 305 · Nov 1
  ["LIFE","COAT","SHADE","BLACK","GAME"],  // 306 · Nov 2
  ["POST","POINT","BOW","BREAK","FIELD"],  // 307 · Nov 3
  ["SALT","SHELL","HEART","RING","SHORT"],  // 308 · Nov 4
  ["STEP","PORT","TRAP","TABLE","SPRING"],  // 309 · Nov 5
  ["SHADE","JAM","BUS","WIND","CASE"],  // 310 · Nov 6
  ["TRACK","DOOR","OIL","BERRY","WORK"],  // 311 · Nov 7
  ["HEAD","PAPER","APPLE","PIPE","HAT"],  // 312 · Nov 8
  ["PICK","GRAPE","SHOP","LOCK","WALL"],  // 313 · Nov 9
  ["BEAN","WAY","TRAIN","HAND","ROAD"],  // 314 · Nov 10
  ["BOARD","POST","BRIDGE","WOOD","MOON"],  // 315 · Nov 11
  ["WARE","FORK","ROCK","CAKE","RUN"],  // 316 · Nov 12
  ["DRUM","PILLOW","BOOK","WORD","STICK"],  // 317 · Nov 13
  ["WOLF","GOLD","CAT","SCHOOL","TIME"],  // 318 · Nov 14
  ["LIGHT","TIP","WEED","EYE","EGG"],  // 319 · Nov 15
  ["BALL","SHIP","STAMP","FLOWER","GROUND"],  // 320 · Nov 16
  ["GRASS","KNIFE","DROP","STAND","STONE"],  // 321 · Nov 17
  ["SIDE","GIRL","MILK","CAR","SKIN"],  // 322 · Nov 18
  ["TEA","HOLE","PAN","BREAD","SHED"],  // 323 · Nov 19
  ["BELL","SPACE","PRINT","ICE","BIRD"],  // 324 · Nov 20
  ["DUST","BREAK","RACE","BRUSH","SOFT"],  // 325 · Nov 21
  ["BAR","HOUSE","TOP","CRAFT","MAIL"],  // 326 · Nov 22
  ["SAND","BACK","SWEET","SET","SEA"],  // 327 · Nov 23
  ["PAD","BOY","COLD","HAIR","FIRE"],  // 328 · Nov 24
  ["SALT","BAND","DRESS","WATCH","LOG"],  // 329 · Nov 25
  ["SHOE","SUIT","NAIL","PASS","PIECE"],  // 330 · Nov 26
  ["LAND","MASTER","SPOT","BED","NIGHT"],  // 331 · Nov 27
  ["FISH","PLAY","YARD","WHEEL","BOX"],  // 332 · Nov 28
  ["LAMP","MATE","SEED","WHITE","BAG"],  // 333 · Nov 29
  ["BUG","FRUIT","HOT","BOW","CARD"],  // 334 · Nov 30
  ["BOOT","HORSE","CROSS","MAN","BELT"],  // 335 · Dec 1
  ["FLAKE","SHOT","KEY","TOWER","SPOON"],  // 336 · Dec 2
  ["MILL","BANK","CARPET","LIFE","SMOKE"],  // 337 · Dec 3
  ["FLY","FALL","TOWN","TOOTH","WAX"],  // 338 · Dec 4
  ["CORN","CLOTH","LINE","CUP","SUN"],  // 339 · Dec 5
  ["POINT","CHAIR","CHIP","GAME","GATE"],  // 340 · Dec 6
  ["RAIN","FREE","CAP","DAY","HOUND"],  // 341 · Dec 7
  ["STORM","BLOOD","TRIP","JACK","GLASS"],  // 342 · Dec 8
  ["BLACK","WATER","SNOW","NUT","CHAIN"],  // 343 · Dec 9
  ["BRICK","PIE","POT","STAR","WORM"],  // 344 · Dec 10
  ["MARK","COAT","DOG","GUARD","FOOT"],  // 345 · Dec 11
  ["ROOM","PLANT","FIELD","BOW","BAR"],  // 346 · Dec 12
  ["GRASS","JAM","LOG","GRAPE","ROAD"],  // 347 · Dec 13
  ["SHELL","TOWER","YARD","NUT","BELT"],  // 348 · Dec 14
  ["RACE","STICK","BANK","WATCH","DRESS"],  // 349 · Dec 15
  ["TOP","PLAY","RUN","GATE","SEA"],  // 350 · Dec 16
  ["MILK","BREAD","SPRING","STONE","TRIP"],  // 351 · Dec 17
  ["PAPER","BRUSH","FRUIT","CHAIN","GLASS"],  // 352 · Dec 18
  ["POINT","POT","SHOP","STAMP","FLAKE"],  // 353 · Dec 19
  ["MATE","HOUSE","BEAN","TRAP","PIPE"],  // 354 · Dec 20
  ["FALL","TOOTH","KNIFE","RAIN","FISH"],  // 355 · Dec 21
  ["DROP","HEART","WAY","LAMP","SIDE"],  // 356 · Dec 22
  ["PRINT","EYE","WHEEL","EGG","BUS"],  // 357 · Dec 23
  ["SNOW","TABLE","TIP","PAD","TRAIN"],  // 358 · Dec 24
  ["CLOTH","CROSS","CARD","BAG","OIL"],  // 359 · Dec 25
  ["STAR","GOLD","GUARD","BREAK","PAN"],  // 360 · Dec 26
  ["SUN","BAND","TRACK","SHOE","MASTER"],  // 361 · Dec 27
  ["DUST","ICE","PASS","HOUND","NIGHT"],  // 362 · Dec 28
  ["HORSE","SHORT","SUIT","FLOWER","SALT"],  // 363 · Dec 29
  ["BLACK","ROCK","RING","POST","SPOT"],  // 364 · Dec 30
  ["BERRY","BALL","DAY","PILLOW","WATER"]  // 365 · Dec 31
];
