// Three of a Kind puzzles.
//
// Each puzzle has:
//   words  - three words, in capitals
//   answer - what they have in common (the correct option)
//   wrong  - three options that are not correct
//
// The game shuffles the four options. Every game picks five puzzles at random.
// All puzzles must be original.

window.THREE_OF_A_KIND_PUZZLES = [
  { words: ["SCAR", "CARPET", "OSCAR"], answer: "Each contains CAR", wrong: ["Each is a film term", "Each can follow RED", "Each has two syllables"] },
  { words: ["POUND", "HASH", "NUMBER"], answer: "Each is a name for the # sign", wrong: ["Each is a unit of weight", "Each is a kind of key", "Each is a breakfast food"] },
  { words: ["BASS", "BOW", "LEAD"], answer: "Each has two pronunciations", wrong: ["Each is part of a ship", "Each is a metal", "Each is a kind of fish"] },
  { words: ["LEVEL", "RADAR", "KAYAK"], answer: "Each reads the same backwards", wrong: ["Each is a kind of boat", "Each is a tool", "Each has two vowels"] },
  { words: ["ALMOST", "BIOPSY", "CHINTZ"], answer: "Their letters run in alphabetical order", wrong: ["Each is a medical term", "Each has no repeated vowels", "Each is a kind of fabric"] },
  { words: ["CLUB", "DIAMOND", "SPADE"], answer: "Each is a suit of cards", wrong: ["Each is a garden tool", "Each is a shape", "Each is a kind of sandwich"] },
  { words: ["DOZEN", "GROSS", "SCORE"], answer: "Each names a number", wrong: ["Each is a sports term", "Each means unpleasant", "Each is a unit of weight"] },
  { words: ["QUEUE", "BEE", "TEA"], answer: "Each sounds like a letter", wrong: ["Each is found in a garden", "Each has a double letter", "Each is a British habit"] },
  { words: ["CARPENTER", "SERPENT", "PENTAGON"], answer: "Each contains PEN", wrong: ["Each is a kind of snake", "Each is a job", "Each has four syllables"] },
  { words: ["TEACHER", "PEACHES", "BLEACH"], answer: "Each contains EACH", wrong: ["Each is a fruit", "Each is found in a school", "Each ends in a silent letter"] },
  { words: ["SPARROW", "ARROWHEAD", "NARROW"], answer: "Each contains ARROW", wrong: ["Each is a bird", "Each is a weapon", "Each means thin"] },
  { words: ["OAK", "MAPLE", "BIRCH"], answer: "Each is a tree", wrong: ["Each is a kind of syrup", "Each is a dog breed", "Each is a type of boat"] },
  { words: ["VIOLIN", "CELLO", "HARP"], answer: "Each has strings", wrong: ["Each is played with a bow", "Each is a brass instrument", "Each is a card game"] },
  { words: ["BISHOP", "KNIGHT", "ROOK"], answer: "Each is a chess piece", wrong: ["Each is a bird", "Each is a church title", "Each is a kind of soldier"] },
  { words: ["RUBY", "EMERALD", "SAPPHIRE"], answer: "Each is a gemstone", wrong: ["Each is a kind of wine", "Each is a shade of green", "Each is a playing card"] },
  { words: ["TIMES", "CROSS", "KISS"], answer: "Each can be written as an X", wrong: ["Each is a kind of puzzle", "Each is a church word", "Each is a sign of affection"] },
  { words: ["AND", "PER", "AT"], answer: "Each has its own keyboard symbol", wrong: ["Each is a Latin word", "Each is a chess term", "Each is a unit of measure"] },
  { words: ["RIVER", "BOTTLE", "CAVE"], answer: "Each has a mouth", wrong: ["Each holds water", "Each is found underground", "Each is made of glass"] },
  { words: ["NEEDLE", "STORM", "POTATO"], answer: "Each has an eye", wrong: ["Each is found in a kitchen", "Each is a kind of weather", "Each is sharp"] },
  { words: ["PIANO", "TYPEWRITER", "COMPUTER"], answer: "Each has keys", wrong: ["Each is a musical instrument", "Each is found in an office", "Each has a screen"] },
  { words: ["TABLE", "DOG", "JOURNEY"], answer: "Each has legs", wrong: ["Each is found in a kitchen", "Each can be walked", "Each has four of something"] },
  { words: ["COMB", "SAW", "KEY"], answer: "Each has teeth", wrong: ["Each is a tool", "Each is found in a bathroom", "Each cuts"] },
  { words: ["BOOK", "TREE", "CABBAGE"], answer: "Each has leaves", wrong: ["Each grows", "Each is green", "Each is made of paper"] },
  { words: ["BOTTLE", "GUITAR", "GIRAFFE"], answer: "Each has a neck", wrong: ["Each is made of glass", "Each has strings", "Each is found in a zoo"] },
  { words: ["HEARTH", "EARTHQUAKE", "UNEARTHED"], answer: "Each contains EARTH", wrong: ["Each is a kind of fireplace", "Each means to dig up", "Each is a natural disaster"] },
  { words: ["TEAPOT", "HIPPOPOTAMUS", "POTATO"], answer: "Each contains POT", wrong: ["Each is a vegetable", "Each is found in a kitchen", "Each lives in a river"] },
  { words: ["CATALOGUE", "SCATTER", "VACATION"], answer: "Each contains CAT", wrong: ["Each is a holiday word", "Each means to spread about", "Each is a kind of list"] },
  { words: ["ENGINE", "GINGER", "IMAGINE"], answer: "Each contains GIN", wrong: ["Each is a spice", "Each is part of a car", "Each means to think up"] },
  { words: ["BANDAGE", "HUSBAND", "ABANDON"], answer: "Each contains BAND", wrong: ["Each is a first-aid word", "Each means to leave behind", "Each is a family member"] },
  { words: ["MINUS", "DASH", "HYPHEN"], answer: "Each is a short horizontal line", wrong: ["Each is a running term", "Each is a maths word", "Each is a punctuation mark"] },
  { words: ["CHECK", "TICK", "CORRECT"], answer: "Each can be shown as a check mark", wrong: ["Each is a kind of clock", "Each is a chess term", "Each is a kind of insect"] },
  { words: ["BAKER", "SMITH", "COOPER"], answer: "Each is a surname that was once a job", wrong: ["Each is a kind of bread", "Each is a famous explorer", "Each is a type of barrel"] },
  { words: ["MERCURY", "IRON", "COPPER"], answer: "Each is a metal", wrong: ["Each is a planet", "Each is a Roman god", "Each is a coin"] },
  { words: ["CRICKET", "SQUASH", "GOLF"], answer: "Each is a sport", wrong: ["Each is an insect", "Each is a vegetable", "Each is played on ice"] },
  { words: ["MOUSE", "WEB", "VIRUS"], answer: "Each is a computer word", wrong: ["Each is an animal", "Each is spun by a spider", "Each is an illness"] },
  { words: ["PUPIL", "IRIS", "LID"], answer: "Each is part of the eye", wrong: ["Each is a flower", "Each is a school word", "Each is part of a box"] },
  { words: ["BARK", "TRUNK", "RING"], answer: "Each is part of a tree", wrong: ["Each is a dog noise", "Each is part of a car", "Each is jewellery"] },
  { words: ["JACK", "QUEEN", "ACE"], answer: "Each is a playing card", wrong: ["Each is a tool for lifting a car", "Each is a chess piece", "Each is a tennis term"] },
  { words: ["PENNY", "NICKEL", "DIME"], answer: "Each is a coin", wrong: ["Each is a metal", "Each is a girl's name", "Each is a kind of candy"] },
  { words: ["TIBIA", "FEMUR", "SKULL"], answer: "Each is a bone", wrong: ["Each is a Roman emperor", "Each is a kind of muscle", "Each is a pirate word"] },
  { words: ["BRIDGE", "POKER", "HEARTS"], answer: "Each is a card game", wrong: ["Each is a body part", "Each is a fireplace tool", "Each crosses a river"] },
  { words: ["BUFFALO", "FLY", "DUCK"], answer: "Each is both an animal and an action", wrong: ["Each has wings", "Each lives in water", "Each is a kind of bird"] },
  { words: ["SWIFT", "GOOSE", "KITE"], answer: "Each is a bird", wrong: ["Each is a toy", "Each means fast", "Each is a kind of boat"] },
  { words: ["TROUT", "SALMON", "COD"], answer: "Each is a fish", wrong: ["Each is a river", "Each is a kind of boat", "Each is a Scottish town"] },
  { words: ["PAW", "HOOF", "FIN"], answer: "Each is part of an animal", wrong: ["Each is a kind of shoe", "Each is part of a car", "Each is a swimming stroke"] },
  { words: ["TULIP", "CROCUS", "DAFFODIL"], answer: "Each is a spring flower", wrong: ["Each is a tree", "Each is a vegetable", "Each is a bird"] },
  { words: ["HAMLET", "OTHELLO", "MACBETH"], answer: "Each is a Shakespeare play", wrong: ["Each is a Roman emperor", "Each is a Greek island", "Each is a kind of cheese"] },
  { words: ["FLUTE", "OBOE", "CLARINET"], answer: "Each is a woodwind instrument", wrong: ["Each is a brass instrument", "Each is a kind of glass", "Each has strings"] },
  { words: ["LIVER", "KIDNEY", "LUNG"], answer: "Each is an organ of the body", wrong: ["Each is a bone", "Each is a muscle", "Each is a kind of fish"] },
  { words: ["COBRA", "VIPER", "ADDER"], answer: "Each is a snake", wrong: ["Each is a kind of hat", "Each is a dance", "Each is a river"] },
  { words: ["ASH", "EMBER", "SOOT"], answer: "Each is left behind by a fire", wrong: ["Each is a tree", "Each is a colour", "Each is a kind of coal"] },
  { words: ["WALTZ", "TANGO", "SALSA"], answer: "Each is a dance", wrong: ["Each is a sauce", "Each is a card game", "Each is a kind of pasta"] },
  { words: ["CHEDDAR", "BRIE", "GOUDA"], answer: "Each is a cheese", wrong: ["Each is a town in France", "Each is a kind of wine", "Each is a dog breed"] },
  { words: ["MARS", "JUPITER", "SATURN"], answer: "Each is a planet", wrong: ["Each is a moon", "Each is a kind of rocket", "Each is a day of the week"] },
  { words: ["COMMA", "COLON", "DASH"], answer: "Each is a punctuation mark", wrong: ["Each is a running term", "Each is a kind of fish", "Each is a musical note"] },
  { words: ["NILE", "AMAZON", "DANUBE"], answer: "Each is a river", wrong: ["Each is a mountain", "Each is a shop", "Each is a desert"] },
  { words: ["ATLAS", "GLOBE", "MAP"], answer: "Each shows the world", wrong: ["Each is a Greek god", "Each is a kind of lamp", "Each is a dance"] },
  { words: ["WHEAT", "THEATRE", "SHEATH"], answer: "Each contains HEAT", wrong: ["Each is a grain", "Each is a knife cover", "Each is a stage word"] },
  { words: ["COWARD", "SCOWL", "COWBOY"], answer: "Each contains COW", wrong: ["Each is a farm word", "Each means afraid", "Each is a Western film word"] },
  { words: ["PIGEON", "PIGMENT", "SPIGOT"], answer: "Each contains PIG", wrong: ["Each is a bird", "Each is a colour word", "Each is a kind of tap"] },
  { words: ["BOREDOM", "KINGDOM", "RANDOM"], answer: "Each contains DOM", wrong: ["Each is a country", "Each means dull", "Each is a word about chance"] },
  { words: ["SHAMPOO", "HAMMOCK", "CHAMPION"], answer: "Each contains HAM", wrong: ["Each is a winner", "Each is found in a bathroom", "Each is a kind of bed"] },
  { words: ["ELEPHANT", "TREE", "CAR"], answer: "Each has a trunk", wrong: ["Each has leaves", "Each has wheels", "Each has tusks"] },
  { words: ["HAMMER", "CABBAGE", "COIN"], answer: "Each has a head", wrong: ["Each is a tool", "Each is a vegetable", "Each is money"] },
  { words: ["SHOE", "BELL", "FLAME"], answer: "Each has a tongue", wrong: ["Each rings", "Each is worn", "Each is hot"] },
  { words: ["CORN", "BARLEY", "ELEPHANT"], answer: "Each has ears", wrong: ["Each is a grain", "Each is grey", "Each grows in a field"] },
  { words: ["SKUNK", "ONION", "GARLIC"], answer: "Each is known for its smell", wrong: ["Each is a vegetable", "Each is black and white", "Each is a flower"] },
  { words: ["PERCENT", "HUNDRED", "CENTURY"], answer: "Each is about one hundred", wrong: ["Each is a kind of coin", "Each is a number of years", "Each is a maths sign"] },
  { words: ["NIL", "LOVE", "DUCK"], answer: "Each means a score of zero in a sport", wrong: ["Each is a bird", "Each is a feeling", "Each is a Latin word"] },
  { words: ["TEAPOT", "KETTLE", "JUG"], answer: "Each has a spout", wrong: ["Each boils water", "Each is made of china", "Each is a baseball word"] },
  // ---- Added 9 October 2026 ----
  { words: ["VIOLET", "ROSE", "OLIVE"], answer: "Each is a colour and a plant", wrong: ["Each is a kind of tree", "Each is a spice", "Each is a fruit"] },
  { words: ["MOUSE", "CRANE", "SEAL"], answer: "Each is an animal and a piece of equipment", wrong: ["Each lives in water", "Each is a bird", "Each is a car maker"] },
  { words: ["FOOT", "YARD", "INCH"], answer: "Each is a unit of length", wrong: ["Each is a part of a house", "Each is a verb meaning to walk", "Each is a part of a ship"] },
  { words: ["CRESCENT", "FULL", "NEW"], answer: "Each is a phase of the moon", wrong: ["Each is a kind of bread", "Each is a kind of tide", "Each is a shape in geometry"] },
  { words: ["BISHOP", "DEAN", "VICAR"], answer: "Each is a rank in the church", wrong: ["Each is a chess piece", "Each is a rank in the police", "Each is a university title"] },
  { words: ["HOOK", "LINE", "SINKER"], answer: "Each is part of fishing tackle", wrong: ["Each is a part of a pen", "Each is a part of a song", "Each is a sailing term"] },
  { words: ["ALTO", "TENOR", "BASS"], answer: "Each is a singing voice", wrong: ["Each is a fishing lure", "Each is a kind of drum", "Each is a dance"] },
  { words: ["ORANGE", "LIME", "LEMON"], answer: "Each is a citrus fruit", wrong: ["Each is a colour of the rainbow", "Each grows on a vine", "Each is a berry"] },
  { words: ["KEYBOARD", "MONITOR", "PRINTER"], answer: "Each plugs into a computer", wrong: ["Each is a musical instrument", "Each is a job title", "Each has a lid"] },
  { words: ["BOLT", "NUT", "WASHER"], answer: "Each is a piece of hardware for fastening", wrong: ["Each is a kitchen appliance", "Each is a running term", "Each is a kind of dog"] },
  { words: ["CLUTCH", "BRAKE", "GEAR"], answer: "Each is a control in a car", wrong: ["Each is a hockey term", "Each is a type of shoe", "Each is a poker term"] },
  { words: ["JAVA", "MOCHA", "LATTE"], answer: "Each is a word for coffee", wrong: ["Each is a dance", "Each is an Italian city", "Each is a breed of cat"] },
  { words: ["PERCH", "PIKE", "CARP"], answer: "Each is a freshwater fish", wrong: ["Each is a kind of cheese", "Each is a card game", "Each is a dance"] },
  { words: ["TEAL", "NAVY", "SKY"], answer: "Each is a shade of blue", wrong: ["Each is a kind of boat", "Each is a fabric", "Each is a month"] },
  { words: ["ROBIN", "JAY", "WREN"], answer: "Each is a bird", wrong: ["Each is a car maker", "Each is a planet", "Each is a kind of cheese"] },
  { words: ["SONNET", "HAIKU", "LIMERICK"], answer: "Each is a form of poem", wrong: ["Each is a pasta shape", "Each is a dance", "Each is a type of knot"] },
  { words: ["WATT", "VOLT", "AMP"], answer: "Each is a unit of electricity", wrong: ["Each is a chess champion", "Each is a cheese", "Each is a dog breed"] },
  { words: ["STIRRUP", "SADDLE", "BRIDLE"], answer: "Each is part of a horse's tack", wrong: ["Each is a sewing term", "Each is a kind of bread", "Each is a card game"] },
  { words: ["CUMULUS", "CIRRUS", "STRATUS"], answer: "Each is a type of cloud", wrong: ["Each is a Roman emperor", "Each is a spell in a story", "Each is a type of pasta"] },
  { words: ["CANINE", "MOLAR", "INCISOR"], answer: "Each is a kind of tooth", wrong: ["Each is a chess opening", "Each is a kind of drill", "Each is a star"] },
  { words: ["MAJOR", "CAPTAIN", "COLONEL"], answer: "Each is an army rank", wrong: ["Each is a kind of ship", "Each is a card game", "Each is a cut of beef"] },
  { words: ["SCALPEL", "FORCEPS", "SUTURE"], answer: "Each is used in surgery", wrong: ["Each is a kitchen utensil", "Each is a sewing tool", "Each is a garden tool"] },
  { words: ["SPATULA", "WHISK", "LADLE"], answer: "Each is a kitchen utensil", wrong: ["Each is a dance", "Each is a golf club", "Each is a part of a boat"] },
  { words: ["CROQUET", "POLO", "LACROSSE"], answer: "Each is played with a stick or mallet", wrong: ["Each is played in water", "Each is a card game", "Each is a board game"] },
  { words: ["SAHARA", "GOBI", "MOJAVE"], answer: "Each is a desert", wrong: ["Each is a mountain range", "Each is a river", "Each is a volcano"] },
  { words: ["GALLON", "LITRE", "QUART"], answer: "Each is a measure of liquid", wrong: ["Each is a unit of weight", "Each is a coin", "Each is a playing-card term"] },
  { words: ["CARAT", "OUNCE", "GRAM"], answer: "Each is a unit of weight", wrong: ["Each is a kind of vegetable", "Each is a currency", "Each is a measure of length"] },
  { words: ["ELM", "YEW", "FIR"], answer: "Each is a tree", wrong: ["Each is a river", "Each is a bird", "Each is a fabric"] },
  { words: ["DRAKE", "GANDER", "STALLION"], answer: "Each is a male animal", wrong: ["Each is a kind of cheese", "Each is a ship", "Each is a star"] },
  { words: ["DOE", "EWE", "MARE"], answer: "Each is a female animal", wrong: ["Each is a kind of bread", "Each is a river", "Each is a Greek letter"] },
  { words: ["KID", "CALF", "FOAL"], answer: "Each is a young animal", wrong: ["Each is a kind of boot", "Each is a card game", "Each is a boat"] },
  { words: ["NOUN", "VERB", "ADJECTIVE"], answer: "Each is a part of speech", wrong: ["Each is a punctuation mark", "Each is a chess term", "Each is a musical term"] },
  { words: ["BLUSH", "CRIMSON", "SCARLET"], answer: "Each is a shade of red", wrong: ["Each is a river", "Each is a cheese", "Each is a dance"] },
  { words: ["FEDORA", "BERET", "BOWLER"], answer: "Each is a hat", wrong: ["Each is a pasta", "Each is a car", "Each is a kind of bread"] },
  { words: ["LOAFER", "BROGUE", "MOCCASIN"], answer: "Each is a shoe", wrong: ["Each is a sandwich", "Each is a dance", "Each is a cocktail"] },
  { words: ["PENNE", "FUSILLI", "FARFALLE"], answer: "Each is a pasta shape", wrong: ["Each is an opera", "Each is a car", "Each is a cheese"] },
  { words: ["MERLOT", "RIESLING", "CHARDONNAY"], answer: "Each is a kind of wine", wrong: ["Each is a composer", "Each is a dance", "Each is a cheese"] },
  { words: ["SITAR", "BANJO", "UKULELE"], answer: "Each is a stringed instrument", wrong: ["Each is a drum", "Each is a dance", "Each is a dessert"] },
  { words: ["CHECKERS", "CHESS", "BACKGAMMON"], answer: "Each is a board game", wrong: ["Each is a card game", "Each is a cocktail", "Each is a cheese"] },
  { words: ["TOPAZ", "OPAL", "GARNET"], answer: "Each is a gemstone", wrong: ["Each is a shade of blue", "Each is a moon of Jupiter", "Each is a cheese"] },
  { words: ["AVOCADO", "TOMATO", "CUCUMBER"], answer: "Each is a fruit, botanically", wrong: ["Each is a root vegetable", "Each grows underground", "Each is a kind of nut"] },
  { words: ["CLOVE", "NUTMEG", "CINNAMON"], answer: "Each is a spice", wrong: ["Each is a kind of apple", "Each is a sauce", "Each is a pasta"] },
  { words: ["BASIL", "SAGE", "DILL"], answer: "Each is a herb", wrong: ["Each is a Greek god", "Each is a cheese", "Each is a coin"] },
  { words: ["SOLE", "FLOUNDER", "HALIBUT"], answer: "Each is a flatfish", wrong: ["Each is a kind of pasta", "Each is a sailing term", "Each is a cheese"] },
  { words: ["ZEUS", "HERA", "APOLLO"], answer: "Each is a Greek god", wrong: ["Each is a cheese", "Each is a river", "Each is a constellation"] },
  { words: ["CRANIUM", "PATELLA", "STERNUM"], answer: "Each is a bone", wrong: ["Each is a planet", "Each is a pasta", "Each is a cloud"] },
  { words: ["DIESEL", "PETROL", "KEROSENE"], answer: "Each is a fuel", wrong: ["Each is a kind of engine", "Each is a rock", "Each is a fabric"] },
  { words: ["QUARTZ", "GRANITE", "MARBLE"], answer: "Each is a kind of rock", wrong: ["Each is a kind of cake", "Each is a cheese", "Each is a planet"] },
  { words: ["SONATA", "CONCERTO", "SYMPHONY"], answer: "Each is a form of music", wrong: ["Each is a pasta", "Each is a cheese", "Each is a dance"] },
  { words: ["KRONA", "RUPEE", "YEN"], answer: "Each is a currency", wrong: ["Each is a kind of boat", "Each is a cheese", "Each is a dance"] },
  { words: ["TROMBONE", "TUBA", "CORNET"], answer: "Each is a brass instrument", wrong: ["Each is a pasta", "Each is a cheese", "Each is a dance"] },
  { words: ["BUNGALOW", "VILLA", "CHALET"], answer: "Each is a kind of house", wrong: ["Each is a cheese", "Each is a dance", "Each is a kind of boat"] },
  { words: ["BARGE", "YACHT", "CANOE"], answer: "Each is a boat", wrong: ["Each is a cheese", "Each is a dance", "Each is a fabric"] },
  { words: ["ANVIL", "HAMMER", "STIRRUP"], answer: "Each is a bone in the ear", wrong: ["Each is a chess term", "Each is a card game", "Each is a sailing word"] },
  { words: ["TITAN", "EUROPA", "PHOBOS"], answer: "Each is a moon", wrong: ["Each is a Greek god", "Each is a planet", "Each is a star"] },
  { words: ["ASCOT", "CRAVAT", "BOLO"], answer: "Each is a kind of tie", wrong: ["Each is a cheese", "Each is a dance", "Each is a kind of boat"] },
  { words: ["BEIGE", "TAUPE", "KHAKI"], answer: "Each is a shade of brown", wrong: ["Each is a dance", "Each is a cheese", "Each is a river"] },
  { words: ["GRAVITY", "LIFT", "DRAG"], answer: "Each is a force on an aircraft", wrong: ["Each is a chess term", "Each is a card game", "Each is a kind of race"] },
  { words: ["ROUGH", "GREEN", "BUNKER"], answer: "Each is part of a golf course", wrong: ["Each is a kind of bread", "Each is a card game", "Each is a dance"] },
  { words: ["SERVE", "VOLLEY", "LOB"], answer: "Each is a tennis shot", wrong: ["Each is a card game", "Each is a dance", "Each is a cheese"] },
  { words: ["STRIKE", "SPARE", "GUTTER"], answer: "Each is a bowling term", wrong: ["Each is a kind of bread", "Each is a dance", "Each is a cheese"] },
  { words: ["PUCK", "STICK", "NET"], answer: "Each is used in hockey", wrong: ["Each is a card game", "Each is a cheese", "Each is a dance"] },
  { words: ["SCRUM", "TRY", "RUCK"], answer: "Each is a rugby term", wrong: ["Each is a kind of bread", "Each is a dance", "Each is a cheese"] },
  { words: ["FLUSH", "STRAIGHT", "PAIR"], answer: "Each is a poker hand", wrong: ["Each is a kind of bread", "Each is a dance", "Each is a cheese"] }
];
