// Splice puzzles.
//
// Each puzzle has:
//   clues  - two clues, one for each word
//   parts  - the two words, in capitals. The end of the first must match the start of
//            the second (DRUM and UMBRELLA share "UM").
//   answer - the two words blended into one where they overlap (DRUMBRELLA)
//
// Every game picks five of these at random. All puzzles must be original.

window.SPLICE_PUZZLES = [
  { clues: ["You hit it with sticks", "It keeps the rain off"], parts: ["DRUM", "UMBRELLA"], answer: "DRUMBRELLA" },
  { clues: ["A big cousin of the violin, played seated", "Seafood with claws"], parts: ["CELLO", "LOBSTER"], answer: "CELLOBSTER" },
  { clues: ["It has 88 keys", "A long work of fiction"], parts: ["PIANO", "NOVEL"], answer: "PIANOVEL" },
  { clues: ["A red salad fruit", "A warty amphibian"], parts: ["TOMATO", "TOAD"], answer: "TOMATOAD" },
  { clues: ["A yellow fruit you peel", "She minds the children"], parts: ["BANANA", "NANNY"], answer: "BANANANNY" },
  { clues: ["A black and white bear", "A small white flower"], parts: ["PANDA", "DAISY"], answer: "PANDAISY" },
  { clues: ["It hops and has a pouch", "It crows at dawn"], parts: ["KANGAROO", "ROOSTER"], answer: "KANGAROOSTER" },
  { clues: ["A six-string instrument", "A Scottish checked cloth"], parts: ["GUITAR", "TARTAN"], answer: "GUITARTAN" },
  { clues: ["An orange root vegetable", "A big black-and-tan guard dog"], parts: ["CARROT", "ROTTWEILER"], answer: "CARROTTWEILER" },
  { clues: ["A big orange squash", "To light a fire"], parts: ["PUMPKIN", "KINDLE"], answer: "PUMPKINDLE" },
  { clues: ["A machine that does tasks for you", "Milk comes in one"], parts: ["ROBOT", "BOTTLE"], answer: "ROBOTTLE" },
  { clues: ["A pink fish that swims upstream", "It swings through the trees"], parts: ["SALMON", "MONKEY"], answer: "SALMONKEY" },
  { clues: ["A nut in a hard, wrinkled shell", "A spice grated onto eggnog"], parts: ["WALNUT", "NUTMEG"], answer: "WALNUTMEG" },
  { clues: ["A spring flower from Holland", "Red colour for your mouth"], parts: ["TULIP", "LIPSTICK"], answer: "TULIPSTICK" },
  { clues: ["A spiky desert plant", "An elephant's long tooth"], parts: ["CACTUS", "TUSK"], answer: "CACTUSK" },
  { clues: ["A brass instrument", "Part of a flower"], parts: ["TRUMPET", "PETAL"], answer: "TRUMPETAL" },
  { clues: ["A bird with a pouch under its beak", "Wax with a wick"], parts: ["PELICAN", "CANDLE"], answer: "PELICANDLE" },
  { clues: ["A talking bird", "To turn around"], parts: ["PARROT", "ROTATE"], answer: "PARROTATE" },
  { clues: ["A desert animal with humps", "A big juicy fruit"], parts: ["CAMEL", "MELON"], answer: "CAMELON" },
  { clues: ["A striped big cat", "A small pet rodent"], parts: ["TIGER", "GERBIL"], answer: "TIGERBIL" },
  { clues: ["A sour yellow fruit", "A scary creature"], parts: ["LEMON", "MONSTER"], answer: "LEMONSTER" },
  { clues: ["A griddled breakfast cake with squares", "A sheep's woolly coat"], parts: ["WAFFLE", "FLEECE"], answer: "WAFFLEECE" },
  { clues: ["A couch", "A tiny magical being with wings"], parts: ["SOFA", "FAIRY"], answer: "SOFAIRY" },
  { clues: ["A peppery red root", "It cleans the plates"], parts: ["RADISH", "DISHWASHER"], answer: "RADISHWASHER" },
  { clues: ["A tropical orange fruit", "A mischievous ugly creature"], parts: ["MANGO", "GOBLIN"], answer: "MANGOBLIN" },
  { clues: ["It drives in nails", "Half woman, half fish"], parts: ["HAMMER", "MERMAID"], answer: "HAMMERMAID" },
  { clues: ["Played with a bow", "A flat pasta ribbon"], parts: ["VIOLIN", "LINGUINE"], answer: "VIOLINGUINE" },
  { clues: ["A cucumber kept in brine", "A big-eyed primate from Madagascar"], parts: ["PICKLE", "LEMUR"], answer: "PICKLEMUR" },
  { clues: ["It fastens a shirt", "You taste with it"], parts: ["BUTTON", "TONGUE"], answer: "BUTTONGUE" },
  { clues: ["It covers the floor", "A trumpet-shaped garden flower"], parts: ["CARPET", "PETUNIA"], answer: "CARPETUNIA" },
  { clues: ["A horned animal with thick skin", "A long pasta strand"], parts: ["RHINO", "NOODLE"], answer: "RHINOODLE" },
  { clues: ["A big ape", "A woolly South American animal"], parts: ["GORILLA", "LLAMA"], answer: "GORILLAMA" },
  { clues: ["It lays eggs", "A dog's little house"], parts: ["CHICKEN", "KENNEL"], answer: "CHICKENNEL" },
  { clues: ["A bushy-tailed nut collector", "A tangy sauce for hot dogs"], parts: ["SQUIRREL", "RELISH"], answer: "SQUIRRELISH" },
  { clues: ["A wrapped head covering", "A twangy stringed instrument"], parts: ["TURBAN", "BANJO"], answer: "TURBANJO" },
  { clues: ["A round leafy vegetable", "A spy"], parts: ["CABBAGE", "AGENT"], answer: "CABBAGENT" },
  { clues: ["A small cake baked in a paper cup", "A small songbird"], parts: ["MUFFIN", "FINCH"], answer: "MUFFINCH" },
  { clues: ["A dam-building rodent", "A covered porch"], parts: ["BEAVER", "VERANDA"], answer: "BEAVERANDA" },
  { clues: ["A striped horse", "A shout of praise"], parts: ["ZEBRA", "BRAVO"], answer: "ZEBRAVO" },
  { clues: ["A hard hat for a cyclist", "It ticks a steady beat for musicians"], parts: ["HELMET", "METRONOME"], answer: "HELMETRONOME" },
  { clues: ["A long-eared farm animal", "You type on it"], parts: ["DONKEY", "KEYBOARD"], answer: "DONKEYBOARD" },
  { clues: ["A root vegetable for chips", "It browns bread"], parts: ["POTATO", "TOASTER"], answer: "POTATOASTER" },
  { clues: ["An open summer shoe", "A spotted dog"], parts: ["SANDAL", "DALMATIAN"], answer: "SANDALMATIAN" },
  { clues: ["A spice that makes you sneeze", "A sweet-smelling scent"], parts: ["PEPPER", "PERFUME"], answer: "PEPPERFUME" },
  { clues: ["A hairy tropical nut", "A tool for opening nuts, or a ballet"], parts: ["COCONUT", "NUTCRACKER"], answer: "COCONUTCRACKER" },
  { clues: ["You dry off with it", "A friendly greeting"], parts: ["TOWEL", "WELCOME"], answer: "TOWELCOME" },
  { clues: ["It takes photographs", "It rubs out pencil marks"], parts: ["CAMERA", "ERASER"], answer: "CAMERASER" },
  { clues: ["A whining, biting insect", "A chewy brown sweet"], parts: ["MOSQUITO", "TOFFEE"], answer: "MOSQUITOFFEE" },
  { clues: ["A tusked Arctic sea animal", "Covered in orange flakes of corrosion"], parts: ["WALRUS", "RUSTY"], answer: "WALRUSTY" },
  { clues: ["A large stinging wasp", "A plant that stings"], parts: ["HORNET", "NETTLE"], answer: "HORNETTLE" },
  { clues: ["A snapping river reptile", "A tricky choice"], parts: ["CROCODILE", "DILEMMA"], answer: "CROCODILEMMA" },
  { clues: ["A big shaggy prairie animal", "A spiky plant with soothing gel"], parts: ["BUFFALO", "ALOE"], answer: "BUFFALOE" },
  { clues: ["A leafy green that made a sailor strong", "A dull pain"], parts: ["SPINACH", "ACHE"], answer: "SPINACHE" },
  { clues: ["It floats and pops", "Canada's one-dollar coin"], parts: ["BALLOON", "LOONIE"], answer: "BALLOONIE" },
  { clues: ["A fish that comes in cans", "It wipes your mouth at dinner"], parts: ["TUNA", "NAPKIN"], answer: "TUNAPKIN" },
  { clues: ["A space rock with a glowing tail", "Iron or gold"], parts: ["COMET", "METAL"], answer: "COMETAL" },
  { clues: ["You stay there on holiday", "It brings the stars closer"], parts: ["HOTEL", "TELESCOPE"], answer: "HOTELESCOPE" },
  { clues: ["A playful river animal", "A raised outdoor patio"], parts: ["OTTER", "TERRACE"], answer: "OTTERRACE" },
  { clues: ["The tallest animal", "Fondness"], parts: ["GIRAFFE", "AFFECTION"], answer: "GIRAFFECTION" },
  { clues: ["Soft chewy toffee", "A tune"], parts: ["CARAMEL", "MELODY"], answer: "CARAMELODY" },
  { clues: ["A seabird with a colourful beak", "To end"], parts: ["PUFFIN", "FINISH"], answer: "PUFFINISH" },
  // ---- Added 9 October 2026 ----
  { clues: ["A talking bird", "A playful river swimmer"], parts: ["PARROT", "OTTER"], answer: "PARROTTER" },
  { clues: ["A desert animal with humps", "The joint in the middle of your arm"], parts: ["CAMEL", "ELBOW"], answer: "CAMELBOW" },
  { clues: ["A woolly South American animal", "It attracts iron"], parts: ["LLAMA", "MAGNET"], answer: "LLAMAGNET" },
  { clues: ["It carries its home on its back", "A sour yellow fruit"], parts: ["TURTLE", "LEMON"], answer: "TURTLEMON" },
  { clues: ["A bird in a tuxedo", "A six-legged creature"], parts: ["PENGUIN", "INSECT"], answer: "PENGUINSECT" },
  { clues: ["It has eight arms", "Someone who shows you to your seat"], parts: ["OCTOPUS", "USHER"], answer: "OCTOPUSHER" },
  { clues: ["A bug with a hard shell", "Green leaves in a salad"], parts: ["BEETLE", "LETTUCE"], answer: "BEETLETTUCE" },
  { clues: ["It spins a web", "A famous horse race"], parts: ["SPIDER", "DERBY"], answer: "SPIDERBY" },
  { clues: ["You can ride it", "Something you must not tell"], parts: ["HORSE", "SECRET"], answer: "HORSECRET" },
  { clues: ["A tiny squeaker", "Spring, summer, autumn or winter"], parts: ["MOUSE", "SEASON"], answer: "MOUSEASON" },
  { clues: ["A big black-and-white cat", "A man living alone in the wild"], parts: ["PANTHER", "HERMIT"], answer: "PANTHERMIT" },
  { clues: ["A striped digger with a black-and-white face", "A flower with bright red clusters"], parts: ["BADGER", "GERANIUM"], answer: "BADGERANIUM" },
  { clues: ["A long, thin pet that loves tunnels", "The back of your eye"], parts: ["FERRET", "RETINA"], answer: "FERRETINA" },
  { clues: ["A small shellfish, pink when cooked", "An African antelope"], parts: ["SHRIMP", "IMPALA"], answer: "SHRIMPALA" },
  { clues: ["A sleepy Australian in a gum tree", "Melted rock from a volcano"], parts: ["KOALA", "LAVA"], answer: "KOALAVA" },
  { clues: ["A bird with a huge colourful beak", "A deep valley with steep sides"], parts: ["TOUCAN", "CANYON"], answer: "TOUCANYON" },
  { clues: ["A huge animal with wide antlers", "A playground plank that goes up and down"], parts: ["MOOSE", "SEESAW"], answer: "MOOSEESAW" },
  { clues: ["The bird on the Thanksgiving table", "You put a key in it"], parts: ["TURKEY", "KEYHOLE"], answer: "TURKEYHOLE" },
  { clues: ["A shaggy buffalo of the plains", "A fourteen-line poem"], parts: ["BISON", "SONNET"], answer: "BISONNET" },
  { clues: ["A snake with a hood", "A limb of a tree"], parts: ["COBRA", "BRANCH"], answer: "COBRANCH" },
  { clues: ["A giant snake that squeezes", "Bees make it"], parts: ["PYTHON", "HONEY"], answer: "PYTHONEY" },
  { clues: ["A lizard that climbs walls", "A sleepy Australian in a gum tree"], parts: ["GECKO", "KOALA"], answer: "GECKOALA" },
  { clues: ["A big green lizard", "A word made by mixing up the letters of another"], parts: ["IGUANA", "ANAGRAM"], answer: "IGUANAGRAM" },
  { clues: ["A laughing scavenger", "The sea-going armed forces"], parts: ["HYENA", "NAVY"], answer: "HYENAVY" },
  { clues: ["A spotted big cat of the Americas", "A knight's metal suit"], parts: ["JAGUAR", "ARMOUR"], answer: "JAGUARMOUR" },
  { clues: ["A stocky Australian burrower", "It powers a torch"], parts: ["WOMBAT", "BATTERY"], answer: "WOMBATTERY" },
  { clues: ["The slowest animal in the trees", "The rumble after lightning"], parts: ["SLOTH", "THUNDER"], answer: "SLOTHUNDER" },
  { clues: ["A small pet that runs in a wheel", "Music from two speakers"], parts: ["HAMSTER", "STEREO"], answer: "HAMSTEREO" },
  { clues: ["A masked animal that raids bins", "It makes you cry when you chop it"], parts: ["RACCOON", "ONION"], answer: "RACCOONION" },
  { clues: ["A shellfish with claws, smaller than a lobster", "Not here"], parts: ["CRAB", "ABSENT"], answer: "CRABSENT" },
  { clues: ["A shellfish like a big shrimp", "A canvas roof over a shop window"], parts: ["PRAWN", "AWNING"], answer: "PRAWNING" },
  { clues: ["A graceful white bird with a long neck", "To walk about with no aim"], parts: ["SWAN", "WANDER"], answer: "SWANDER" },
  { clues: ["A big black bird in a spooky poem", "The place where an event is held"], parts: ["RAVEN", "VENUE"], answer: "RAVENUE" },
  { clues: ["A fast bird of prey", "A live music performance"], parts: ["FALCON", "CONCERT"], answer: "FALCONCERT" },
  { clues: ["The biggest bird, and it cannot fly", "A hot pepper"], parts: ["OSTRICH", "CHILLI"], answer: "OSTRICHILLI" },
  { clues: ["A tall Australian bird that cannot fly", "A building full of old treasures"], parts: ["EMU", "MUSEUM"], answer: "EMUSEUM" },
  { clues: ["A fuzzy brown fruit, or a New Zealand bird", "A domed tent of poles and bark"], parts: ["KIWI", "WIGWAM"], answer: "KIWIGWAM" },
  { clues: ["The king of the jungle", "It makes you cry when you chop it"], parts: ["LION", "ONION"], answer: "LIONION" },
  { clues: ["A big furry animal that hibernates", "It is shot from a bow"], parts: ["BEAR", "ARROW"], answer: "BEARROW" },
  { clues: ["An animal with antlers", "It rubs out pencil marks"], parts: ["DEER", "ERASER"], answer: "DEERASER" },
  { clues: ["It barks and balances a ball on its nose", "A nut used in marzipan"], parts: ["SEAL", "ALMOND"], answer: "SEALMOND" },
  { clues: ["A fluffy cousin of the llama", "It takes photographs"], parts: ["ALPACA", "CAMERA"], answer: "ALPACAMERA" },
  { clues: ["It has horns and a beard", "A book of maps"], parts: ["GOAT", "ATLAS"], answer: "GOATLAS" },
  { clues: ["You brew in it", "A magic drink"], parts: ["TEAPOT", "POTION"], answer: "TEAPOTION" },
  { clues: ["Wax with a wick", "A book of accounts"], parts: ["CANDLE", "LEDGER"], answer: "CANDLEDGER" },
  { clues: ["You rest your head on it", "A night bird that hoots"], parts: ["PILLOW", "OWL"], answer: "PILLOWL" },
  { clues: ["You see yourself in it", "The path of a satellite round a planet"], parts: ["MIRROR", "ORBIT"], answer: "MIRRORBIT" },
  { clues: ["Woven to carry shopping", "Red sauce for chips"], parts: ["BASKET", "KETCHUP"], answer: "BASKETCHUP" },
  { clues: ["It blasts off into space", "It boils water for tea"], parts: ["ROCKET", "KETTLE"], answer: "ROCKETTLE" },
  { clues: ["Where flowers and vegetables grow", "The person who fixes your teeth"], parts: ["GARDEN", "DENTIST"], answer: "GARDENTIST" },
  { clues: ["A small wooden house in the woods", "The list at the back of a book"], parts: ["CABIN", "INDEX"], answer: "CABINDEX" },
  { clues: ["Lettuce, tomato and cucumber in a bowl", "You climb it to reach the roof"], parts: ["SALAD", "LADDER"], answer: "SALADDER" },
  { clues: ["You spread it on toast", "A small, lively breed of dog"], parts: ["BUTTER", "TERRIER"], answer: "BUTTERRIER" },
  { clues: ["Made from milk, and good on crackers", "It barks and balances a ball on its nose"], parts: ["CHEESE", "SEAL"], answer: "CHEESEAL" },
  { clues: ["It makes things sweet", "A curved opening in a wall"], parts: ["SUGAR", "ARCH"], answer: "SUGARCH" },
  { clues: ["Bees make it", "A hair on the edge of your eyelid"], parts: ["HONEY", "EYELASH"], answer: "HONEYELASH" },
  { clues: ["Eggs beaten and fried flat", "What you post in an envelope"], parts: ["OMELET", "LETTER"], answer: "OMELETTER" },
  { clues: ["A chewy bread ring", "The biggest animal with a trunk"], parts: ["BAGEL", "ELEPHANT"], answer: "BAGELEPHANT" },
  { clues: ["A folded Mexican shell with a filling", "A snake with a hood"], parts: ["TACO", "COBRA"], answer: "TACOBRA" },
  { clues: ["A fruit that grows in bunches on a vine", "The very top, the highest point"], parts: ["GRAPE", "APEX"], answer: "GRAPEX" },
  { clues: ["A small orange fruit with a stone", "A small house in the country"], parts: ["APRICOT", "COTTAGE"], answer: "APRICOTTAGE" },
  { clues: ["A game played with rackets in a walled court", "A dish for cigarette ends"], parts: ["SQUASH", "ASHTRAY"], answer: "SQUASHTRAY" },
  { clues: ["Where the trees are thick", "Where you order a meal"], parts: ["FOREST", "RESTAURANT"], answer: "FORESTAURANT" },
  { clues: ["The deep blue sea", "It holds a ship in place"], parts: ["OCEAN", "ANCHOR"], answer: "OCEANCHOR" },
  { clues: ["Earth is one", "Computers linked together"], parts: ["PLANET", "NETWORK"], answer: "PLANETWORK" },
  { clues: ["A fire-breathing beast of legend", "A long narrow boat of Venice"], parts: ["DRAGON", "GONDOLA"], answer: "DRAGONDOLA" },
  { clues: ["A horse with one horn", "A small brass trumpet"], parts: ["UNICORN", "CORNET"], answer: "UNICORNET" },
  { clues: ["A ghost, or the masked man of the opera", "Red and round in a salad"], parts: ["PHANTOM", "TOMATO"], answer: "PHANTOMATO" },
  { clues: ["You sit on it", "Where planes take off"], parts: ["CHAIR", "AIRPORT"], answer: "CHAIRPORT" },
  { clues: ["It lights a room", "It makes a guitar louder"], parts: ["LAMP", "AMPLIFIER"], answer: "LAMPLIFIER" },
  { clues: ["Worn on a hand in winter", "A game with rackets and a net"], parts: ["MITTEN", "TENNIS"], answer: "MITTENNIS" },
  { clues: ["It fastens a jacket with a pull", "A human being"], parts: ["ZIPPER", "PERSON"], answer: "ZIPPERSON" },
  { clues: ["You write with it", "A herb used in Mexican cooking"], parts: ["PENCIL", "CILANTRO"], answer: "PENCILANTRO" },
  { clues: ["A flaming stick, or a flashlight", "Where apple trees grow"], parts: ["TORCH", "ORCHARD"], answer: "TORCHARD" },
  { clues: ["A passage dug through a hill", "A tiny helper with pointed ears"], parts: ["TUNNEL", "ELF"], answer: "TUNNELF" },
  { clues: ["A grassy field full of wildflowers", "A night bird that hoots"], parts: ["MEADOW", "OWL"], answer: "MEADOWL" }
];
