// Daily puzzle schedule for 2026. Made by: node tools/make-daily.js 2026
// One line per day. Day 1 is January 1. Each puzzle is named by its key (see shared/keys.js).
// Do not edit by hand: past days should stay as they were.
window.DAILY_SCHEDULE = window.DAILY_SCHEDULE || {};
window.DAILY_SCHEDULE[2026] = [
  ["CAN","ART","NOSE","RAIN","PEA"],  // 1 · Jan 1
  ["HOP","RIDE","ARM","BAR","PAT"],  // 2 · Jan 2
  ["ANT","FIT","MEAL","LIE","WIG"],  // 3 · Jan 3
  ["GRIN","PAIN","COAT","CAT","RAM"],  // 4 · Jan 4
  ["CASH","HOST","HOSE","BUN","LAND"],  // 5 · Jan 5
  ["CUB","TON","INK","PLAN","BEAD"],  // 6 · Jan 6
  ["TEA","MEN","RIB","BARE","CAP"],  // 7 · Jan 7
  ["NEW","LAW","FAST","HAM","TEN"],  // 8 · Jan 8
  ["MOTH","TRAY","OIL","FEW","STAR"],  // 9 · Jan 9
  ["FIN","LAMP","ICE","SHED","OWN"],  // 10 · Jan 10
  ["EAT","ELF","ROD","GOAT","WIN"],  // 11 · Jan 11
  ["SPIN","PIE","OWL","TIN","EAR"],  // 12 · Jan 12
  ["SEAT","OAK","MAT","BAND","SEA"],  // 13 · Jan 13
  ["PIT","PEN","BAT","BELL","SOCK"],  // 14 · Jan 14
  ["PAW","HAT","RAT","BET","ROT"],  // 15 · Jan 15
  ["NET","BOW","RUN","SIGH","TAP"],  // 16 · Jan 16
  ["HEN","TIE","FOG","FORT","BOAT"],  // 17 · Jan 17
  ["BEAR","CAMP","CORD","WAR","SON"],  // 18 · Jan 18
  ["CAR","CROW","TIE","BEAR","CUB"],  // 19 · Jan 19
  ["PLAN","ROD","HAT","PEN","WAR"],  // 20 · Jan 20
  ["NEW","ANT","INK","TRAY","RIB"],  // 21 · Jan 21
  ["WIN","EAR","OWN","SEAT","BET"],  // 22 · Jan 22
  ["BOAT","PAT","CAN","BEAD","HOSE"],  // 23 · Jan 23
  ["CAMP","FAST","CAR","CASH","MOTH"],  // 24 · Jan 24
  ["CAP","ART","WIG","GOAT","FIT"],  // 25 · Jan 25
  ["MAT","ICE","ELF","SON","STAR"],  // 26 · Jan 26
  ["SHED","OWL","HAM","BAR","FORT"],  // 27 · Jan 27
  ["TIN","FOG","RIDE","TON","BELL"],  // 28 · Jan 28
  ["PIE","GRIN","HEN","LAMP","BOW"],  // 29 · Jan 29
  ["HOST","BUN","HOP","PAIN","OIL"],  // 30 · Jan 30
  ["PEA","SEA","TEA","PAW","FIN"],  // 31 · Jan 31
  ["ROT","BARE","ARM","CORD","CROW"],  // 32 · Feb 1
  ["TEN","COAT","BAT","EAT","TAP"],  // 33 · Feb 2
  ["FEW","RAIN","OAK","BAND","PIT"],  // 34 · Feb 3
  ["SOCK","CAT","RUN","RAT","SPIN"],  // 35 · Feb 4
  ["NOSE","MEAL","RAM","SIGH","NET"],  // 36 · Feb 5
  ["LAND","LIE","MEN","LAW","ROD"],  // 37 · Feb 6
  ["TIN","SON","WAR","HAM","MAT"],  // 38 · Feb 7
  ["CAP","BAT","BEAD","CAMP","PLAN"],  // 39 · Feb 8
  ["WIN","HOST","LIE","RIDE","CORD"],  // 40 · Feb 9
  ["CROW","RIB","FIN","TRAY","SOCK"],  // 41 · Feb 10
  ["PEA","NEW","FIT","OIL","TAP"],  // 42 · Feb 11
  ["STAR","BARE","TIE","OAK","COAT"],  // 43 · Feb 12
  ["HEN","PIE","RAM","RAT","CUB"],  // 44 · Feb 13
  ["PEN","FORT","BOAT","ARM","PIT"],  // 45 · Feb 14
  ["BOW","WIG","ROT","SEA","GOAT"],  // 46 · Feb 15
  ["SPIN","BUN","PAW","HAT","LAND"],  // 47 · Feb 16
  ["RAIN","TEN","TEA","FAST","SHED"],  // 48 · Feb 17
  ["LAMP","INK","FOG","BET","CAR"],  // 49 · Feb 18
  ["RUN","BAR","PAIN","ICE","ART"],  // 50 · Feb 19
  ["BELL","SIGH","MEN","OWN","BAND"],  // 51 · Feb 20
  ["CAN","CAT","SEAT","ELF","EAT"],  // 52 · Feb 21
  ["ANT","MOTH","NOSE","HOP","BEAR"],  // 53 · Feb 22
  ["GRIN","CASH","OWL","LAW","MEAL"],  // 54 · Feb 23
  ["PAT","EAR","TON","FEW","HOSE"],  // 55 · Feb 24
  ["NET","STAR","SOCK","HAT","SEA"],  // 56 · Feb 25
  ["MOTH","RAIN","TON","WIN","LAMP"],  // 57 · Feb 26
  ["BUN","TEA","OIL","SON","OAK"],  // 58 · Feb 27
  ["ROD","RAT","RIDE","PLAN","PAIN"],  // 59 · Feb 28
  ["FIN","HAM","ARM","TAP","SPIN"],  // 60 · Mar 1
  ["BELL","PIE","FOG","CROW","MEN"],  // 61 · Mar 2
  ["PEA","BOAT","OWL","SHED","RAM"],  // 62 · Mar 3
  ["CAN","BET","TRAY","LAND","LAW"],  // 63 · Mar 4
  ["BEAR","ICE","HOSE","BEAD","MEAL"],  // 64 · Mar 5
  ["ELF","RUN","HOST","OWN","PIT"],  // 65 · Mar 6
  ["ROT","FEW","SIGH","CAMP","TIE"],  // 66 · Mar 7
  ["LIE","GOAT","PAW","FAST","TIN"],  // 67 · Mar 8
  ["ANT","BARE","ART","CAP","FIT"],  // 68 · Mar 9
  ["NET","BAT","SEAT","BOW","PEN"],  // 69 · Mar 10
  ["GRIN","PAT","COAT","BAND","CAT"],  // 70 · Mar 11
  ["HEN","EAR","NEW","HOP","BAR"],  // 71 · Mar 12
  ["NOSE","CAR","CORD","RIB","MAT"],  // 72 · Mar 13
  ["CASH","WIG","EAT","INK","CUB"],  // 73 · Mar 14
  ["TEN","FORT","WAR","SEAT","SIGH"],  // 74 · Mar 15
  ["SEA","TIE","ART","SON","PAT"],  // 75 · Mar 16
  ["CUB","NEW","FOG","STAR","BELL"],  // 76 · Mar 17
  ["MOTH","OWL","COAT","BAR","TEN"],  // 77 · Mar 18
  ["PAIN","BEAR","CORD","ROD","WIN"],  // 78 · Mar 19
  ["PIE","GRIN","RIB","RUN","LIE"],  // 79 · Mar 20
  ["LAW","BUN","TEA","BEAD","OIL"],  // 80 · Mar 21
  ["SPIN","BAND","WAR","ARM","PAW"],  // 81 · Mar 22
  ["BARE","PLAN","BOW","INK","EAT"],  // 82 · Mar 23
  ["FEW","FIN","OAK","CASH","MEAL"],  // 83 · Mar 24
  ["HEN","GOAT","NET","HOP","CAMP"],  // 84 · Mar 25
  ["PEN","BET","BAT","RAIN","BOAT"],  // 85 · Mar 26
  ["NOSE","CAR","ICE","CROW","LAND"],  // 86 · Mar 27
  ["HOST","PEA","FAST","MEN","HOSE"],  // 87 · Mar 28
  ["TAP","WIG","TIN","HAT","CAN"],  // 88 · Mar 29
  ["CAP","FIT","SHED","LAMP","ELF"],  // 89 · Mar 30
  ["PIT","ANT","EAR","RAT","ROT"],  // 90 · Mar 31
  ["MAT","OWN","RAM","TRAY","HAM"],  // 91 · Apr 1
  ["TON","FORT","RIDE","SOCK","CAT"],  // 92 · Apr 2
  ["ROT","ANT","WIN","BAR","BET"],  // 93 · Apr 3
  ["BUN","RAT","NOSE","BEAR","CAR"],  // 94 · Apr 4
  ["RAIN","CORD","MEN","SIGH","LAW"],  // 95 · Apr 5
  ["ICE","TEA","FEW","HAT","PEA"],  // 96 · Apr 6
  ["RIDE","RIB","LAMP","PIE","PLAN"],  // 97 · Apr 7
  ["RUN","CAN","NET","CUB","ROD"],  // 98 · Apr 8
  ["LIE","RAM","PAT","ELF","TIE"],  // 99 · Apr 9
  ["COAT","HEN","NEW","ARM","CAMP"],  // 100 · Apr 10
  ["GOAT","TON","OIL","MEAL","PIT"],  // 101 · Apr 11
  ["WAR","HOST","OWL","ART","BAT"],  // 102 · Apr 12
  ["SHED","MAT","PAW","STAR","INK"],  // 103 · Apr 13
  ["HAM","PEN","MOTH","CAT","BAND"],  // 104 · Apr 14
  ["SPIN","BOAT","SON","FIT","FORT"],  // 105 · Apr 15
  ["BEAD","BARE","CASH","BELL","OAK"],  // 106 · Apr 16
  ["TAP","EAT","CAP","CROW","HOSE"],  // 107 · Apr 17
  ["OWN","GRIN","WIG","FOG","LAND"],  // 108 · Apr 18
  ["TRAY","SOCK","FIN","FAST","SEAT"],  // 109 · Apr 19
  ["HOP","SEA","TIN","PAIN","TEN"],  // 110 · Apr 20
  ["EAR","BOW","FOG","WIG","TON"],  // 111 · Apr 21
  ["BAND","BOAT","OWL","BOW","RAIN"],  // 112 · Apr 22
  ["BAR","EAT","ROD","CAT","ARM"],  // 113 · Apr 23
  ["CUB","NOSE","SIGH","PEA","BUN"],  // 114 · Apr 24
  ["HAT","MOTH","PIE","GRIN","MAT"],  // 115 · Apr 25
  ["SON","ANT","CORD","WAR","RAM"],  // 116 · Apr 26
  ["BARE","CASH","LAW","RIDE","FEW"],  // 117 · Apr 27
  ["FIT","OWN","TIN","ICE","CAN"],  // 118 · Apr 28
  ["HOSE","MEAL","SPIN","PIT","EAR"],  // 119 · Apr 29
  ["CROW","LIE","HAM","ELF","MEN"],  // 120 · Apr 30
  ["FIN","BAT","OIL","BELL","SHED"],  // 121 · May 1
  ["FORT","BEAD","ROT","INK","SEAT"],  // 122 · May 2
  ["HEN","SOCK","TEA","BET","TIE"],  // 123 · May 3
  ["RIB","STAR","RUN","PAT","TEN"],  // 124 · May 4
  ["FAST","TAP","LAND","CAMP","PLAN"],  // 125 · May 5
  ["GOAT","TRAY","SEA","PEN","COAT"],  // 126 · May 6
  ["PAW","RAT","NET","HOP","OAK"],  // 127 · May 7
  ["CAR","PAIN","BEAR","ART","WIN"],  // 128 · May 8
  ["LAMP","HOST","NEW","CAP","WIN"],  // 129 · May 9
  ["TRAY","SEAT","ARM","BAND","TIE"],  // 130 · May 10
  ["CORD","BELL","HOP","TEN","CAN"],  // 131 · May 11
  ["RAT","HOSE","PAT","OAK","OWN"],  // 132 · May 12
  ["FIT","NOSE","RIDE","BOW","TAP"],  // 133 · May 13
  ["ICE","MOTH","SPIN","OWL","ANT"],  // 134 · May 14
  ["ROT","MEAL","SIGH","FEW","STAR"],  // 135 · May 15
  ["CASH","CAP","TIN","FOG","PEN"],  // 136 · May 16
  ["RAM","PEA","EAT","BUN","CAR"],  // 137 · May 17
  ["BEAR","PIE","BET","GOAT","WIG"],  // 138 · May 18
  ["ELF","FAST","HEN","SEA","BOAT"],  // 139 · May 19
  ["FORT","RAIN","HAM","BEAD","LAW"],  // 140 · May 20
  ["FIN","ROD","BAT","SON","HOST"],  // 141 · May 21
  ["CAMP","MAT","CAT","WAR","PAW"],  // 142 · May 22
  ["HAT","COAT","LAMP","ART","PLAN"],  // 143 · May 23
  ["NET","LAND","EAR","INK","BARE"],  // 144 · May 24
  ["NEW","CROW","TEA","MEN","TON"],  // 145 · May 25
  ["GRIN","SOCK","CUB","RIB","SHED"],  // 146 · May 26
  ["RUN","BAR","OIL","PIT","PAIN"],  // 147 · May 27
  ["LIE","WIG","HEN","NOSE","CAR"],  // 148 · May 28
  ["CAN","MAT","RAT","WIN","NET"],  // 149 · May 29
  ["GOAT","CAT","TRAY","FOG","ROT"],  // 150 · May 30
  ["NEW","CAP","MEAL","PIE","COAT"],  // 151 · May 31
  ["SPIN","SIGH","HAM","ELF","ART"],  // 152 · Jun 1
  ["ROD","HOP","OAK","HOST","SHED"],  // 153 · Jun 2
  ["CASH","BARE","BELL","ARM","RIB"],  // 154 · Jun 3
  ["ICE","PAW","INK","PAIN","RAM"],  // 155 · Jun 4
  ["EAR","SEAT","CORD","LIE","BUN"],  // 156 · Jun 5
  ["BEAR","MEN","TEA","CROW","TIE"],  // 157 · Jun 6
  ["MOTH","LAW","TIN","BEAD","PLAN"],  // 158 · Jun 7
  ["GRIN","TON","SOCK","LAMP","RUN"],  // 159 · Jun 8
  ["FIN","BOW","SON","HOSE","TEN"],  // 160 · Jun 9
  ["CAMP","RIDE","BET","PAT","OWN"],  // 161 · Jun 10
  ["FORT","SEA","FEW","PIT","HAT"],  // 162 · Jun 11
  ["PEN","LAND","CUB","BAND","WAR"],  // 163 · Jun 12
  ["FAST","FIT","ANT","BAR","PEA"],  // 164 · Jun 13
  ["OWL","RAIN","OIL","TAP","BOAT"],  // 165 · Jun 14
  ["EAT","BAT","STAR","PEA","CROW"],  // 166 · Jun 15
  ["SOCK","BEAR","OAK","WAR","GOAT"],  // 167 · Jun 16
  ["TIN","WIG","GRIN","RAT","FAST"],  // 168 · Jun 17
  ["HOSE","ICE","NOSE","BAR","CORD"],  // 169 · Jun 18
  ["ROT","HOST","BARE","ANT","SEAT"],  // 170 · Jun 19
  ["RIDE","INK","MEN","ROD","PAT"],  // 171 · Jun 20
  ["FORT","RUN","PLAN","PIE","EAR"],  // 172 · Jun 21
  ["SPIN","CAT","OIL","SIGH","ART"],  // 173 · Jun 22
  ["HEN","STAR","BOW","TON","WIN"],  // 174 · Jun 23
  ["PAIN","FEW","PIT","BET","FOG"],  // 175 · Jun 24
  ["TIE","BUN","CAP","TRAY","MAT"],  // 176 · Jun 25
  ["BAND","CUB","CAMP","LIE","COAT"],  // 177 · Jun 26
  ["HOP","TEN","LAMP","BOAT","CAR"],  // 178 · Jun 27
  ["FIT","RAIN","HAM","BEAD","OWL"],  // 179 · Jun 28
  ["NET","MOTH","EAT","OWN","NEW"],  // 180 · Jun 29
  ["BELL","RIB","SEA","RAM","HAT"],  // 181 · Jun 30
  ["TEA","PEN","LAW","SHED","CASH"],  // 182 · Jul 1
  ["ELF","BAT","MEAL","ARM","LAND"],  // 183 · Jul 2
  ["TAP","SON","PAW","FIN","CAN"],  // 184 · Jul 3
  ["RAIN","CAN","PEA","OWN","BOW"],  // 185 · Jul 4
  ["CAT","PLAN","ANT","TIN","HAT"],  // 186 · Jul 5
  ["ROD","BEAD","RIDE","PIE","HOST"],  // 187 · Jul 6
  ["HAM","BELL","INK","LIE","HOSE"],  // 188 · Jul 7
  ["OWL","CAP","HEN","CASH","COAT"],  // 189 · Jul 8
  ["LAND","SEA","TEA","CORD","CUB"],  // 190 · Jul 9
  ["CAR","OIL","SIGH","MEAL","FAST"],  // 191 · Jul 10
  ["EAR","SHED","RIB","TAP","NET"],  // 192 · Jul 11
  ["BEAR","GRIN","STAR","ROT","NOSE"],  // 193 · Jul 12
  ["RAM","SEAT","BAT","BOAT","SON"],  // 194 · Jul 13
  ["RAT","CROW","MAT","BAR","SPIN"],  // 195 · Jul 14
  ["FEW","LAMP","FIN","EAT","FOG"],  // 196 · Jul 15
  ["TEN","PAT","TIE","ELF","ICE"],  // 197 · Jul 16
  ["CAMP","FIT","PAIN","PIT","ART"],  // 198 · Jul 17
  ["BET","BAND","OAK","FORT","BUN"],  // 199 · Jul 18
  ["TON","MEN","LAW","WIN","GOAT"],  // 200 · Jul 19
  ["TRAY","HOP","RUN","WIG","PAW"],  // 201 · Jul 20
  ["BARE","SOCK","NEW","MOTH","WAR"],  // 202 · Jul 21
  ["PEN","ARM","BEAR","TEA","STAR"],  // 203 · Jul 22
  ["CAT","HEN","OIL","EAT","WIG"],  // 204 · Jul 23
  ["SON","PIE","PIT","OAK","WIN"],  // 205 · Jul 24
  ["CAN","BOAT","LAND","HAM","RIDE"],  // 206 · Jul 25
  ["HOP","CASH","FOG","PEA","TIE"],  // 207 · Jul 26
  ["ROD","GRIN","MAT","BAR","PLAN"],  // 208 · Jul 27
  ["PEN","PAW","BELL","TAP","RAM"],  // 209 · Jul 28
  ["TRAY","LIE","BUN","NOSE","ANT"],  // 210 · Jul 29
  ["GOAT","PAIN","TEN","FEW","HOSE"],  // 211 · Jul 30
  ["CROW","SEAT","SOCK","CAR","BOW"],  // 212 · Jul 31
  ["ICE","FIN","ROT","MEN","HOST"],  // 213 · Aug 1
  ["MEAL","INK","CAMP","OWL","COAT"],  // 214 · Aug 2
  ["TON","FIT","ARM","NEW","SPIN"],  // 215 · Aug 3
  ["RIB","BEAD","BAT","CAP","ELF"],  // 216 · Aug 4
  ["ART","BET","CORD","BARE","SHED"],  // 217 · Aug 5
  ["MOTH","TIN","PAT","RAIN","LAMP"],  // 218 · Aug 6
  ["NET","OWN","LAW","CUB","EAR"],  // 219 · Aug 7
  ["RAT","SIGH","SEA","BAND","HAT"],  // 220 · Aug 8
  ["RUN","WAR","FAST","FORT","RAIN"],  // 221 · Aug 9
  ["ART","HAM","STAR","OWL","PEN"],  // 222 · Aug 10
  ["BAT","NET","ROD","RIB","OAK"],  // 223 · Aug 11
  ["BEAD","CASH","BOW","WAR","TON"],  // 224 · Aug 12
  ["PIE","TRAY","GRIN","FIN","LIE"],  // 225 · Aug 13
  ["FORT","MEN","LAW","NEW","ELF"],  // 226 · Aug 14
  ["SEAT","RIDE","INK","BET","ARM"],  // 227 · Aug 15
  ["FEW","CROW","HOST","BARE","BUN"],  // 228 · Aug 16
  ["ANT","HEN","PAT","RUN","CUB"],  // 229 · Aug 17
  ["MOTH","SOCK","BELL","TIN","SPIN"],  // 230 · Aug 18
  ["SIGH","FIT","LAMP","COAT","EAR"],  // 231 · Aug 19
  ["RAT","FAST","WIG","PIT","MEAL"],  // 232 · Aug 20
  ["HOSE","PAW","PLAN","PAIN","FOG"],  // 233 · Aug 21
  ["BEAR","HAT","CAT","NOSE","TEN"],  // 234 · Aug 22
  ["HOP","CAN","EAT","SON","TIE"],  // 235 · Aug 23
  ["SEA","ROT","CAP","CAMP","SHED"],  // 236 · Aug 24
  ["ICE","BOAT","MAT","LAND","BAND"],  // 237 · Aug 25
  ["PEA","TEA","GOAT","OIL","TAP"],  // 238 · Aug 26
  ["BAR","WIN","OWN","CORD","CAR"],  // 239 · Aug 27
  ["RAM","CORD","OAK","RIB","CAR"],  // 240 · Aug 28
  ["CUB","SON","GOAT","FIN","BARE"],  // 241 · Aug 29
  ["HAM","ICE","TIN","TAP","CAN"],  // 242 · Aug 30
  ["TRAY","FAST","SPIN","BAND","MEAL"],  // 243 · Aug 31
  ["EAT","MEN","HAT","CAMP","RAM"],  // 244 · Sep 1
  ["SHED","CAT","CROW","BELL","ANT"],  // 245 · Sep 2
  ["INK","NET","OIL","HOSE","CASH"],  // 246 · Sep 3
  ["PAT","FOG","WAR","TEA","TON"],  // 247 · Sep 4
  ["OWN","ROT","FORT","COAT","HOP"],  // 248 · Sep 5
  ["BUN","NEW","GRIN","RUN","WIN"],  // 249 · Sep 6
  ["LIE","BAT","STAR","SOCK","PLAN"],  // 250 · Sep 7
  ["SEA","ELF","PAW","FIT","LAMP"],  // 251 · Sep 8
  ["ROD","PAIN","LAND","RIDE","RAT"],  // 252 · Sep 9
  ["TEN","WIG","PEA","BAR","EAR"],  // 253 · Sep 10
  ["MAT","HEN","MOTH","HOST","SEAT"],  // 254 · Sep 11
  ["BEAD","RAIN","PEN","BET","BOW"],  // 255 · Sep 12
  ["PIT","ARM","FEW","OWL","TIE"],  // 256 · Sep 13
  ["NOSE","SIGH","PIE","ART","LAW"],  // 257 · Sep 14
  ["CAP","BOAT","BEAR","RAT","PIE"],  // 258 · Sep 15
  ["BEAD","MEAL","MAT","WAR","BAR"],  // 259 · Sep 16
  ["STAR","RIDE","NOSE","RAIN","LAMP"],  // 260 · Sep 17
  ["BAND","FOG","ROD","TEA","BAT"],  // 261 · Sep 18
  ["PIT","CUB","BELL","GOAT","FIN"],  // 262 · Sep 19
  ["COAT","HAT","PAT","PAIN","HOST"],  // 263 · Sep 20
  ["RAM","BOW","ROT","TRAY","EAT"],  // 264 · Sep 21
  ["CAN","BUN","NET","ELF","LIE"],  // 265 · Sep 22
  ["FIT","SON","TON","SIGH","SEA"],  // 266 · Sep 23
  ["OIL","TIN","OWL","LAW","HOSE"],  // 267 · Sep 24
  ["BET","NEW","PLAN","BOAT","FEW"],  // 268 · Sep 25
  ["GRIN","MOTH","CASH","HEN","CROW"],  // 269 · Sep 26
  ["CAP","ARM","EAR","RUN","LAND"],  // 270 · Sep 27
  ["CAMP","WIG","ICE","FORT","SPIN"],  // 271 · Sep 28
  ["CORD","FAST","RIB","ANT","TEN"],  // 272 · Sep 29
  ["HOP","OWN","BEAR","INK","CAT"],  // 273 · Sep 30
  ["ART","TIE","MEN","HAM","SEAT"],  // 274 · Oct 1
  ["PAW","WIN","CAR","TAP","OAK"],  // 275 · Oct 2
  ["SHED","PEN","PEA","BARE","SOCK"],  // 276 · Oct 3
  ["RUN","EAR","FORT","SOCK","NEW"],  // 277 · Oct 4
  ["PEA","ANT","PAT","OIL","ARM"],  // 278 · Oct 5
  ["CAR","BOAT","LIE","LAW","SHED"],  // 279 · Oct 6
  ["CUB","CORD","EAT","MAT","BEAR"],  // 280 · Oct 7
  ["NET","CASH","SEAT","PAIN","FEW"],  // 281 · Oct 8
  ["CAMP","WIG","WAR","ART","MEN"],  // 282 · Oct 9
  ["RAM","HOSE","INK","BAT","STAR"],  // 283 · Oct 10
  ["HAM","RAIN","TIE","RIDE","BARE"],  // 284 · Oct 11
  ["OWL","NOSE","ROT","TON","COAT"],  // 285 · Oct 12
  ["PIT","GOAT","PAW","CROW","BOW"],  // 286 · Oct 13
  ["TRAY","OAK","BELL","FIT","BET"],  // 287 · Oct 14
  ["FOG","GRIN","WIN","HEN","TEN"],  // 288 · Oct 15
  ["HAT","TAP","TIN","ICE","BAR"],  // 289 · Oct 16
  ["CAP","BUN","BAND","SON","BEAD"],  // 290 · Oct 17
  ["TEA","MEAL","SEA","CAN","SIGH"],  // 291 · Oct 18
  ["HOST","ELF","MOTH","HOP","OWN"],  // 292 · Oct 19
  ["ROD","RIB","RAT","SPIN","LAMP"],  // 293 · Oct 20
  ["PLAN","FIN","LAND","FAST","CAT"],  // 294 · Oct 21
  ["PIE","PEN","BARE","PLAN","CAMP"],  // 295 · Oct 22
  ["SEA","COAT","TIN","NEW","SHED"],  // 296 · Oct 23
  ["WIN","TON","MOTH","ICE","EAR"],  // 297 · Oct 24
  ["WAR","TAP","ROT","NET","ART"],  // 298 · Oct 25
  ["RUN","FOG","LAMP","BOAT","LIE"],  // 299 · Oct 26
  ["CAN","OAK","FIN","BAND","LAW"],  // 300 · Oct 27
  ["CASH","RIDE","SEAT","RIB","OIL"],  // 301 · Oct 28
  ["FAST","PAW","PAT","MEAL","HOSE"],  // 302 · Oct 29
  ["TEA","TEN","WIG","SOCK","PEA"],  // 303 · Oct 30
  ["CAP","PIE","ARM","HAM","PEN"],  // 304 · Oct 31
  ["BAR","FEW","CAT","EAT","BOW"],  // 305 · Nov 1
  ["BEAR","ANT","STAR","MAT","FIT"],  // 306 · Nov 2
  ["SON","RAT","BELL","RAIN","BEAD"],  // 307 · Nov 3
  ["PAIN","TIE","NOSE","ROD","HEN"],  // 308 · Nov 4
  ["TRAY","HOST","MEN","BUN","SPIN"],  // 309 · Nov 5
  ["OWN","LAND","GRIN","HOP","PIT"],  // 310 · Nov 6
  ["BET","ELF","CROW","OWL","CORD"],  // 311 · Nov 7
  ["SIGH","HAT","INK","GOAT","RAM"],  // 312 · Nov 8
  ["BAT","FORT","CAR","CUB","SEAT"],  // 313 · Nov 9
  ["GRIN","ROD","CAN","SHED","BUN"],  // 314 · Nov 10
  ["CAMP","HOSE","BOW","LAMP","CORD"],  // 315 · Nov 11
  ["PAT","FEW","ARM","WIN","BET"],  // 316 · Nov 12
  ["GOAT","RAT","BEAD","TEN","OWN"],  // 317 · Nov 13
  ["SPIN","HOP","HEN","PIT","OWL"],  // 318 · Nov 14
  ["FOG","NEW","ANT","EAR","BAR"],  // 319 · Nov 15
  ["TEA","ELF","RAM","CASH","FORT"],  // 320 · Nov 16
  ["HAT","RIB","CROW","TIN","SON"],  // 321 · Nov 17
  ["STAR","TON","RIDE","WAR","PEA"],  // 322 · Nov 18
  ["SIGH","INK","OIL","FAST","HAM"],  // 323 · Nov 19
  ["ART","PEN","TRAY","EAT","MAT"],  // 324 · Nov 20
  ["HOST","SOCK","NET","LAND","PAIN"],  // 325 · Nov 21
  ["BOAT","COAT","RUN","ICE","MOTH"],  // 326 · Nov 22
  ["CAR","PIE","CAT","MEAL","FIT"],  // 327 · Nov 23
  ["CAP","MEN","LIE","CUB","FIN"],  // 328 · Nov 24
  ["WIG","BELL","BAND","BAT","NOSE"],  // 329 · Nov 25
  ["ROT","OAK","BEAR","PAW","LAW"],  // 330 · Nov 26
  ["SEA","TIE","RAIN","PLAN","BARE"],  // 331 · Nov 27
  ["TAP","NET","MEN","ROD","ROT"],  // 332 · Nov 28
  ["LIE","NEW","SOCK","BEAR","TIE"],  // 333 · Nov 29
  ["CAN","PAW","CORD","SEAT","BUN"],  // 334 · Nov 30
  ["LAMP","SIGH","STAR","OWL","EAT"],  // 335 · Dec 1
  ["CAT","CAMP","FAST","CAR","FOG"],  // 336 · Dec 2
  ["PIE","HOP","BARE","CAP","WIG"],  // 337 · Dec 3
  ["RIDE","FEW","ANT","CUB","BAT"],  // 338 · Dec 4
  ["BEAD","BOW","TEN","MOTH","BELL"],  // 339 · Dec 5
  ["OIL","COAT","PEN","GOAT","BOAT"],  // 340 · Dec 6
  ["BAR","FIT","TRAY","TON","RAM"],  // 341 · Dec 7
  ["HAT","BET","LAND","SPIN","LAW"],  // 342 · Dec 8
  ["FORT","OWN","HAM","HEN","RIB"],  // 343 · Dec 9
  ["CASH","ELF","PIT","HOST","MAT"],  // 344 · Dec 10
  ["FIN","RAT","ICE","PAIN","NOSE"],  // 345 · Dec 11
  ["ARM","WAR","TEA","BAND","ART"],  // 346 · Dec 12
  ["CROW","TAP","WIN","EAR","PLAN"],  // 347 · Dec 13
  ["TIN","HOSE","RAIN","MEAL","PEA"],  // 348 · Dec 14
  ["SON","SEA","INK","PAT","SHED"],  // 349 · Dec 15
  ["GRIN","RUN","OAK","PAT","TIE"],  // 350 · Dec 16
  ["LAND","OIL","CAT","CAR","MEAL"],  // 351 · Dec 17
  ["RIDE","OWN","BOAT","RAT","OAK"],  // 352 · Dec 18
  ["GRIN","GOAT","ARM","EAR","ROT"],  // 353 · Dec 19
  ["OWL","CORD","BEAD","PLAN","SIGH"],  // 354 · Dec 20
  ["BARE","SEAT","HAM","FIN","SHED"],  // 355 · Dec 21
  ["CAMP","PEA","NET","NEW","BAND"],  // 356 · Dec 22
  ["FEW","CAP","PIE","ART","MAT"],  // 357 · Dec 23
  ["SEA","RAM","CASH","FORT","TIN"],  // 358 · Dec 24
  ["TEN","BELL","LAMP","BUN","MEN"],  // 359 · Dec 25
  ["STAR","LIE","CROW","HOP","HOSE"],  // 360 · Dec 26
  ["TEA","NOSE","PAIN","PEN","SPIN"],  // 361 · Dec 27
  ["BAR","SON","ELF","CUB","ROD"],  // 362 · Dec 28
  ["HAT","CAN","FOG","COAT","HOST"],  // 363 · Dec 29
  ["BEAR","SOCK","RIB","BAT","LAW"],  // 364 · Dec 30
  ["EAT","ANT","ICE","WIN","TON"]  // 365 · Dec 31
];
