// Stowaway puzzles.
//
// Each puzzle has:
//   clues   - two clues
//   answers - two words, in the same order. The second is the first with one letter added
//             anywhere: at the start, in the middle or at the end.
//
// Every game picks five of these at random. All puzzles must be original.

window.STOWAWAY_PUZZLES = [
  { clues: ["A hot drink", "A group of players"], answers: ["TEA", "TEAM"] },
  { clues: ["A pet that purrs", "You push it around the store"], answers: ["CAT", "CART"] },
  { clues: ["It twinkles at night", "To begin"], answers: ["STAR", "START"] },
  { clues: ["Thick mist", "It croaks"], answers: ["FOG", "FROG"] },
  { clues: ["It threads onto a necklace", "Baked in a loaf"], answers: ["BEAD", "BREAD"] },
  { clues: ["Winter outerwear", "Where land meets sea"], answers: ["COAT", "COAST"] },
  { clues: ["It lights a desk", "It holds wood while glue dries"], answers: ["LAMP", "CLAMP"] },
  { clues: ["You hear with it", "To make money by working"], answers: ["EAR", "EARN"] },
  { clues: ["A long tired breath", "The sense of seeing"], answers: ["SIGH", "SIGHT"] },
  { clues: ["It floats", "To brag"], answers: ["BOAT", "BOAST"] },
  { clues: ["The one throwing the party", "It haunts a house"], answers: ["HOST", "GHOST"] },
  { clues: ["A big furry animal", "Hair on the chin"], answers: ["BEAR", "BEARD"] },
  { clues: ["Quick", "A big celebratory meal"], answers: ["FAST", "FEAST"] },
  { clues: ["Worn with a suit", "The sea's daily rise and fall"], answers: ["TIE", "TIDE"] },
  { clues: ["A hat with a peak", "Tents in the woods"], answers: ["CAP", "CAMP"] },
  { clues: ["It flutters around a lamp", "Thirty days or so"], answers: ["MOTH", "MONTH"] },
  { clues: ["A gentle tap", "A trail to walk along"], answers: ["PAT", "PATH"] },
  { clues: ["A night bird that hoots", "You eat cereal from it"], answers: ["OWL", "BOWL"] },
  { clues: ["Baked with a crust", "Water flows through it"], answers: ["PIE", "PIPE"] },
  { clues: ["Attached to your shoulder", "Where crops are grown"], answers: ["ARM", "FARM"] },
  { clues: ["Breakfast, lunch or dinner", "Won at the Olympics"], answers: ["MEAL", "MEDAL"] },
  { clues: ["It hangs upside down in caves", "A long soak in the tub"], answers: ["BAT", "BATH"] },
  { clues: ["It falls from clouds", "It runs on rails"], answers: ["RAIN", "TRAIN"] },
  { clues: ["What a bruise causes", "It colours a wall"], answers: ["PAIN", "PAINT"] },
  { clues: ["Worn on the head", "Warmth"], answers: ["HAT", "HEAT"] },
  { clues: ["To come first", "Made from grapes"], answers: ["WIN", "WINE"] },
  { clues: ["Worn inside a shoe", "Goods kept in a shop"], answers: ["SOCK", "STOCK"] },
  { clues: ["You write with it", "Not closed"], answers: ["PEN", "OPEN"] },
  { clues: ["Paintings and sculpture", "A small arrow thrown at a board"], answers: ["ART", "DART"] },
  { clues: ["You drive it", "It comes in a deck"], answers: ["CAR", "CARD"] },
  { clues: ["Frozen water", "A grain eaten with curry"], answers: ["ICE", "RICE"] },
  { clues: ["To move fast on foot", "To spoil completely"], answers: ["RUN", "RUIN"] },
  { clues: ["Fighting between nations", "Pleasantly hot"], answers: ["WAR", "WARM"] },
  { clues: ["The ocean", "A whiskered animal that claps its flippers"], answers: ["SEA", "SEAL"] },
  { clues: ["A scheme", "It flies"], answers: ["PLAN", "PLANE"] },
  { clues: ["It greases an engine", "A loop of wire"], answers: ["OIL", "COIL"] },
  { clues: ["You smell with it", "Unwanted sound"], answers: ["NOSE", "NOISE"] },
  { clues: ["You tie one on a gift", "The ridge above your eye"], answers: ["BOW", "BROW"] },
  { clues: ["A female chicken", "After that"], answers: ["HEN", "THEN"] },
  { clues: ["A rodent", "A speed or a price"], answers: ["RAT", "RATE"] },
  { clues: ["A wide smile", "A single seed of wheat"], answers: ["GRIN", "GRAIN"] },
  { clues: ["You sit on it", "It beads on your skin when hot"], answers: ["SEAT", "SWEAT"] },
  { clues: ["A fish steers with it", "Very good, or a penalty payment"], answers: ["FIN", "FINE"] },
  { clues: ["It rings", "Your stomach"], answers: ["BELL", "BELLY"] },
  { clues: ["To turn round fast", "Your backbone"], answers: ["SPIN", "SPINE"] },
  { clues: ["Paper money", "A loud fight"], answers: ["CASH", "CLASH"] },
  { clues: ["A male child", "In a short while"], answers: ["SON", "SOON"] },
  { clues: ["A metal used for cans", "Very small"], answers: ["TIN", "TINY"] },
  { clues: ["A farm animal with horns and a beard", "To show off about winning"], answers: ["GOAT", "GLOAT"] },
  { clues: ["A black bird that caws", "A king wears it"], answers: ["CROW", "CROWN"] },
  { clues: ["You wipe your feet on it", "Sums and numbers at school"], answers: ["MAT", "MATH"] },
  { clues: ["A small green vegetable", "The top of a mountain"], answers: ["PEA", "PEAK"] },
  { clues: ["A rule made by government", "Grass in front of a house"], answers: ["LAW", "LAWN"] },
  { clues: ["Twice five", "Aged thirteen to nineteen"], answers: ["TEN", "TEEN"] },
  { clues: ["A tiny insect", "Your parent's sister"], answers: ["ANT", "AUNT"] },
  { clues: ["A tree that grows acorns", "To leave in water for a long time"], answers: ["OAK", "SOAK"] },
  { clues: ["A hole in the ground", "A measure of beer"], answers: ["PIT", "PINT"] },
  { clues: ["A bone in your chest", "A baby's bed"], answers: ["RIB", "CRIB"] },
  { clues: ["To possess", "Bigger than a village"], answers: ["OWN", "TOWN"] },
  { clues: ["A small round bread roll", "A bed stacked above another"], answers: ["BUN", "BUNK"] },
  { clues: ["Solid ground", "Dull in flavour"], answers: ["LAND", "BLAND"] },
  { clues: ["A thin straight bar", "Cars drive on it"], answers: ["ROD", "ROAD"] },
  { clues: ["A small pointy-eared helper", "Yourself"], answers: ["ELF", "SELF"] },
  { clues: ["Pens are filled with it", "Dishes are washed in it"], answers: ["INK", "SINK"] },
  { clues: ["A small jump", "You buy things in it"], answers: ["HOP", "SHOP"] },
  { clues: ["A length of string", "Notes played together"], answers: ["CORD", "CHORD"] },
  { clues: ["A garden hut", "A thin torn strip"], answers: ["SHED", "SHRED"] },
  { clues: ["A tin", "A walking stick"], answers: ["CAN", "CANE"] },
  { clues: ["A group of musicians", "A company's name and logo"], answers: ["BAND", "BRAND"] },
  { clues: ["It catches fish", "A bird builds it"], answers: ["NET", "NEST"] },
  { clues: ["Uncovered", "A flat-bottomed river boat"], answers: ["BARE", "BARGE"] },
  { clues: ["More than one man", "A list of dishes"], answers: ["MEN", "MENU"] },
  { clues: ["A baby bear", "A group that meets for a hobby"], answers: ["CUB", "CLUB"] },
  { clues: ["An untruth", "A green citrus fruit"], answers: ["LIE", "LIME"] },
  { clues: ["A soldiers' stronghold", "Four times ten"], answers: ["FORT", "FORTY"] },
  { clues: ["An animal's foot", "The smallest chess piece"], answers: ["PAW", "PAWN"] },
  { clues: ["A long rod, or a pub counter", "Where hay is stored"], answers: ["BAR", "BARN"] },
  { clues: ["To go bad", "The part of a plant underground"], answers: ["ROT", "ROOT"] },
  { clues: ["False hair", "A bird flaps it"], answers: ["WIG", "WING"] },
  { clues: ["To have a meal", "To defeat"], answers: ["EAT", "BEAT"] },
  { clues: ["A wager", "Worn around the waist"], answers: ["BET", "BELT"] },
  { clues: ["You carry drinks on it", "A lost pet"], answers: ["TRAY", "STRAY"] },
  { clues: ["A male sheep", "A slope for wheels"], answers: ["RAM", "RAMP"] },
  { clues: ["Healthy", "A clenched hand"], answers: ["FIT", "FIST"] },
  { clues: ["A thousand kilograms", "The quality of a sound"], answers: ["TON", "TONE"] },
  { clues: ["Not old", "Was aware of"], answers: ["NEW", "KNEW"] },
  { clues: ["Tents in the woods", "A sudden muscle pain"], answers: ["CAMP", "CRAMP"] },
  { clues: ["A trip on a horse", "She walks down the aisle"], answers: ["RIDE", "BRIDE"] },
  { clues: ["Meat from a pig", "Damage or injury"], answers: ["HAM", "HARM"] },
  { clues: ["Not many", "Travelled by plane, in the past"], answers: ["FEW", "FLEW"] },
  { clues: ["Water comes out of it", "It catches animals"], answers: ["TAP", "TRAP"] },
  { clues: ["A flexible water pipe", "You can ride it"], answers: ["HOSE", "HORSE"] },
  // ---- Added 9 October 2026 ----
  { clues: ["At this moment", "To be aware of"], answers: ["NOW", "KNOW"] },
  { clues: ["In this place", "In that place"], answers: ["HERE", "THERE"] },
  { clues: ["Belonging to us", "Belonging to you"], answers: ["OUR", "YOUR"] },
  { clues: ["Every one", "To phone someone"], answers: ["ALL", "CALL"] },
  { clues: ["A grown-up boy", "Unkind, or what a word signifies"], answers: ["MAN", "MEAN"] },
  { clues: ["A single thing", "Finished"], answers: ["ONE", "DONE"] },
  { clues: ["A route", "Not here"], answers: ["WAY", "AWAY"] },
  { clues: ["Allow", "The opposite of right"], answers: ["LET", "LEFT"] },
  { clues: ["Compared with", "To say you are grateful"], answers: ["THAN", "THANK"] },
  { clues: ["In what way", "To let someone see"], answers: ["HOW", "SHOW"] },
  { clues: ["At any time", "At no time"], answers: ["EVER", "NEVER"] },
  { clues: ["To speak", "To remain"], answers: ["SAY", "STAY"] },
  { clues: ["Extremely", "Each one"], answers: ["VERY", "EVERY"] },
  { clues: ["Not young", "Informed"], answers: ["OLD", "TOLD"] },
  { clues: ["Plus", "At the end of your arm"], answers: ["AND", "HAND"] },
  { clues: ["Not a few", "A lot of"], answers: ["ANY", "MANY"] },
  { clues: ["Also", "Grabbed"], answers: ["TOO", "TOOK"] },
  { clues: ["In favour of", "Two plus two"], answers: ["FOR", "FOUR"] },
  { clues: ["A great deal", "Unable to be found"], answers: ["LOT", "LOST"] },
  { clues: ["A young goat, or a child", "Caring and gentle"], answers: ["KID", "KIND"] },
  { clues: ["Not soft", "Listened to"], answers: ["HARD", "HEARD"] },
  { clues: ["Final", "The smallest amount"], answers: ["LAST", "LEAST"] },
  { clues: ["The rear", "The darkest colour"], answers: ["BACK", "BLACK"] },
  { clues: ["A unit of language", "The whole planet"], answers: ["WORD", "WORLD"] },
  { clues: ["A young male", "Everything from head to toe"], answers: ["BOY", "BODY"] },
  { clues: ["Not short", "Beside, as in \"come ___\""], answers: ["LONG", "ALONG"] },
  { clues: ["To hand over money", "What children do with toys"], answers: ["PAY", "PLAY"] },
  { clues: ["Not hot", "Was able to"], answers: ["COLD", "COULD"] },
  { clues: ["To take in words from a page", "Prepared"], answers: ["READ", "READY"] },
  { clues: ["The highest point", "Come to a halt"], answers: ["TOP", "STOP"] },
  { clues: ["Hand over", "Handed over"], answers: ["GIVE", "GIVEN"] },
  { clues: ["Came across", "To get together"], answers: ["MET", "MEET"] },
  { clues: ["A piece of the whole", "A celebration"], answers: ["PART", "PARTY"] },
  { clues: ["To be alive", "Not dead"], answers: ["LIVE", "ALIVE"] },
  { clues: ["The finish", "To post"], answers: ["END", "SEND"] },
  { clues: ["Angry", "Created"], answers: ["MAD", "MADE"] },
  { clues: ["A box for carrying things, or a court matter", "The reason something happens"], answers: ["CASE", "CAUSE"] },
  { clues: ["Not odd", "The number after six"], answers: ["EVEN", "SEVEN"] },
  { clues: ["Shaped like a ball", "On all sides"], answers: ["ROUND", "AROUND"] },
  { clues: ["The opposite of win", "The opposite of open"], answers: ["LOSE", "CLOSE"] },
  { clues: ["Above", "A lid"], answers: ["OVER", "COVER"] },
  { clues: ["Very warm", "Fired, as a gun"], answers: ["HOT", "SHOT"] },
  { clues: ["To change position", "A film"], answers: ["MOVE", "MOVIE"] },
  { clues: ["Unhappy", "Spoke"], answers: ["SAD", "SAID"] },
  { clues: ["A circle of metal on a finger", "To carry along"], answers: ["RING", "BRING"] },
  { clues: ["What you breathe", "It grows on your head"], answers: ["AIR", "HAIR"] },
  { clues: ["Not near", "Just and honest"], answers: ["FAR", "FAIR"] },
  { clues: ["To purchase", "Occupied"], answers: ["BUY", "BUSY"] },
  { clues: ["To do something", "Something that is true"], answers: ["ACT", "FACT"] },
  { clues: ["Capable", "You eat your dinner at it"], answers: ["ABLE", "TABLE"] },
  { clues: ["It has a trunk and branches", "One more than two"], answers: ["TREE", "THREE"] },
  { clues: ["To post", "To pay out"], answers: ["SEND", "SPEND"] },
  { clues: ["Every one", "What a teacher does"], answers: ["EACH", "TEACH"] },
  { clues: ["A kind or type", "Not tall"], answers: ["SORT", "SHORT"] },
  { clues: ["To stop doing something", "Completely"], answers: ["QUIT", "QUITE"] },
  { clues: ["Unwell", "A thin piece of wood"], answers: ["SICK", "STICK"] },
  { clues: ["Not good", "A group of musicians"], answers: ["BAD", "BAND"] },
  { clues: ["An opening", "Complete, entire"], answers: ["HOLE", "WHOLE"] },
  { clues: ["Not different", "A feeling of disgrace"], answers: ["SAME", "SHAME"] },
  { clues: ["To take a seat", "A jacket and trousers"], answers: ["SIT", "SUIT"] },
  { clues: ["To have on, as clothes", "To promise solemnly"], answers: ["WEAR", "SWEAR"] },
  { clues: ["To exchange for money", "To sniff"], answers: ["SELL", "SMELL"] },
  { clues: ["A punch-up", "A journey by air"], answers: ["FIGHT", "FLIGHT"] },
  { clues: ["A large room", "Will, as in \"we ___ see\""], answers: ["HALL", "SHALL"] },
  { clues: ["Correct", "Shining"], answers: ["RIGHT", "BRIGHT"] },
  { clues: ["A small amount", "To sink your teeth in"], answers: ["BIT", "BITE"] },
  { clues: ["Not dry", "Travelled"], answers: ["WET", "WENT"] },
  { clues: ["Not high", "What the wind does"], answers: ["LOW", "BLOW"] },
  { clues: ["Moved fast on foot", "It falls from clouds"], answers: ["RAN", "RAIN"] },
  { clues: ["It grows on your head", "You sit on it"], answers: ["HAIR", "CHAIR"] },
  { clues: ["Not late", "Almost"], answers: ["EARLY", "NEARLY"] },
  { clues: ["To look after", "To frighten"], answers: ["CARE", "SCARE"] },
  { clues: ["Beef or pork", "Intended"], answers: ["MEAT", "MEANT"] },
  { clues: ["Consumed", "Not early"], answers: ["ATE", "LATE"] },
  { clues: ["A spot or location", "Where a king lives"], answers: ["PLACE", "PALACE"] },
  { clues: ["Together, not without", "She rides a broomstick"], answers: ["WITH", "WITCH"] },
  { clues: ["Those people", "The subject of a story"], answers: ["THEM", "THEME"] },
  { clues: ["Coins and notes", "It swings through the trees"], answers: ["MONEY", "MONKEY"] },
  { clues: ["Wicked", "A horned fiend"], answers: ["EVIL", "DEVIL"] },
  { clues: ["What something costs", "A king's son"], answers: ["PRICE", "PRINCE"] },
  { clues: ["Handed over", "Where a body is buried"], answers: ["GAVE", "GRAVE"] },
  { clues: ["Water flowing to the sea", "The person behind the wheel"], answers: ["RIVER", "DRIVER"] },
  { clues: ["Not early", "You eat dinner off it"], answers: ["LATE", "PLATE"] },
  { clues: ["A police officer, informally", "A duplicate"], answers: ["COP", "COPY"] },
  { clues: ["A running contest", "Elegance, or a prayer before a meal"], answers: ["RACE", "GRACE"] },
  { clues: ["A restaurant cook", "The leader"], answers: ["CHEF", "CHIEF"] },
  { clues: ["How old you are", "One side of a sheet of paper"], answers: ["AGE", "PAGE"] },
  { clues: ["Two times four", "How heavy something is"], answers: ["EIGHT", "WEIGHT"] },
  { clues: ["Left or right", "To one side"], answers: ["SIDE", "ASIDE"] },
  { clues: ["Better than all the rest", "A wild animal"], answers: ["BEST", "BEAST"] },
  { clues: ["A spell of bad luck", "A series of lessons"], answers: ["CURSE", "COURSE"] },
  { clues: ["Not fat", "To use your brain"], answers: ["THIN", "THINK"] },
  { clues: ["For the good of, as in \"for your ___\"", "To wobble back and forth"], answers: ["SAKE", "SHAKE"] },
  { clues: ["Guided", "A heavy grey metal"], answers: ["LED", "LEAD"] },
  { clues: ["Not him", "Worn on a foot"], answers: ["SHE", "SHOE"] },
  { clues: ["You carry shopping in it", "A loud noise"], answers: ["BAG", "BANG"] },
  { clues: ["To stop sleeping", "No longer asleep"], answers: ["WAKE", "AWAKE"] },
  { clues: ["To put a question", "A job to be done"], answers: ["ASK", "TASK"] },
  { clues: ["A beam of light", "To speak to a god"], answers: ["RAY", "PRAY"] },
  { clues: ["Where boats shelter", "A very young child"], answers: ["BAY", "BABY"] },
  { clues: ["Rhythm", "A wild animal"], answers: ["BEAT", "BEAST"] },
  { clues: ["Complete", "Completely"], answers: ["FULL", "FULLY"] },
  { clues: ["A key opens it", "A cube of wood or stone"], answers: ["LOCK", "BLOCK"] },
  { clues: ["What the wind does", "Underneath"], answers: ["BLOW", "BELOW"] },
  { clues: ["On a beach", "To be on your feet"], answers: ["SAND", "STAND"] },
  { clues: ["A wrongdoing", "A notice on a post"], answers: ["SIN", "SIGN"] },
  { clues: ["Took a seat", "A place to sit"], answers: ["SAT", "SEAT"] },
  { clues: ["A command, or a sequence", "The edge of a country"], answers: ["ORDER", "BORDER"] },
  { clues: ["The very end", "A journey"], answers: ["TIP", "TRIP"] },
  { clues: ["To shut", "A cupboard for clothes"], answers: ["CLOSE", "CLOSET"] },
  { clues: ["The people who run a ship", "A twisting metal fastener"], answers: ["CREW", "SCREW"] },
  { clues: ["A condition, or a nation", "A large house with grounds"], answers: ["STATE", "ESTATE"] },
  { clues: ["To be paid for work", "To gain knowledge"], answers: ["EARN", "LEARN"] },
  { clues: ["To get something extra", "One more time"], answers: ["GAIN", "AGAIN"] },
  { clues: ["Closed", "To yell"], answers: ["SHUT", "SHOUT"] },
  { clues: ["To add up", "A region of a province or state"], answers: ["COUNT", "COUNTY"] },
  { clues: ["To get up", "To lift"], answers: ["RISE", "RAISE"] },
  { clues: ["A special pleasure", "A warning of harm"], answers: ["TREAT", "THREAT"] },
  { clues: ["The top of a house", "Evidence"], answers: ["ROOF", "PROOF"] },
  { clues: ["When the stars are out", "He wears armour"], answers: ["NIGHT", "KNIGHT"] },
  { clues: ["Grains eaten with curry", "What something costs"], answers: ["RICE", "PRICE"] },
  { clues: ["The two together", "A small enclosed stall"], answers: ["BOTH", "BOOTH"] },
  { clues: ["To squeeze someone fondly", "Enormous"], answers: ["HUG", "HUGE"] },
  { clues: ["You cook in it", "A small round mark"], answers: ["POT", "SPOT"] },
  { clues: ["What something costs", "The land beside the sea"], answers: ["COST", "COAST"] },
  { clues: ["To become a member", "Where two bones meet"], answers: ["JOIN", "JOINT"] },
  { clues: ["A bad habit", "What you speak with"], answers: ["VICE", "VOICE"] },
  { clues: ["Rage", "Something that could harm you"], answers: ["ANGER", "DANGER"] },
  { clues: ["A woman on her wedding day", "It crosses a river"], answers: ["BRIDE", "BRIDGE"] },
  { clues: ["Soil", "Not clean"], answers: ["DIRT", "DIRTY"] },
  { clues: ["Had on, as clothes", "Not better"], answers: ["WORE", "WORSE"] },
  { clues: ["A midday meal", "To send a rocket into space"], answers: ["LUNCH", "LAUNCH"] },
  { clues: ["The top of the milk", "To yell in fright"], answers: ["CREAM", "SCREAM"] },
  { clues: ["\"That hurt!\"", "To make contact with a finger"], answers: ["OUCH", "TOUCH"] },
  { clues: ["Exchanged for money", "Not hollow"], answers: ["SOLD", "SOLID"] },
  { clues: ["A narrow country road", "It flies with wings and an engine"], answers: ["LANE", "PLANE"] },
  { clues: ["A flat piece of wood", "On the ship"], answers: ["BOARD", "ABOARD"] },
  { clues: ["To stop living", "A plan for eating less"], answers: ["DIE", "DIET"] },
  { clues: ["Sacred", "A prickly evergreen with red berries"], answers: ["HOLY", "HOLLY"] },
  { clues: ["A big road vehicle", "Hit hard"], answers: ["TRUCK", "STRUCK"] },
  { clues: ["Just and honest", "A tiny magical being"], answers: ["FAIR", "FAIRY"] },
  { clues: ["A musical note, or a mood", "A rock"], answers: ["TONE", "STONE"] },
  { clues: ["Gave food to", "To give food to"], answers: ["FED", "FEED"] },
  { clues: ["Strength, or electricity", "Fine dry particles"], answers: ["POWER", "POWDER"] },
  { clues: ["A piece of a tree trunk", "Not short"], answers: ["LOG", "LONG"] },
  { clues: ["Further down", "It blooms"], answers: ["LOWER", "FLOWER"] },
  { clues: ["A distance of 1.6 kilometres", "A happy expression"], answers: ["MILE", "SMILE"] },
  { clues: ["You sleep in it", "To curve"], answers: ["BED", "BEND"] },
  { clues: ["You eat your dinner at it", "Where horses are kept"], answers: ["TABLE", "STABLE"] },
  { clues: ["She rides a broomstick", "Flick it to turn the light on"], answers: ["WITCH", "SWITCH"] },
  { clues: ["You drink it", "He brings your food in a restaurant"], answers: ["WATER", "WAITER"] },
  { clues: ["A small round mark", "Football or tennis"], answers: ["SPOT", "SPORT"] },
  { clues: ["Money set aside for a purpose", "Discovered"], answers: ["FUND", "FOUND"] },
  { clues: ["Pleasant", "Your brother's daughter"], answers: ["NICE", "NIECE"] },
  { clues: ["Shame for doing wrong", "Having done wrong"], answers: ["GUILT", "GUILTY"] },
  { clues: ["Was victorious", "Used until shabby"], answers: ["WON", "WORN"] },
  { clues: ["To take a life", "A talent"], answers: ["KILL", "SKILL"] },
  { clues: ["Similar to", "Similar"], answers: ["LIKE", "ALIKE"] },
  { clues: ["A shopping centre", "Not big"], answers: ["MALL", "SMALL"] },
  { clues: ["A payment for a service", "To touch, or to experience"], answers: ["FEE", "FEEL"] },
  { clues: ["Not up", "To die under water"], answers: ["DOWN", "DROWN"] },
  { clues: ["The actors in a play", "The land beside the sea"], answers: ["CAST", "COAST"] },
  { clues: ["Inside", "The evening meal"], answers: ["INNER", "DINNER"] },
  { clues: ["A story", "You eat your dinner at it"], answers: ["TALE", "TABLE"] },
  { clues: ["Sums and numbers", "A game, or a stick that lights a fire"], answers: ["MATH", "MATCH"] },
  { clues: ["A woman whose husband has died", "Glass in a wall"], answers: ["WIDOW", "WINDOW"] },
  { clues: ["A thought", "Perfect"], answers: ["IDEA", "IDEAL"] },
  { clues: ["To plunge head first into water", "To steer a car"], answers: ["DIVE", "DRIVE"] },
  { clues: ["A group of related families", "Not dirty"], answers: ["CLAN", "CLEAN"] },
  { clues: ["Part of a house", "A man on his wedding day"], answers: ["ROOM", "GROOM"] },
  { clues: ["Healthy, or a hole for water", "To grow bigger"], answers: ["WELL", "SWELL"] },
  { clues: ["The joint at the top of your leg", "A large boat"], answers: ["HIP", "SHIP"] },
  { clues: ["The way out", "To be"], answers: ["EXIT", "EXIST"] },
  { clues: ["The best card", "The front of your head"], answers: ["ACE", "FACE"] },
  { clues: ["Iron, copper or gold", "To do with the mind"], answers: ["METAL", "MENTAL"] },
  { clues: ["To hurry", "To squash"], answers: ["RUSH", "CRUSH"] },
  { clues: ["At the ends of your legs", "A group of ships"], answers: ["FEET", "FLEET"] },
  { clues: ["A group of players", "Hot water vapour"], answers: ["TEAM", "STEAM"] },
  { clues: ["What a llama might do to you", "To divide"], answers: ["SPIT", "SPLIT"] },
  { clues: ["A large stone", "Full of large stones"], answers: ["ROCK", "ROCKY"] },
  { clues: ["Noisy", "It floats in the sky"], answers: ["LOUD", "CLOUD"] },
  { clues: ["A small simple shelter", "Closed"], answers: ["HUT", "SHUT"] },
  { clues: ["A closed hand", "Before all others"], answers: ["FIST", "FIRST"] },
  { clues: ["Higher than the land around it", "A slight cold"], answers: ["HILL", "CHILL"] },
  { clues: ["To be on fire", "Scorched"], answers: ["BURN", "BURNT"] },
  { clues: ["To keep for later", "To remove hair with a razor"], answers: ["SAVE", "SHAVE"] },
  { clues: ["Above all others, as in \"___ star\"", "An evening meal"], answers: ["SUPER", "SUPPER"] },
  { clues: ["To lift", "To say good things about"], answers: ["RAISE", "PRAISE"] },
  { clues: ["Money paid to the government", "A cab"], answers: ["TAX", "TAXI"] },
  { clues: ["Thin, or to tilt", "To gain knowledge"], answers: ["LEAN", "LEARN"] },
  { clues: ["Cars drive on it", "Wide"], answers: ["ROAD", "BROAD"] },
  { clues: ["Damage", "Delightful appeal"], answers: ["HARM", "CHARM"] },
  { clues: ["Clean, unmixed", "A small bag for money"], answers: ["PURE", "PURSE"] },
  { clues: ["Speed", "A spot or location"], answers: ["PACE", "PLACE"] },
  { clues: ["Unable to walk well", "To hold responsible"], answers: ["LAME", "BLAME"] },
  { clues: ["A mountain chain, or a cooker", "A fruit with a peel, and a colour"], answers: ["RANGE", "ORANGE"] },
  { clues: ["What is left after a fire", "Coins and notes"], answers: ["ASH", "CASH"] },
  { clues: ["Painful to touch", "A shop"], answers: ["SORE", "STORE"] },
  { clues: ["The one who inherits", "Belonging to them"], answers: ["HEIR", "THEIR"] },
  { clues: ["A dog wags it", "A path through the woods"], answers: ["TAIL", "TRAIL"] },
  { clues: ["Had a meal", "Defeated"], answers: ["EATEN", "BEATEN"] },
  { clues: ["At the end of your arm", "Useful"], answers: ["HAND", "HANDY"] },
  { clues: ["An offer at an auction", "It has feathers"], answers: ["BID", "BIRD"] },
  { clues: ["Switched on", "Things written down one under another"], answers: ["LIT", "LIST"] },
  { clues: ["Uncooked", "To make a picture with a pencil"], answers: ["RAW", "DRAW"] },
  { clues: ["A part of something", "To make a hole with a sharp point"], answers: ["PIECE", "PIERCE"] },
  { clues: ["Onward, as in \"go ___\"", "After third"], answers: ["FORTH", "FOURTH"] },
  { clues: ["A friendly talk", "To break the rules to win"], answers: ["CHAT", "CHEAT"] },
  { clues: ["A room for science experiments", "A young sheep"], answers: ["LAB", "LAMB"] },
  { clues: ["A bird flies with it", "A seat that hangs from ropes"], answers: ["WING", "SWING"] },
  { clues: ["Deep affection", "Worn on a hand"], answers: ["LOVE", "GLOVE"] },
  { clues: ["A high hill", "How much there is"], answers: ["MOUNT", "AMOUNT"] },
  { clues: ["Jacket and trousers", "A set of hotel rooms"], answers: ["SUIT", "SUITE"] },
  { clues: ["A close tie between people", "Tied up"], answers: ["BOND", "BOUND"] },
  { clues: ["What you eat", "Too much water"], answers: ["FOOD", "FLOOD"] },
  { clues: ["A position in a list", "Honest and open"], answers: ["RANK", "FRANK"] },
  { clues: ["A track to walk along", "A piece sewn over a hole"], answers: ["PATH", "PATCH"] },
  { clues: ["Where money is kept", "Empty, with nothing written on it"], answers: ["BANK", "BLANK"] }
];
