// Stowaway puzzles.
//
// Each puzzle has:
//   clues   - two clues
//   answers - two words, in the same order. The second is the first with one letter added
//             anywhere: at the start, in the middle or at the end.
//
// Every game picks five of these at random. All puzzles must be original.

window.STOWAWAY_PUZZLES = [
  { clues: ["A hot drink", "A group of players"], answers: ["TEA", "TEAM"] },
  { clues: ["A pet that purrs", "You push it around the store"], answers: ["CAT", "CART"] },
  { clues: ["It twinkles at night", "To begin"], answers: ["STAR", "START"] },
  { clues: ["Thick mist", "It croaks"], answers: ["FOG", "FROG"] },
  { clues: ["It threads onto a necklace", "Baked in a loaf"], answers: ["BEAD", "BREAD"] },
  { clues: ["Winter outerwear", "Where land meets sea"], answers: ["COAT", "COAST"] },
  { clues: ["It lights a desk", "It holds wood while glue dries"], answers: ["LAMP", "CLAMP"] },
  { clues: ["You hear with it", "To make money by working"], answers: ["EAR", "EARN"] },
  { clues: ["A long tired breath", "The sense of seeing"], answers: ["SIGH", "SIGHT"] },
  { clues: ["It floats", "To brag"], answers: ["BOAT", "BOAST"] },
  { clues: ["The one throwing the party", "It haunts a house"], answers: ["HOST", "GHOST"] },
  { clues: ["A big furry animal", "Hair on the chin"], answers: ["BEAR", "BEARD"] },
  { clues: ["Quick", "A big celebratory meal"], answers: ["FAST", "FEAST"] },
  { clues: ["Worn with a suit", "The sea's daily rise and fall"], answers: ["TIE", "TIDE"] },
  { clues: ["A hat with a peak", "Tents in the woods"], answers: ["CAP", "CAMP"] },
  { clues: ["It flutters around a lamp", "Thirty days or so"], answers: ["MOTH", "MONTH"] },
  { clues: ["A gentle tap", "A trail to walk along"], answers: ["PAT", "PATH"] },
  { clues: ["A night bird that hoots", "You eat cereal from it"], answers: ["OWL", "BOWL"] },
  { clues: ["Baked with a crust", "Water flows through it"], answers: ["PIE", "PIPE"] },
  { clues: ["Attached to your shoulder", "Where crops are grown"], answers: ["ARM", "FARM"] },
  { clues: ["Breakfast, lunch or dinner", "Won at the Olympics"], answers: ["MEAL", "MEDAL"] },
  { clues: ["It hangs upside down in caves", "A long soak in the tub"], answers: ["BAT", "BATH"] },
  { clues: ["It falls from clouds", "It runs on rails"], answers: ["RAIN", "TRAIN"] },
  { clues: ["What a bruise causes", "It colours a wall"], answers: ["PAIN", "PAINT"] },
  { clues: ["Worn on the head", "Warmth"], answers: ["HAT", "HEAT"] },
  { clues: ["To come first", "Made from grapes"], answers: ["WIN", "WINE"] },
  { clues: ["Worn inside a shoe", "Goods kept in a shop"], answers: ["SOCK", "STOCK"] },
  { clues: ["You write with it", "Not closed"], answers: ["PEN", "OPEN"] },
  { clues: ["Paintings and sculpture", "A small arrow thrown at a board"], answers: ["ART", "DART"] },
  { clues: ["You drive it", "It comes in a deck"], answers: ["CAR", "CARD"] },
  { clues: ["Frozen water", "A grain eaten with curry"], answers: ["ICE", "RICE"] },
  { clues: ["To move fast on foot", "To spoil completely"], answers: ["RUN", "RUIN"] },
  { clues: ["Fighting between nations", "Pleasantly hot"], answers: ["WAR", "WARM"] },
  { clues: ["The ocean", "A whiskered animal that claps its flippers"], answers: ["SEA", "SEAL"] },
  { clues: ["A scheme", "It flies"], answers: ["PLAN", "PLANE"] },
  { clues: ["It greases an engine", "A loop of wire"], answers: ["OIL", "COIL"] },
  { clues: ["You smell with it", "Unwanted sound"], answers: ["NOSE", "NOISE"] },
  { clues: ["You tie one on a gift", "The ridge above your eye"], answers: ["BOW", "BROW"] },
  { clues: ["A female chicken", "After that"], answers: ["HEN", "THEN"] },
  { clues: ["A rodent", "A speed or a price"], answers: ["RAT", "RATE"] },
  { clues: ["A wide smile", "A single seed of wheat"], answers: ["GRIN", "GRAIN"] },
  { clues: ["You sit on it", "It beads on your skin when hot"], answers: ["SEAT", "SWEAT"] },
  { clues: ["A fish steers with it", "Very good, or a penalty payment"], answers: ["FIN", "FINE"] },
  { clues: ["It rings", "Your stomach"], answers: ["BELL", "BELLY"] },
  { clues: ["To turn round fast", "Your backbone"], answers: ["SPIN", "SPINE"] },
  { clues: ["Paper money", "A loud fight"], answers: ["CASH", "CLASH"] },
  { clues: ["A male child", "In a short while"], answers: ["SON", "SOON"] },
  { clues: ["A metal used for cans", "Very small"], answers: ["TIN", "TINY"] },
  { clues: ["A farm animal with horns and a beard", "To show off about winning"], answers: ["GOAT", "GLOAT"] },
  { clues: ["A black bird that caws", "A king wears it"], answers: ["CROW", "CROWN"] },
  { clues: ["You wipe your feet on it", "Sums and numbers at school"], answers: ["MAT", "MATH"] },
  { clues: ["A small green vegetable", "The top of a mountain"], answers: ["PEA", "PEAK"] },
  { clues: ["A rule made by government", "Grass in front of a house"], answers: ["LAW", "LAWN"] },
  { clues: ["Twice five", "Aged thirteen to nineteen"], answers: ["TEN", "TEEN"] },
  { clues: ["A tiny insect", "Your parent's sister"], answers: ["ANT", "AUNT"] },
  { clues: ["A tree that grows acorns", "To leave in water for a long time"], answers: ["OAK", "SOAK"] },
  { clues: ["A hole in the ground", "A measure of beer"], answers: ["PIT", "PINT"] },
  { clues: ["A bone in your chest", "A baby's bed"], answers: ["RIB", "CRIB"] },
  { clues: ["To possess", "Bigger than a village"], answers: ["OWN", "TOWN"] },
  { clues: ["A small round bread roll", "A bed stacked above another"], answers: ["BUN", "BUNK"] },
  { clues: ["Solid ground", "Dull in flavour"], answers: ["LAND", "BLAND"] },
  { clues: ["A thin straight bar", "Cars drive on it"], answers: ["ROD", "ROAD"] },
  { clues: ["A small pointy-eared helper", "Yourself"], answers: ["ELF", "SELF"] },
  { clues: ["Pens are filled with it", "Dishes are washed in it"], answers: ["INK", "SINK"] },
  { clues: ["A small jump", "You buy things in it"], answers: ["HOP", "SHOP"] },
  { clues: ["A length of string", "Notes played together"], answers: ["CORD", "CHORD"] },
  { clues: ["A garden hut", "A thin torn strip"], answers: ["SHED", "SHRED"] },
  { clues: ["A tin", "A walking stick"], answers: ["CAN", "CANE"] },
  { clues: ["A group of musicians", "A company's name and logo"], answers: ["BAND", "BRAND"] },
  { clues: ["It catches fish", "A bird builds it"], answers: ["NET", "NEST"] },
  { clues: ["Uncovered", "A flat-bottomed river boat"], answers: ["BARE", "BARGE"] },
  { clues: ["More than one man", "A list of dishes"], answers: ["MEN", "MENU"] },
  { clues: ["A baby bear", "A group that meets for a hobby"], answers: ["CUB", "CLUB"] },
  { clues: ["An untruth", "A green citrus fruit"], answers: ["LIE", "LIME"] },
  { clues: ["A soldiers' stronghold", "Four times ten"], answers: ["FORT", "FORTY"] },
  { clues: ["An animal's foot", "The smallest chess piece"], answers: ["PAW", "PAWN"] },
  { clues: ["A long rod, or a pub counter", "Where hay is stored"], answers: ["BAR", "BARN"] },
  { clues: ["To go bad", "The part of a plant underground"], answers: ["ROT", "ROOT"] },
  { clues: ["False hair", "A bird flaps it"], answers: ["WIG", "WING"] },
  { clues: ["To have a meal", "To defeat"], answers: ["EAT", "BEAT"] },
  { clues: ["A wager", "Worn around the waist"], answers: ["BET", "BELT"] },
  { clues: ["You carry drinks on it", "A lost pet"], answers: ["TRAY", "STRAY"] },
  { clues: ["A male sheep", "A slope for wheels"], answers: ["RAM", "RAMP"] },
  { clues: ["Healthy", "A clenched hand"], answers: ["FIT", "FIST"] },
  { clues: ["A thousand kilograms", "The quality of a sound"], answers: ["TON", "TONE"] },
  { clues: ["Not old", "Was aware of"], answers: ["NEW", "KNEW"] },
  { clues: ["Tents in the woods", "A sudden muscle pain"], answers: ["CAMP", "CRAMP"] },
  { clues: ["A trip on a horse", "She walks down the aisle"], answers: ["RIDE", "BRIDE"] },
  { clues: ["Meat from a pig", "Damage or injury"], answers: ["HAM", "HARM"] },
  { clues: ["Not many", "Travelled by plane, in the past"], answers: ["FEW", "FLEW"] },
  { clues: ["Water comes out of it", "It catches animals"], answers: ["TAP", "TRAP"] },
  { clues: ["A flexible water pipe", "You can ride it"], answers: ["HOSE", "HORSE"] }
];
