// Daily puzzle schedule for 2026. Made by: node tools/make-daily.js 2026 --refresh (days 1 to 283 kept from the earlier schedule)
// One line per day. Day 1 is January 1. Each puzzle is named by its key (see shared/keys.js).
// Do not edit by hand: past days should stay as they were.
window.DAILY_SCHEDULE = window.DAILY_SCHEDULE || {};
window.DAILY_SCHEDULE[2026] = [
  ["PARSE","DOWRY","BEGIN","THREE","BREAD"],  // 1 · Jan 1
  ["STEER","GLARE","SWINE","HIRES","BEAST"],  // 2 · Jan 2
  ["EARLY","SHEAR","BRUTE","BELOW","PETAL"],  // 3 · Jan 3
  ["SPELT","LAIRS","SPRAY","COAST","EARNS"],  // 4 · Jan 4
  ["VERSE","SPACE","LOVES","CLASP","IDEAS"],  // 5 · Jan 5
  ["REACT","HEART","SPOTS","HEATS","CARES"],  // 6 · Jan 6
  ["TEAMS","PANES","NAMES","SPORE","SWEAR"],  // 7 · Jan 7
  ["TRIES","ALERT","RENTS","COINS","LUMPS"],  // 8 · Jan 8
  ["ROBES","TILES","WIRES","POOLS","LEAST"],  // 9 · Jan 9
  ["PEDAL","NOTES","WORSE","NAILS","LEASH"],  // 10 · Jan 10
  ["TIMER","SMILE","TRADE","GROAN","RESIN"],  // 11 · Jan 11
  ["ITEMS","ANGEL","STARE","STAIN","DIETS"],  // 12 · Jan 12
  ["SLIDE","SALTS","FLOWS","DEALS","EVILS"],  // 13 · Jan 13
  ["LAMPS","STRAP","SHAPE","SKATE","PALES"],  // 14 · Jan 14
  ["BAKER","WEIRD","SHAPE","STAIN","PARSE"],  // 15 · Jan 15
  ["LOVES","SLIDE","SMILE","LEASH","NOTES"],  // 16 · Jan 16
  ["RENTS","BREAD","TIMER","LUMPS","SPRAY"],  // 17 · Jan 17
  ["COAST","GROAN","EVILS","SPACE","DOWRY"],  // 18 · Jan 18
  ["TILES","EARLY","TRADE","SWEAR","PALES"],  // 19 · Jan 19
  ["CARES","TEAMS","DIETS","SALTS","PANES"],  // 20 · Jan 20
  ["STARE","BRUTE","HIRES","SPORE","LAMPS"],  // 21 · Jan 21
  ["EARNS","IDEAS","WEIRD","PEDAL","NAMES"],  // 22 · Jan 22
  ["POOLS","THREE","BAKER","LEAST","BEGIN"],  // 23 · Jan 23
  ["ROBES","SHEAR","SKATE","FLOWS","STEER"],  // 24 · Jan 24
  ["BELOW","WORSE","ALERT","SPELT","NAILS"],  // 25 · Jan 25
  ["GLARE","STRAP","LAIRS","REACT","RESIN"],  // 26 · Jan 26
  ["COINS","VERSE","ITEMS","HEATS","WIRES"],  // 27 · Jan 27
  ["BEAST","SPOTS","DEALS","ANGEL","TRIES"],  // 28 · Jan 28
  ["CLASP","HEART","SWINE","PETAL","BEGIN"],  // 29 · Jan 29
  ["EARNS","DEALS","NOTES","POOLS","SWEAR"],  // 30 · Jan 30
  ["SHEAR","RENTS","SKATE","PETAL","TRIES"],  // 31 · Jan 31
  ["FLOWS","LAIRS","WORSE","ALERT","COINS"],  // 32 · Feb 1
  ["LEASH","BREAD","HEART","SPORE","STAIN"],  // 33 · Feb 2
  ["NAMES","SPOTS","LOVES","NAILS","TILES"],  // 34 · Feb 3
  ["SPACE","WIRES","SLIDE","SMILE","STEER"],  // 35 · Feb 4
  ["IDEAS","SALTS","VERSE","PALES","ITEMS"],  // 36 · Feb 5
  ["GROAN","PANES","ROBES","LAMPS","SPRAY"],  // 37 · Feb 6
  ["BAKER","DOWRY","SPELT","STRAP","TIMER"],  // 38 · Feb 7
  ["THREE","CARES","ANGEL","LEAST","PEDAL"],  // 39 · Feb 8
  ["HIRES","BRUTE","WEIRD","GLARE","TRADE"],  // 40 · Feb 9
  ["LUMPS","SHAPE","EVILS","EARLY","REACT"],  // 41 · Feb 10
  ["BEAST","BELOW","DIETS","RESIN","CLASP"],  // 42 · Feb 11
  ["PARSE","HEATS","COAST","SWINE","TEAMS"],  // 43 · Feb 12
  ["STARE","SHAPE","SPELT","LUMPS","TEAMS"],  // 44 · Feb 13
  ["TRADE","CLASP","SLIDE","EARNS","HEART"],  // 45 · Feb 14
  ["ROBES","BAKER","PEDAL","HIRES","PARSE"],  // 46 · Feb 15
  ["REACT","RESIN","BEAST","ITEMS","STAIN"],  // 47 · Feb 16
  ["ALERT","HEATS","EARLY","RENTS","STRAP"],  // 48 · Feb 17
  ["SWEAR","TIMER","TRIES","SPOTS","WEIRD"],  // 49 · Feb 18
  ["PETAL","STARE","VERSE","SPORE","BEGIN"],  // 50 · Feb 19
  ["PALES","WORSE","ANGEL","BELOW","FLOWS"],  // 51 · Feb 20
  ["SWINE","SMILE","EVILS","LEAST","SALTS"],  // 52 · Feb 21
  ["GLARE","THREE","BRUTE","SKATE","COAST"],  // 53 · Feb 22
  ["POOLS","DIETS","PANES","IDEAS","SPACE"],  // 54 · Feb 23
  ["GROAN","LOVES","DEALS","NOTES","LAIRS"],  // 55 · Feb 24
  ["NAMES","BREAD","LEASH","LAMPS","WIRES"],  // 56 · Feb 25
  ["DOWRY","STEER","NAILS","CARES","SHEAR"],  // 57 · Feb 26
  ["COINS","SPRAY","TILES","SHEAR","DIETS"],  // 58 · Feb 27
  ["PALES","WEIRD","LEASH","THREE","TRIES"],  // 59 · Feb 28
  ["POOLS","SALTS","BEAST","REACT","FLOWS"],  // 60 · Mar 1
  ["LEAST","CLASP","STAIN","SPORE","SWEAR"],  // 61 · Mar 2
  ["SPACE","COINS","SPELT","SHAPE","EARNS"],  // 62 · Mar 3
  ["IDEAS","ALERT","SWINE","TEAMS","GROAN"],  // 63 · Mar 4
  ["LAMPS","BREAD","LOVES","SMILE","TRADE"],  // 64 · Mar 5
  ["STEER","NOTES","NAMES","HEART","HIRES"],  // 65 · Mar 6
  ["RESIN","STARE","SLIDE","RENTS","COAST"],  // 66 · Mar 7
  ["SKATE","LUMPS","PEDAL","PETAL","WIRES"],  // 67 · Mar 8
  ["EVILS","ROBES","SPOTS","STRAP","DOWRY"],  // 68 · Mar 9
  ["VERSE","GLARE","DEALS","TIMER","BELOW"],  // 69 · Mar 10
  ["NAILS","ITEMS","BAKER","TILES","LAIRS"],  // 70 · Mar 11
  ["ANGEL","WORSE","PANES","BRUTE","PARSE"],  // 71 · Mar 12
  ["SPRAY","HEATS","EARLY","CARES","BEGIN"],  // 72 · Mar 13
  ["SPRAY","ROBES","SHEAR","SLIDE","LUMPS"],  // 73 · Mar 14
  ["LEAST","COAST","SPORE","HEATS","SALTS"],  // 74 · Mar 15
  ["IDEAS","BRUTE","HEART","ITEMS","NOTES"],  // 75 · Mar 16
  ["GLARE","TRADE","SPACE","SMILE","TIMER"],  // 76 · Mar 17
  ["CARES","CLASP","BEAST","NAILS","PALES"],  // 77 · Mar 18
  ["PARSE","BAKER","HIRES","WORSE","STAIN"],  // 78 · Mar 19
  ["LAIRS","STARE","TEAMS","GROAN","COINS"],  // 79 · Mar 20
  ["SPOTS","TILES","NAMES","WIRES","VERSE"],  // 80 · Mar 21
  ["EARLY","STRAP","SKATE","DOWRY","DEALS"],  // 81 · Mar 22
  ["FLOWS","RENTS","BELOW","POOLS","RESIN"],  // 82 · Mar 23
  ["BEGIN","LEASH","LAMPS","PANES","ALERT"],  // 83 · Mar 24
  ["DIETS","EVILS","SWEAR","SWINE","PETAL"],  // 84 · Mar 25
  ["SHAPE","STEER","TRIES","REACT","WEIRD"],  // 85 · Mar 26
  ["SPELT","EARNS","THREE","BREAD","LOVES"],  // 86 · Mar 27
  ["ANGEL","PEDAL","CLASP","PARSE","LEASH"],  // 87 · Mar 28
  ["BEAST","SMILE","PEDAL","NOTES","BRUTE"],  // 88 · Mar 29
  ["LOVES","BAKER","TIMER","LEAST","TEAMS"],  // 89 · Mar 30
  ["SALTS","RESIN","ROBES","BREAD","LAIRS"],  // 90 · Mar 31
  ["FLOWS","ALERT","COINS","WORSE","STARE"],  // 91 · Apr 1
  ["STEER","CARES","IDEAS","HIRES","TRIES"],  // 92 · Apr 2
  ["BELOW","ITEMS","PETAL","VERSE","SPRAY"],  // 93 · Apr 3
  ["SHAPE","GROAN","POOLS","DOWRY","LUMPS"],  // 94 · Apr 4
  ["TRADE","THREE","SPACE","HEATS","SPORE"],  // 95 · Apr 5
  ["EARNS","NAILS","EVILS","STAIN","BEGIN"],  // 96 · Apr 6
  ["TILES","WEIRD","SPELT","LAMPS","DEALS"],  // 97 · Apr 7
  ["SHEAR","COAST","REACT","PANES","HEART"],  // 98 · Apr 8
  ["SWINE","STRAP","DIETS","SKATE","GLARE"],  // 99 · Apr 9
  ["WIRES","SPOTS","EARLY","RENTS","ANGEL"],  // 100 · Apr 10
  ["PALES","SWEAR","SLIDE","NAMES","COINS"],  // 101 · Apr 11
  ["LAIRS","SPRAY","LEAST","PARSE","SLIDE"],  // 102 · Apr 12
  ["BAKER","LAMPS","DEALS","BELOW","ANGEL"],  // 103 · Apr 13
  ["RENTS","SWINE","HEART","PETAL","PANES"],  // 104 · Apr 14
  ["COAST","EVILS","SPORE","STRAP","TILES"],  // 105 · Apr 15
  ["NOTES","BRUTE","EARLY","DOWRY","STEER"],  // 106 · Apr 16
  ["SMILE","LEASH","EARNS","SWEAR","TRADE"],  // 107 · Apr 17
  ["NAILS","TEAMS","BREAD","ALERT","CLASP"],  // 108 · Apr 18
  ["WIRES","FLOWS","ROBES","LOVES","CARES"],  // 109 · Apr 19
  ["GLARE","IDEAS","WORSE","THREE","VERSE"],  // 110 · Apr 20
  ["DIETS","STARE","SPACE","HIRES","SPELT"],  // 111 · Apr 21
  ["SALTS","ITEMS","SHEAR","PEDAL","TIMER"],  // 112 · Apr 22
  ["NAMES","PALES","SHAPE","HEATS","STAIN"],  // 113 · Apr 23
  ["SKATE","BEAST","RESIN","SPOTS","BEGIN"],  // 114 · Apr 24
  ["TRIES","WEIRD","POOLS","LUMPS","REACT"],  // 115 · Apr 25
  ["GROAN","STAIN","STEER","SALTS","FLOWS"],  // 116 · Apr 26
  ["SPOTS","PALES","RESIN","NOTES","TRIES"],  // 117 · Apr 27
  ["SPELT","GLARE","TEAMS","ROBES","NAILS"],  // 118 · Apr 28
  ["LEASH","CARES","LOVES","PETAL","TRADE"],  // 119 · Apr 29
  ["LAIRS","REACT","DEALS","SHAPE","BRUTE"],  // 120 · Apr 30
  ["LAMPS","VERSE","PARSE","BELOW","HEATS"],  // 121 · May 1
  ["LEAST","GROAN","HIRES","SMILE","WIRES"],  // 122 · May 2
  ["STRAP","EVILS","RENTS","ITEMS","BREAD"],  // 123 · May 3
  ["SKATE","EARLY","SPACE","ALERT","SWEAR"],  // 124 · May 4
  ["ANGEL","DIETS","DOWRY","BAKER","THREE"],  // 125 · May 5
  ["HEART","CLASP","SWINE","SPRAY","NAMES"],  // 126 · May 6
  ["COAST","TILES","WORSE","EARNS","IDEAS"],  // 127 · May 7
  ["SPORE","SLIDE","PEDAL","STARE","COINS"],  // 128 · May 8
  ["BEAST","SHEAR","POOLS","PANES","WEIRD"],  // 129 · May 9
  ["BEGIN","TIMER","LUMPS","THREE","LEAST"],  // 130 · May 10
  ["SHAPE","STAIN","COAST","POOLS","STARE"],  // 131 · May 11
  ["EARLY","BELOW","FLOWS","EVILS","HEATS"],  // 132 · May 12
  ["SALTS","ANGEL","SPOTS","BEAST","SPACE"],  // 133 · May 13
  ["DEALS","NOTES","BEGIN","COINS","RENTS"],  // 134 · May 14
  ["NAILS","TRIES","TIMER","TRADE","ITEMS"],  // 135 · May 15
  ["LOVES","SPORE","RESIN","SMILE","SWINE"],  // 136 · May 16
  ["SHEAR","TILES","GLARE","REACT","VERSE"],  // 137 · May 17
  ["LEASH","PALES","LUMPS","DOWRY","CLASP"],  // 138 · May 18
  ["WORSE","PEDAL","GROAN","BREAD","NAMES"],  // 139 · May 19
  ["PANES","ROBES","SPRAY","HIRES","LAMPS"],  // 140 · May 20
  ["EARNS","DIETS","STRAP","SKATE","WEIRD"],  // 141 · May 21
  ["IDEAS","BRUTE","BAKER","PETAL","ALERT"],  // 142 · May 22
  ["SPELT","TEAMS","HEART","WIRES","CARES"],  // 143 · May 23
  ["SLIDE","PARSE","LAIRS","STEER","SWEAR"],  // 144 · May 24
  ["SMILE","PANES","ROBES","NOTES","SKATE"],  // 145 · May 25
  ["BRUTE","LUMPS","PALES","LEAST","HEART"],  // 146 · May 26
  ["DIETS","RENTS","STARE","LEASH","LOVES"],  // 147 · May 27
  ["SPACE","VERSE","BAKER","HIRES","BELOW"],  // 148 · May 28
  ["COAST","PEDAL","TILES","IDEAS","SLIDE"],  // 149 · May 29
  ["TEAMS","DOWRY","CARES","SPELT","TRIES"],  // 150 · May 30
  ["GROAN","PARSE","RESIN","POOLS","SHEAR"],  // 151 · May 31
  ["SPRAY","REACT","WIRES","DEALS","CLASP"],  // 152 · Jun 1
  ["SWINE","STAIN","WEIRD","GLARE","TRADE"],  // 153 · Jun 2
  ["SPOTS","SWEAR","COINS","BEAST","FLOWS"],  // 154 · Jun 3
  ["SPORE","BEGIN","TIMER","SHAPE","HEATS"],  // 155 · Jun 4
  ["EARNS","ITEMS","PETAL","EARLY","LAIRS"],  // 156 · Jun 5
  ["EVILS","BREAD","ANGEL","LAMPS","SALTS"],  // 157 · Jun 6
  ["THREE","STRAP","ALERT","NAILS","WORSE"],  // 158 · Jun 7
  ["NAMES","STEER","DIETS","GROAN","EARLY"],  // 159 · Jun 8
  ["DOWRY","BAKER","SALTS","WIRES","WORSE"],  // 160 · Jun 9
  ["SKATE","REACT","LOVES","SHAPE","BEGIN"],  // 161 · Jun 10
  ["PANES","SWINE","HEART","DEALS","LUMPS"],  // 162 · Jun 11
  ["CARES","TEAMS","RESIN","PEDAL","TIMER"],  // 163 · Jun 12
  ["ITEMS","PARSE","TRIES","SPRAY","PETAL"],  // 164 · Jun 13
  ["BREAD","SMILE","VERSE","IDEAS","RENTS"],  // 165 · Jun 14
  ["GLARE","SWEAR","STRAP","STEER","STARE"],  // 166 · Jun 15
  ["BEAST","NAMES","TILES","SPACE","ALERT"],  // 167 · Jun 16
  ["WEIRD","LAMPS","THREE","SPORE","HIRES"],  // 168 · Jun 17
  ["COINS","SPELT","CLASP","LEASH","EVILS"],  // 169 · Jun 18
  ["BELOW","STAIN","TRADE","HEATS","PALES"],  // 170 · Jun 19
  ["SLIDE","ROBES","BRUTE","LAIRS","LEAST"],  // 171 · Jun 20
  ["POOLS","COAST","SPOTS","ANGEL","FLOWS"],  // 172 · Jun 21
  ["SHEAR","NAILS","EARNS","NOTES","SPACE"],  // 173 · Jun 22
  ["SWINE","SHAPE","VERSE","PETAL","SMILE"],  // 174 · Jun 23
  ["REACT","SPORE","COINS","BAKER","DIETS"],  // 175 · Jun 24
  ["NOTES","NAILS","WORSE","STRAP","HIRES"],  // 176 · Jun 25
  ["SKATE","GROAN","PARSE","HEATS","TRIES"],  // 177 · Jun 26
  ["CARES","LOVES","STARE","PEDAL","LAIRS"],  // 178 · Jun 27
  ["LUMPS","ITEMS","GLARE","SHEAR","SLIDE"],  // 179 · Jun 28
  ["SWEAR","RENTS","EVILS","BREAD","COAST"],  // 180 · Jun 29
  ["STEER","LAMPS","THREE","POOLS","BEAST"],  // 181 · Jun 30
  ["CLASP","BRUTE","NAMES","TILES","TIMER"],  // 182 · Jul 1
  ["DEALS","EARNS","WIRES","SPRAY","HEART"],  // 183 · Jul 2
  ["TRADE","STAIN","IDEAS","RESIN","FLOWS"],  // 184 · Jul 3
  ["PANES","PALES","ROBES","EARLY","LEASH"],  // 185 · Jul 4
  ["LEAST","SPOTS","TEAMS","BELOW","SPELT"],  // 186 · Jul 5
  ["ANGEL","DOWRY","SALTS","BEGIN","WEIRD"],  // 187 · Jul 6
  ["ALERT","PARSE","NOTES","IDEAS","SPACE"],  // 188 · Jul 7
  ["STARE","HEATS","BELOW","VERSE","PETAL"],  // 189 · Jul 8
  ["GROAN","BREAD","PALES","DOWRY","STAIN"],  // 190 · Jul 9
  ["SALTS","REACT","TILES","WORSE","DIETS"],  // 191 · Jul 10
  ["ANGEL","GLARE","SKATE","TRADE","COINS"],  // 192 · Jul 11
  ["SMILE","TRIES","ALERT","NAMES","LEAST"],  // 193 · Jul 12
  ["STRAP","COAST","SPRAY","STEER","HIRES"],  // 194 · Jul 13
  ["ROBES","SHEAR","SPOTS","BEGIN","RESIN"],  // 195 · Jul 14
  ["LUMPS","FLOWS","WIRES","LAIRS","TEAMS"],  // 196 · Jul 15
  ["EARLY","BRUTE","LEASH","TIMER","POOLS"],  // 197 · Jul 16
  ["SLIDE","SWEAR","SPELT","THREE","NAILS"],  // 198 · Jul 17
  ["SPORE","BEAST","LAMPS","EARNS","EVILS"],  // 199 · Jul 18
  ["WEIRD","BAKER","CLASP","SHAPE","ITEMS"],  // 200 · Jul 19
  ["DEALS","SWINE","RENTS","HEART","PANES"],  // 201 · Jul 20
  ["PEDAL","CARES","LOVES","SKATE","EVILS"],  // 202 · Jul 21
  ["COINS","RENTS","SALTS","DEALS","STEER"],  // 203 · Jul 22
  ["DIETS","CARES","TRIES","TIMER","ALERT"],  // 204 · Jul 23
  ["HEART","IDEAS","SPRAY","PARSE","LEASH"],  // 205 · Jul 24
  ["SLIDE","EARLY","RESIN","PALES","ROBES"],  // 206 · Jul 25
  ["FLOWS","HEATS","LUMPS","SPORE","SPELT"],  // 207 · Jul 26
  ["EARNS","SHAPE","SHEAR","CLASP","WEIRD"],  // 208 · Jul 27
  ["DOWRY","WIRES","NAMES","BELOW","STARE"],  // 209 · Jul 28
  ["HIRES","WORSE","COAST","LEAST","SWEAR"],  // 210 · Jul 29
  ["LAIRS","BAKER","GLARE","TILES","SWINE"],  // 211 · Jul 30
  ["ITEMS","TRADE","TEAMS","REACT","PANES"],  // 212 · Jul 31
  ["SPOTS","THREE","PETAL","GROAN","LOVES"],  // 213 · Aug 1
  ["BREAD","POOLS","LAMPS","VERSE","PEDAL"],  // 214 · Aug 2
  ["STAIN","ANGEL","SMILE","NOTES","NAILS"],  // 215 · Aug 3
  ["BRUTE","BEGIN","BEAST","SPACE","STRAP"],  // 216 · Aug 4
  ["SKATE","STEER","ALERT","STAIN","SPORE"],  // 217 · Aug 5
  ["HEATS","RESIN","SWINE","EARNS","GROAN"],  // 218 · Aug 6
  ["GLARE","POOLS","LUMPS","TRIES","BEAST"],  // 219 · Aug 7
  ["CARES","SHAPE","BELOW","THREE","REACT"],  // 220 · Aug 8
  ["ANGEL","LAIRS","EARLY","SWEAR","WEIRD"],  // 221 · Aug 9
  ["WORSE","LOVES","TRADE","BREAD","DOWRY"],  // 222 · Aug 10
  ["PALES","FLOWS","STRAP","PANES","SLIDE"],  // 223 · Aug 11
  ["SPRAY","EVILS","LEASH","IDEAS","CLASP"],  // 224 · Aug 12
  ["WIRES","LAMPS","NOTES","COINS","ROBES"],  // 225 · Aug 13
  ["DEALS","TIMER","SPOTS","NAILS","BRUTE"],  // 226 · Aug 14
  ["SHEAR","TEAMS","ITEMS","COAST","PETAL"],  // 227 · Aug 15
  ["LEAST","PARSE","BAKER","VERSE","HEART"],  // 228 · Aug 16
  ["BEGIN","DIETS","RENTS","NAMES","STARE"],  // 229 · Aug 17
  ["SPACE","SALTS","PEDAL","TILES","SMILE"],  // 230 · Aug 18
  ["HIRES","SPELT","COAST","SPACE","STARE"],  // 231 · Aug 19
  ["REACT","LEASH","GROAN","TRIES","DOWRY"],  // 232 · Aug 20
  ["PEDAL","WEIRD","SPORE","ROBES","STEER"],  // 233 · Aug 21
  ["EVILS","TEAMS","LUMPS","STAIN","PETAL"],  // 234 · Aug 22
  ["THREE","LAIRS","POOLS","CLASP","RESIN"],  // 235 · Aug 23
  ["STRAP","SHEAR","SHAPE","LEAST","RENTS"],  // 236 · Aug 24
  ["ALERT","SPRAY","BRUTE","BAKER","EARLY"],  // 237 · Aug 25
  ["COINS","SMILE","DIETS","LOVES","SWINE"],  // 238 · Aug 26
  ["BEAST","SLIDE","BEGIN","DEALS","NAILS"],  // 239 · Aug 27
  ["SKATE","ITEMS","IDEAS","SWEAR","SALTS"],  // 240 · Aug 28
  ["NAMES","CARES","EARNS","HIRES","BELOW"],  // 241 · Aug 29
  ["TILES","ANGEL","TRADE","HEART","SPELT"],  // 242 · Aug 30
  ["LAMPS","HEATS","PARSE","NOTES","WORSE"],  // 243 · Aug 31
  ["PANES","SPOTS","FLOWS","WIRES","PALES"],  // 244 · Sep 1
  ["TIMER","BREAD","VERSE","GLARE","DIETS"],  // 245 · Sep 2
  ["POOLS","BEAST","DEALS","LAIRS","WIRES"],  // 246 · Sep 3
  ["LEASH","TRIES","PEDAL","ITEMS","STAIN"],  // 247 · Sep 4
  ["HEATS","SPORE","LAMPS","COAST","BREAD"],  // 248 · Sep 5
  ["PARSE","DOWRY","FLOWS","SMILE","TIMER"],  // 249 · Sep 6
  ["NAMES","SHAPE","BRUTE","LUMPS","STARE"],  // 250 · Sep 7
  ["PALES","ALERT","SALTS","WORSE","SWINE"],  // 251 · Sep 8
  ["SPELT","RENTS","HIRES","BAKER","STEER"],  // 252 · Sep 9
  ["THREE","SHEAR","PANES","STRAP","VERSE"],  // 253 · Sep 10
  ["CLASP","GLARE","HEART","NAILS","IDEAS"],  // 254 · Sep 11
  ["WEIRD","SKATE","TILES","SPOTS","CARES"],  // 255 · Sep 12
  ["TRADE","BELOW","SPACE","LOVES","REACT"],  // 256 · Sep 13
  ["SLIDE","EVILS","LEAST","NOTES","ROBES"],  // 257 · Sep 14
  ["TEAMS","SPRAY","GROAN","EARNS","SWEAR"],  // 258 · Sep 15
  ["PETAL","RESIN","BEGIN","EARLY","COINS"],  // 259 · Sep 16
  ["ANGEL","SPOTS","SPORE","SMILE","EVILS"],  // 260 · Sep 17
  ["PANES","DEALS","BEGIN","STAIN","PETAL"],  // 261 · Sep 18
  ["ROBES","LEAST","BREAD","VERSE","LAIRS"],  // 262 · Sep 19
  ["PALES","HEATS","ALERT","STARE","DOWRY"],  // 263 · Sep 20
  ["THREE","ITEMS","LAMPS","HIRES","PEDAL"],  // 264 · Sep 21
  ["IDEAS","ANGEL","GLARE","LUMPS","EARNS"],  // 265 · Sep 22
  ["BAKER","POOLS","EARLY","LOVES","RENTS"],  // 266 · Sep 23
  ["STEER","TRADE","TILES","LEASH","DIETS"],  // 267 · Sep 24
  ["NOTES","SPRAY","SPELT","BRUTE","SHEAR"],  // 268 · Sep 25
  ["COAST","SPACE","WIRES","TEAMS","STRAP"],  // 269 · Sep 26
  ["RESIN","BEAST","GROAN","TIMER","NAMES"],  // 270 · Sep 27
  ["NAILS","WEIRD","SKATE","PARSE","COINS"],  // 271 · Sep 28
  ["SHAPE","TRIES","CARES","CLASP","SALTS"],  // 272 · Sep 29
  ["FLOWS","SWEAR","HEART","SWINE","BELOW"],  // 273 · Sep 30
  ["SLIDE","REACT","WORSE","SPOTS","LAMPS"],  // 274 · Oct 1
  ["CLASP","FLOWS","NAMES","DOWRY","HIRES"],  // 275 · Oct 2
  ["STAIN","POOLS","TEAMS","NAILS","TRADE"],  // 276 · Oct 3
  ["SPACE","THREE","BRUTE","IDEAS","ALERT"],  // 277 · Oct 4
  ["SALTS","STEER","TRIES","LOVES","SLIDE"],  // 278 · Oct 5
  ["SPORE","EVILS","BELOW","SKATE","SWINE"],  // 279 · Oct 6
  ["WEIRD","DIETS","SWEAR","SPRAY","BAKER"],  // 280 · Oct 7
  ["LAIRS","SMILE","BREAD","EARLY","PEDAL"],  // 281 · Oct 8
  ["ITEMS","PETAL","SPELT","PARSE","PANES"],  // 282 · Oct 9
  ["SHEAR","WORSE","CAPER","PALES","THREE"],  // 283 · Oct 10
  ["TRADE","DEARS","SKATE","SWEAR","PRIEST"],  // 284 · Oct 11
  ["FLOWS","SALTS","LAYERS","COINS","COAST"],  // 285 · Oct 12
  ["SPACE","PISTOL","BEAST","STREAK","SPREAD"],  // 286 · Oct 13
  ["PARSE","DIETS","LEAST","BREAD","SPEARS"],  // 287 · Oct 14
  ["BRUTE","SMILE","GROAN","STRAP","WORSE"],  // 288 · Oct 15
  ["STARE","NAILS","THREE","BEARS","STAKES"],  // 289 · Oct 16
  ["TIMER","TRACES","LAIRS","FEAST","LUMPS"],  // 290 · Oct 17
  ["WEIRD","LEASH","SAFER","SPELT","SPRAY"],  // 291 · Oct 18
  ["LAMPS","STAKED","POLES","HATRED","SINGER"],  // 292 · Oct 19
  ["CAPER","SPORE","PLATES","TRIES","SHEAR"],  // 293 · Oct 20
  ["MENTAL","SLIDE","VERSE","MISTER","RENTS"],  // 294 · Oct 21
  ["DANGER","REMAIN","SOLEMN","BEGIN","ANGEL"],  // 295 · Oct 22
  ["ROOTS","PEDALS","DEALS","SILVER","BELOW"],  // 296 · Oct 23
  ["SIGNED","PETAL","NAMES","GLARE","ALERT"],  // 297 · Oct 24
  ["BAKER","WIRES","LOVES","ROBES","PANES"],  // 298 · Oct 25
  ["HIRES","MARES","ARTIST","SHAPE","PLAYER"],  // 299 · Oct 26
  ["STEER","STAIN","STARED","SCARED","EARLY"],  // 300 · Oct 27
  ["PISTOL","LADIES","SAFER","DANGER","PETAL"],  // 301 · Oct 28
  ["ROBES","HEATS","STAIN","SPOTS","PEDAL"],  // 302 · Oct 29
  ["HATRED","SPORE","BREAKS","PANES","MENTAL"],  // 303 · Oct 30
  ["RENTS","HIRES","FOREST","LAYERS","STABLE"],  // 304 · Oct 31
  ["SPINE","MISTER","DIAPER","PALES","STAKED"],  // 305 · Nov 1
  ["EVILS","NAILS","NOTES","SHEAR","HEART"],  // 306 · Nov 2
  ["THREE","RESIN","WARNED","BELOW","SUBTLE"],  // 307 · Nov 3
  ["SINGER","EARLY","STAKES","WEIRD","BRUISE"],  // 308 · Nov 4
  ["PLATES","SPREAD","COAST","LAIRS","LUMPS"],  // 309 · Nov 5
  ["MARES","LAMPS","SALTS","ANGEL","PLAYER"],  // 310 · Nov 6
  ["POLES","SPACE","LOVES","FEAST","SHAPE"],  // 311 · Nov 7
  ["TEAMS","DEALS","CARED","FIRES","SWINE"],  // 312 · Nov 8
  ["LEASH","PEDALS","SEARCH","SHARES","ROOTS"],  // 313 · Nov 9
  ["COINS","WIRES","STARED","SKATE","TRANCE"],  // 314 · Nov 10
  ["REACT","TILES","TRACES","POOLS","SPRAY"],  // 315 · Nov 11
  ["CARES","EARNS","FLOWS","IDEAS","BAKER"],  // 316 · Nov 12
  ["LISTEN","SWEAR","TRIES","READER","STARE"],  // 317 · Nov 13
  ["SOLEMN","STEER","VERSE","STRAP","SCARED"],  // 318 · Nov 14
  ["TIMER","BEGIN","RECALL","SILVER","SIGNED"],  // 319 · Nov 15
  ["TRADE","SMILE","GLARE","CLASP","BREAD"],  // 320 · Nov 16
  ["ITEMS","REMAIN","BEAST","CAPER","PARSE"],  // 321 · Nov 17
  ["WORSE","SEATED","BEARS","PRIEST","LEAST"],  // 322 · Nov 18
  ["DIETS","BRUTE","SLIDE","ARTIST","NAMES"],  // 323 · Nov 19
  ["GROAN","DETOUR","PLANE","DEARS","ORDEAL"],  // 324 · Nov 20
  ["DOWRY","SPELT","STREAK","SPEARS","ALERT"],  // 325 · Nov 21
  ["CARED","FOREST","DANGER","EVILS","IDEAS"],  // 326 · Nov 22
  ["TEAMS","COINS","PEDALS","STAIN","SWEAR"],  // 327 · Nov 23
  ["BRUTE","LAMPS","SCARED","DIAPER","BEARS"],  // 328 · Nov 24
  ["SPINE","TRACES","SPELT","CAPER","ORDEAL"],  // 329 · Nov 25
  ["HATRED","ANGEL","FIRES","STAKED","HEART"],  // 330 · Nov 26
  ["PLAYER","THREE","WARNED","TILES","REMAIN"],  // 331 · Nov 27
  ["LAYERS","FLOWS","SKATE","ALERT","STAKES"],  // 332 · Nov 28
  ["POOLS","LISTEN","DETOUR","PISTOL","READER"],  // 333 · Nov 29
  ["SPREAD","COAST","STEER","SEATED","BREAD"],  // 334 · Nov 30
  ["GLARE","SUBTLE","LEAST","MENTAL","STREAK"],  // 335 · Dec 1
  ["EARNS","DEARS","DIETS","LEASH","SPOTS"],  // 336 · Dec 2
  ["LADIES","NAMES","NOTES","SPEARS","GROAN"],  // 337 · Dec 3
  ["PLATES","TIMER","ROBES","SLIDE","HIRES"],  // 338 · Dec 4
  ["BEAST","ROOTS","SALTS","SHAPE","SMILE"],  // 339 · Dec 5
  ["WIRES","EARLY","BELOW","VERSE","TRIES"],  // 340 · Dec 6
  ["REACT","LAIRS","RESIN","BREAKS","PALES"],  // 341 · Dec 7
  ["CARES","HEATS","STARED","SHARES","STARE"],  // 342 · Dec 8
  ["SOLEMN","SINGER","ARTIST","TRANCE","BEGIN"],  // 343 · Dec 9
  ["PARSE","PETAL","PLANE","STRAP","SHEAR"],  // 344 · Dec 10
  ["LUMPS","DEALS","MISTER","WORSE","PEDAL"],  // 345 · Dec 11
  ["WEIRD","SPACE","RENTS","PANES","FEAST"],  // 346 · Dec 12
  ["SILVER","SPORE","SAFER","ITEMS","BRUISE"],  // 347 · Dec 13
  ["PRIEST","DOWRY","RECALL","NAILS","CLASP"],  // 348 · Dec 14
  ["SWINE","SPRAY","STABLE","POLES","TRADE"],  // 349 · Dec 15
  ["LOVES","BAKER","SIGNED","SEARCH","MARES"],  // 350 · Dec 16
  ["STARED","SKATE","PARSE","TIMER","LADIES"],  // 351 · Dec 17
  ["CAPER","HEART","TRADE","LAYERS","BRUTE"],  // 352 · Dec 18
  ["FEAST","PETAL","SPELT","DEARS","SHAPE"],  // 353 · Dec 19
  ["STRAP","STAIN","TRIES","COAST","PALES"],  // 354 · Dec 20
  ["STEER","ITEMS","SHEAR","STAKES","WORSE"],  // 355 · Dec 21
  ["CARED","SWINE","BELOW","BEARS","STARE"],  // 356 · Dec 22
  ["POLES","PANES","ROOTS","SPOTS","SALTS"],  // 357 · Dec 23
  ["DANGER","HATRED","LAIRS","STABLE","LEAST"],  // 358 · Dec 24
  ["BEAST","DETOUR","SPACE","VERSE","ANGEL"],  // 359 · Dec 25
  ["NOTES","GROAN","FIRES","CLASP","REMAIN"],  // 360 · Dec 26
  ["STREAK","STAKED","DOWRY","PRIEST","IDEAS"],  // 361 · Dec 27
  ["RECALL","CARES","MENTAL","PLANE","PEDALS"],  // 362 · Dec 28
  ["BEGIN","MISTER","LAMPS","SPORE","SUBTLE"],  // 363 · Dec 29
  ["RENTS","BREAKS","HIRES","READER","SEARCH"],  // 364 · Dec 30
  ["LOVES","POOLS","FLOWS","PEDAL","LISTEN"]  // 365 · Dec 31
];
