// Tumble puzzles.
//
// Each puzzle has:
//   letters - the scrambled word shown on the tiles, in capitals
//   clues   - two clues: the first for the main word, the second for the bonus word
//   answers - the two answers, in the same order. Both must use exactly the letters above.
//
// Every game picks five of these at random. All puzzles must be original.

window.TUMBLE_PUZZLES = [
  { letters: "HEART", clues: ["The ground beneath you", "Bonus: someone full of dislike"], answers: ["EARTH", "HATER"] },
  { letters: "NOTES", clues: ["A rock", "Bonus: the start of something"], answers: ["STONE", "ONSET"] },
  { letters: "PARSE", clues: ["A weapon you throw", "Bonus: an extra one, kept in reserve"], answers: ["SPEAR", "SPARE"] },
  { letters: "SKATE", clues: ["A cut of beef", "Bonus: a wooden post"], answers: ["STEAK", "STAKE"] },
  { letters: "REACT", clues: ["A wooden shipping box", "Bonus: to follow a trail"], answers: ["CRATE", "TRACE"] },
  { letters: "ANGEL", clues: ["Measured in degrees", "Bonus: to gather, bit by bit"], answers: ["ANGLE", "GLEAN"] },
  { letters: "TEAMS", clues: ["It rises from a kettle", "Bonus: friends, in Britain"], answers: ["STEAM", "MATES"] },
  { letters: "SMILE", clues: ["Green citrus fruits", "Bonus: long distances"], answers: ["LIMES", "MILES"] },
  { letters: "BELOW", clues: ["The joint in your arm", "Bonus: part of the gut"], answers: ["ELBOW", "BOWEL"] },
  { letters: "SPOTS", clues: ["Comes to a halt", "Bonus: fence uprights"], answers: ["STOPS", "POSTS"] },
  { letters: "LEAST", clues: ["To take what is not yours", "Bonus: grey rock used for roofing"], answers: ["STEAL", "SLATE"] },
  { letters: "STARE", clues: ["Prices", "Bonus: they fall when you cry"], answers: ["RATES", "TEARS"] },
  { letters: "NAILS", clues: ["A slow creature with a shell", "Bonus: killed, in old stories"], answers: ["SNAIL", "SLAIN"] },
  { letters: "PALES", clues: ["Jumps", "Bonus: a slip, or a gap in time"], answers: ["LEAPS", "LAPSE"] },
  { letters: "LAMPS", clues: ["Tropical trees, or parts of your hands", "Bonus: a song from the Bible"], answers: ["PALMS", "PSALM"] },
  { letters: "SHEAR", clues: ["To divide between people", "Bonus: long-eared animals like big rabbits"], answers: ["SHARE", "HARES"] },
  { letters: "WEIRD", clues: ["Connected by cables", "Bonus: broader"], answers: ["WIRED", "WIDER"] },
  { letters: "COAST", clues: ["Mexican food in folded shells", "Bonus: winter outerwear"], answers: ["TACOS", "COATS"] },
  { letters: "POOLS", clues: ["Thread is wound onto it", "Bonus: circles in a rope"], answers: ["SPOOL", "LOOPS"] },
  { letters: "ITEMS", clues: ["Occasions", "Bonus: tiny bugs"], answers: ["TIMES", "MITES"] },
  { letters: "LOVES", clues: ["To work out a puzzle", "Bonus: small mouse-like animals"], answers: ["SOLVE", "VOLES"] },
  { letters: "DEALS", clues: ["Goes in front", "Bonus: valleys"], answers: ["LEADS", "DALES"] },
  { letters: "FLOWS", clues: ["Farm birds", "Bonus: eats greedily"], answers: ["FOWLS", "WOLFS"] },
  { letters: "BAKER", clues: ["It slows a car", "Bonus: to snap in two"], answers: ["BRAKE", "BREAK"] },
  { letters: "GROAN", clues: ["It is played in church", "Bonus: a gas used in light bulbs"], answers: ["ORGAN", "ARGON"] },
  { letters: "ROBES", clues: ["Not drunk", "Bonus: dull people"], answers: ["SOBER", "BORES"] },
  { letters: "PETAL", clues: ["You eat from it", "Bonus: jumped, in the past"], answers: ["PLATE", "LEAPT"] },
  { letters: "RESIN", clues: ["A loud warning sound", "Bonus: to wash with water"], answers: ["SIREN", "RINSE"] },
  { letters: "STRAP", clues: ["Pieces", "Bonus: they catch animals"], answers: ["PARTS", "TRAPS"] },
  { letters: "IDEAS", clues: ["Out of the way", "Bonus: helpers"], answers: ["ASIDE", "AIDES"] },
  { letters: "EARLY", clues: ["One thickness of something", "Bonus: a race run in stages"], answers: ["LAYER", "RELAY"] },
  { letters: "VERSE", clues: ["To hand out food", "Bonus: to cut through"], answers: ["SERVE", "SEVER"] },
  { letters: "ALERT", clues: ["To change", "Bonus: afterwards"], answers: ["ALTER", "LATER"] },
  { letters: "SHAPE", clues: ["A stage", "Bonus: piles"], answers: ["PHASE", "HEAPS"] },
  { letters: "CARES", clues: ["To frighten", "Bonus: running contests"], answers: ["SCARE", "RACES"] },
  { letters: "HEATS", clues: ["Hurry", "Bonus: dislikes strongly"], answers: ["HASTE", "HATES"] },
  { letters: "NAMES", clues: ["Methods", "Bonus: the hair on lions' necks"], answers: ["MEANS", "MANES"] },
  { letters: "TRIES", clues: ["Rows, one above another", "Bonus: ceremonies"], answers: ["TIERS", "RITES"] },
  { letters: "SPACE", clues: ["Steps", "Bonus: cloaks"], answers: ["PACES", "CAPES"] },
  { letters: "BEAST", clues: ["Rhythms", "Bonus: to spoon juices over a roast"], answers: ["BEATS", "BASTE"] },
  { letters: "DIETS", clues: ["The sea's daily rise and fall", "Bonus: corrects text"], answers: ["TIDES", "EDITS"] },
  { letters: "SWEAR", clues: ["Has on, as clothes", "Bonus: goods for sale"], answers: ["WEARS", "WARES"] },
  { letters: "BREAD", clues: ["Hair on the chin", "Bonus: uncovered"], answers: ["BEARD", "BARED"] },
  { letters: "TRADE", clues: ["The grip on a tyre", "Bonus: given a score"], answers: ["TREAD", "RATED"] },
  { letters: "THREE", clues: ["In that place", "Bonus: an old-fashioned anaesthetic gas"], answers: ["THERE", "ETHER"] },
  { letters: "BEGIN", clues: ["A living creature", "Bonus: a spree of too much eating"], answers: ["BEING", "BINGE"] },
  { letters: "BRUTE", clues: ["A potato is one", "Bonus: to argue against"], answers: ["TUBER", "REBUT"] },
  { letters: "LEASH", clues: ["Gets better", "Bonus: a flaky grey rock"], answers: ["HEALS", "SHALE"] },
  { letters: "WORSE", clues: ["Used bad language", "Bonus: one who plants seeds"], answers: ["SWORE", "SOWER"] },
  { letters: "GLARE", clues: ["Big", "Bonus: fit for a king"], answers: ["LARGE", "REGAL"] },
  { letters: "SALTS", clues: ["Thin strips of wood", "Bonus: goes on for a long time"], answers: ["SLATS", "LASTS"] },
  { letters: "SPRAY", clues: ["Speaks to a god", "Bonus: rough-voiced"], answers: ["PRAYS", "RASPY"] },
  { letters: "EVILS", clues: ["Is alive", "Bonus: face coverings"], answers: ["LIVES", "VEILS"] },
  { letters: "STEER", clues: ["Oaks and pines", "Bonus: to set again"], answers: ["TREES", "RESET"] },
  { letters: "SWINE", clues: ["Drinks made from grapes", "Bonus: a tough cord joining muscle to bone"], answers: ["WINES", "SINEW"] },
  { letters: "LUMPS", clues: ["Purple fruits", "Bonus: a sudden drop"], answers: ["PLUMS", "SLUMP"] },
  { letters: "SPORE", clues: ["Writing that is not poetry", "Bonus: thick cords"], answers: ["PROSE", "ROPES"] },
  { letters: "HIRES", clues: ["They inherit", "Bonus: an English county, or a big horse"], answers: ["HEIRS", "SHIRE"] },
  { letters: "EARNS", clues: ["A trap for rabbits", "Bonus: comes closer"], answers: ["SNARE", "NEARS"] },
  { letters: "STAIN", clues: ["A holy person", "Bonus: a smooth glossy fabric"], answers: ["SAINT", "SATIN"] },
  { letters: "CLASP", clues: ["Applauds", "Bonus: the skin on top of your head"], answers: ["CLAPS", "SCALP"] },
  { letters: "RENTS", clues: ["The back of a ship", "Bonus: seabirds"], answers: ["STERN", "TERNS"] },
  { letters: "PEDAL", clues: ["To beg", "Bonus: went white"], answers: ["PLEAD", "PALED"] },
  { letters: "SLIDE", clues: ["Sits doing nothing", "Bonus: to move sideways shyly"], answers: ["IDLES", "SIDLE"] },
  { letters: "TILES", clues: ["A tiny island", "Bonus: steps for climbing over a fence"], answers: ["ISLET", "STILE"] },
  { letters: "TIMER", clues: ["Worth, or deserving praise", "Bonus: a bishop's tall hat"], answers: ["MERIT", "MITRE"] },
  { letters: "SPELT", clues: ["Had a night's rest", "Bonus: animal skins"], answers: ["SLEPT", "PELTS"] },
  { letters: "WIRES", clues: ["More sensible", "Bonus: small dams across rivers"], answers: ["WISER", "WEIRS"] },
  { letters: "PANES", clues: ["A tree with trembling leaves", "Bonus: the backs of necks"], answers: ["ASPEN", "NAPES"] },
  { letters: "DOWRY", clues: ["Noisy and wild", "Bonus: using too many words"], answers: ["ROWDY", "WORDY"] },
  { letters: "COINS", clues: ["Small pictures on a screen", "Bonus: to do with sound"], answers: ["ICONS", "SONIC"] },
  { letters: "LAIRS", clues: ["People who tell untruths", "Bonus: train tracks"], answers: ["LIARS", "RAILS"] },
  // ---- Added 9 October 2026 ----
  { letters: "PLANE", clues: ["A flat board, or a group of experts", "Bonus: to do with punishment"], answers: ["PANEL", "PENAL"] },
  { letters: "CARED", clues: ["A tree with fragrant wood", "Bonus: ran in a competition"], answers: ["CEDAR", "RACED"] },
  { letters: "DEARS", clues: ["Looks at words on a page", "Bonus: challenges someone to do it"], answers: ["READS", "DARES"] },
  { letters: "SAFER", clues: ["Worries, frights", "Bonus: ticket prices"], answers: ["FEARS", "FARES"] },
  { letters: "ROOTS", clues: ["The body without the arms, legs and head", "Bonus: where hens sleep"], answers: ["TORSO", "ROOST"] },
  { letters: "BEARS", clues: ["A curved sword", "Bonus: uncovers"], answers: ["SABRE", "BARES"] },
  { letters: "FEAST", clues: ["Impressive deeds", "Bonus: what will happen, destinies"], answers: ["FEATS", "FATES"] },
  { letters: "SPINE", clues: ["Evergreen trees", "Bonus: a wading bird, or a nasty remark"], answers: ["PINES", "SNIPE"] },
  { letters: "FIRES", clues: ["Chips, in America", "Bonus: the little foot on a letter in some typefaces"], answers: ["FRIES", "SERIF"] },
  { letters: "MARES", clues: ["To spread grease on something", "Bonus: packs of paper"], answers: ["SMEAR", "REAMS"] },
  { letters: "POLES", clues: ["A hillside", "Bonus: runs with long strides"], answers: ["SLOPE", "LOPES"] },
  { letters: "CAPER", clues: ["A runner who sets the speed", "Bonus: a short summary"], answers: ["PACER", "RECAP"] },
];
