// Swap One puzzles.
//
// Each puzzle has:
//   start - a four-letter word, in capitals
//   steps - three [clue, answer] pairs. Each answer changes exactly one letter of the
//           word before it, in any position.
//
// Every game picks four of these at random. All puzzles must be original.

window.SWAP_ONE_PUZZLES = [
  { start: "COLD", steps: [["A length of string", "CORD"], ["It comes in a deck", "CARD"], ["Not soft", "HARD"]] },
  { start: "WARM", steps: [["A hospital room", "WARD"], ["You are reading one", "WORD"], ["A nobleman", "LORD"]] },
  { start: "FISH", steps: [["You serve food on it", "DISH"], ["A short fast run", "DASH"], ["Paper money", "CASH"]] },
  { start: "BOOK", steps: [["To make a meal", "COOK"], ["Slightly cold", "COOL"], ["You swim in it", "POOL"]] },
  { start: "LAMP", steps: [["To walk unevenly", "LIMP"], ["A green citrus fruit", "LIME"], ["A clock tells it", "TIME"]] },
  { start: "MOON", steps: [["How you feel", "MOOD"], ["You eat it", "FOOD"], ["It goes in a shoe", "FOOT"]] },
  { start: "SAND", steps: [["It has five fingers", "HAND"], ["A group of musicians", "BAND"], ["To tie up", "BIND"]] },
  { start: "RAIN", steps: [["The most important", "MAIN"], ["Letters and parcels", "MAIL"], ["It catches the wind", "SAIL"]] },
  { start: "HEAD", steps: [["To get better after an injury", "HEAL"], ["The back of your foot", "HEEL"], ["To touch, or to sense", "FEEL"]] },
  { start: "MILK", steps: [["A smooth, shiny fabric", "SILK"], ["The ledge under a window", "SILL"], ["To exchange for money", "SELL"]] },
  { start: "BARK", steps: [["With no light", "DARK"], ["A small arrow thrown at a board", "DART"], ["A piece of something", "PART"]] },
  { start: "GOLD", steps: [["Brave", "BOLD"], ["It fastens with a nut", "BOLT"], ["Worn around the waist", "BELT"]] },
  { start: "WIND", steps: [["Made from grapes", "WINE"], ["Belonging to me", "MINE"], ["A fresh-tasting herb", "MINT"]] },
  { start: "SOCK", steps: [["A stone", "ROCK"], ["A chess piece shaped like a castle", "ROOK"], ["Four walls and a door", "ROOM"]] },
  { start: "PINK", steps: [["An evergreen tree", "PINE"], ["A heap", "PILE"], ["Just over 1.6 kilometres", "MILE"]] },
  { start: "CORN", steps: [["A bull has two", "HORN"], ["Came into the world", "BORN"], ["Where hay is stored", "BARN"]] },
  { start: "TALL", steps: [["It holds up the roof", "WALL"], ["To go on foot", "WALK"], ["To speak", "TALK"]] },
  { start: "LOVE", steps: [["To be alive", "LIVE"], ["Draw one with a ruler", "LINE"], ["One ring of a chain", "LINK"]] },
  { start: "FARM", steps: [["A document with blanks to fill in", "FORM"], ["You eat with it", "FORK"], ["It plugs a wine bottle", "CORK"]] },
  { start: "MOTH", steps: [["Sums and numbers at school", "MATH"], ["A long soak in the tub", "BATH"], ["A trail to walk along", "PATH"]] },
  { start: "FIRE", steps: [["To give someone a job", "HIRE"], ["To put out of sight", "HIDE"], ["Left or right", "SIDE"]] },
  { start: "WOLF", steps: [["A game with clubs and holes", "GOLF"], ["A large bay", "GULF"], ["To swallow fast", "GULP"]] },
  { start: "RACE", steps: [["A grain eaten with curry", "RICE"], ["Pleasant", "NICE"], ["Three times three", "NINE"]] },
  { start: "DUCK", steps: [["Where a ship ties up", "DOCK"], ["A key opens it", "LOCK"], ["To use your eyes", "LOOK"]] },
  { start: "SEAT", steps: [["To defeat", "BEAT"], ["Baked, on toast", "BEAN"], ["Unkind", "MEAN"]] },
  { start: "SHIP", steps: [["You buy things in it", "SHOP"], ["To cut with an axe", "CHOP"], ["A fried slice of potato", "CHIP"]] },
  { start: "COAT", steps: [["It floats", "BOAT"], ["A tall shoe", "BOOT"], ["The part of a plant underground", "ROOT"]] },
  { start: "LEAF", steps: [["Bread baked in one piece", "LOAF"], ["A heavy burden", "LOAD"], ["Cars drive on it", "ROAD"]] },
  { start: "SNOW", steps: [["A performance", "SHOW"], ["Not fast", "SLOW"], ["A narrow opening for coins", "SLOT"]] },
  { start: "GAME", steps: [["It swings open in a fence", "GATE"], ["After the agreed time", "LATE"], ["A big pool of fresh water", "LAKE"]] },
  { start: "HOPE", steps: [["A thick cord", "ROPE"], ["A thorny flower", "ROSE"], ["You smell with it", "NOSE"]] },
  { start: "DEEP", steps: [["A woodland animal with antlers", "DEER"], ["A cold drink by the pint", "BEER"], ["A red root vegetable", "BEET"]] },
  { start: "SALT", steps: [["Grain used for brewing", "MALT"], ["A shopping centre", "MALL"], ["It bounces", "BALL"]] },
  { start: "KING", steps: [["Worn on a finger", "RING"], ["Where you skate", "RINK"], ["Dishes are washed in it", "SINK"]] },
  { start: "TENT", steps: [["An exam", "TEST"], ["A bird builds it", "NEST"], ["Where the sun sets", "WEST"]] },
  { start: "CAKE", steps: [["To look after", "CARE"], ["The middle of an apple", "CORE"], ["A greater amount", "MORE"]] },
  { start: "PEAR", steps: [["A big furry animal", "BEAR"], ["A bird's mouth", "BEAK"], ["The top of a mountain", "PEAK"]] },
  { start: "JUMP", steps: [["It pushes up water", "PUMP"], ["A rubbish tip", "DUMP"], ["Slightly wet", "DAMP"]] },
  { start: "WAVE", steps: [["A hollow in a cliff", "CAVE"], ["A bird is kept in it", "CAGE"], ["One side of a sheet in a book", "PAGE"]] },
  { start: "TREE", steps: [["Costing nothing", "FREE"], ["To run away", "FLEE"], ["A tiny jumping pest", "FLEA"]] },
  { start: "GIRL", steps: [["A fish breathes with it", "GILL"], ["A seaside bird", "GULL"], ["Boring", "DULL"]] },
  { start: "MOST", steps: [["Soft green growth on stones", "MOSS"], ["The person in charge", "BOSS"], ["The opposite of a win", "LOSS"]] },
  { start: "STAR", steps: [["A mark left by a wound", "SCAR"], ["To fly high", "SOAR"], ["You wash with it", "SOAP"]] },
  { start: "LION", steps: [["A diving bird on Canadian lakes", "LOON"], ["A circle in a rope", "LOOP"], ["A basketball ring", "HOOP"]] },
  { start: "HILL", steps: [["A sword's handle", "HILT"], ["A clue", "HINT"], ["To chase wild animals", "HUNT"]] },
  { start: "SOUP", steps: [["Sharp-tasting, like lemon", "SOUR"], ["Twice two", "FOUR"], ["Against the rules", "FOUL"]] },
  { start: "WORM", steps: [["Used until shabby", "WORN"], ["Ripped", "TORN"], ["To rotate", "TURN"]] },
  { start: "MASK", steps: [["A spot or stain", "MARK"], ["A green space in town", "PARK"], ["A bonus that comes with a job", "PERK"]] },
  { start: "FLAT", steps: [["One beat of a wing", "FLAP"], ["To turn over", "FLIP"], ["To lose your footing", "SLIP"]] },
  { start: "HERO", steps: [["Basil or mint", "HERB"], ["A doing word", "VERB"], ["Extremely", "VERY"]] },
  { start: "CLAP", steps: [["A hit with an open hand", "SLAP"], ["To shut with a bang", "SLAM"], ["Thin", "SLIM"]] },
  { start: "BOWL", steps: [["To heat water until it bubbles", "BOIL"], ["A loop of wire", "COIL"], ["A penny is one", "COIN"]] },
  { start: "DARE", steps: [["A day on the calendar", "DATE"], ["A friend, or a partner", "MATE"], ["Not female", "MALE"]] },
  { start: "LAKE", steps: [["To be fond of", "LIKE"], ["Two wheels and pedals", "BIKE"], ["What a dog may do with its teeth", "BITE"]] },
  { start: "MIND", steps: [["Gentle, not spicy", "MILD"], ["Not tame", "WILD"], ["Determination", "WILL"]] },
  { start: "BALD", steps: [["A group of musicians", "BAND"], ["A curve", "BEND"], ["Not straight", "BENT"]] },
  { start: "PORK", steps: [["A harbour", "PORT"], ["A kind or type", "SORT"], ["Not hard", "SOFT"]] },
  { start: "VASE", steps: [["A box or container", "CASE"], ["The actors in a play", "CAST"], ["Huge", "VAST"]] },
  { start: "TOAD", steps: [["Said to someone", "TOLD"], ["To keep in your hands", "HOLD"], ["An opening", "HOLE"]] },
  { start: "NAIL", steps: [["A dog wags it", "TAIL"], ["Hard work", "TOIL"], ["Earth in a garden", "SOIL"]] },
  { start: "WEEK", steps: [["An unwanted garden plant", "WEED"], ["A plant grows from it", "SEED"], ["To require", "NEED"]] },
  { start: "PUSH", steps: [["A small shrub", "BUSH"], ["A big party, or a heavy hit", "BASH"], ["To crush potatoes", "MASH"]] },
  { start: "RUST", steps: [["Has to", "MUST"], ["Thin fog", "MIST"], ["To fail to hit", "MISS"]] },
  { start: "NECK", steps: [["A ship's floor, or a pack of cards", "DECK"], ["You write at it", "DESK"], ["A flat round plate", "DISK"]] },
  { start: "FUEL", steps: [["With no room left", "FULL"], ["Autumn", "FALL"], ["To not succeed", "FAIL"]] },
  { start: "WISH", steps: [["To clean with water", "WASH"], ["A striped stinging insect", "WASP"], ["A sharp intake of breath", "GASP"]] },
  { start: "GLUE", steps: [["Gloomy", "GLUM"], ["A purple fruit", "PLUM"], ["The adding sign", "PLUS"]] },
  { start: "TOWN", steps: [["The opposite of up", "DOWN"], ["Sunrise", "DAWN"], ["Grass in front of a house", "LAWN"]] },
  { start: "PEEL", steps: [["To look closely", "PEER"], ["A walkway out over the sea", "PIER"], ["A row above another", "TIER"]] },
  { start: "DIRT", steps: [["What you eat", "DIET"], ["A song for two", "DUET"], ["Fine powder on shelves", "DUST"]] },
  { start: "LUCK", steps: [["What a dog does with its tongue", "LICK"], ["To choose", "PICK"], ["To fill a suitcase", "PACK"]] },
  { start: "MOLE", steps: [["A cross between a horse and a donkey", "MULE"], ["Silent", "MUTE"], ["Sweet and pretty", "CUTE"]] },
  { start: "SWIM", steps: [["Moved through water, in the past", "SWAM"], ["Where two pieces of cloth join", "SEAM"], ["A group of players", "TEAM"]] },
  { start: "BELL", steps: [["To shout", "YELL"], ["A short sharp cry", "YELP"], ["To assist", "HELP"]] },
  { start: "GRIP", steps: [["A single falling drop", "DRIP"], ["To let fall", "DROP"], ["Plants grown on a farm", "CROP"]] },
  { start: "OPEN", steps: [["You bake in it", "OVEN"], ["Finished", "OVER"], ["At any time", "EVER"]] },
  { start: "PLAY", steps: [["Pottery is made from it", "CLAY"], ["A cat's sharp nail", "CLAW"], ["A fault", "FLAW"]] },
  { start: "JOKE", steps: [["To prod with a finger", "POKE"], ["A tiny hole in your skin", "PORE"], ["Clean, with nothing added", "PURE"]] },
  { start: "MEAT", steps: [["Breakfast, lunch or dinner", "MEAL"], ["Not fake", "REAL"], ["A whiskered animal that claps", "SEAL"]] },
  { start: "LIFT", steps: [["Items written one under another", "LIST"], ["Unable to find the way", "LOST"], ["The price", "COST"]] },
  { start: "SING", steps: [["Music with words", "SONG"], ["Not short", "LONG"], ["You breathe with it", "LUNG"]] }
];
